-- db.0012_auto_20230104_0117, recorded by apps/api-go/tools/generate_migration_sql.py. Do not edit by hand.
ALTER TABLE "issue_activity" ADD COLUMN "new_identifier" uuid NULL;
ALTER TABLE "issue_activity" ADD COLUMN "old_identifier" uuid NULL;
SET CONSTRAINTS "module_issues_issue_id_7caa908b_fk_issue_id" IMMEDIATE; ALTER TABLE "module_issues" DROP CONSTRAINT "module_issues_issue_id_7caa908b_fk_issue_id";
DROP INDEX IF EXISTS "module_issues_issue_id_7caa908b";
ALTER TABLE "module_issues" ADD CONSTRAINT "module_issues_issue_id_7caa908b_uniq" UNIQUE ("issue_id");
ALTER TABLE "module_issues" ADD CONSTRAINT "module_issues_issue_id_7caa908b_fk_issue_id" FOREIGN KEY ("issue_id") REFERENCES "issue" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_issues" DROP CONSTRAINT "module_issues_module_id_issue_id_3322d0ea_uniq";
ALTER TABLE "cycle" RENAME TO "cycles";
ALTER TABLE "cycle_issue" RENAME TO "cycle_issues";
ALTER TABLE "file_asset" RENAME TO "file_assets";
ALTER TABLE "issue" RENAME TO "issues";
ALTER TABLE "issue_activity" RENAME TO "issue_activities";
ALTER TABLE "issue_assignee" RENAME TO "issue_assignees";
ALTER TABLE "issue_blocker" RENAME TO "issue_blockers";
ALTER TABLE "issue_comment" RENAME TO "issue_comments";
ALTER TABLE "issue_label" RENAME TO "issue_labels";
ALTER TABLE "issue_property" RENAME TO "issue_properties";
ALTER TABLE "issue_sequence" RENAME TO "issue_sequences";
ALTER TABLE "label" RENAME TO "labels";
ALTER TABLE "module" RENAME TO "modules";
ALTER TABLE "module_member" RENAME TO "module_members";
ALTER TABLE "project" RENAME TO "projects";
ALTER TABLE "project_identifier" RENAME TO "project_identifiers";
ALTER TABLE "project_member" RENAME TO "project_members";
ALTER TABLE "project_member_invite" RENAME TO "project_member_invites";
ALTER TABLE "shortcut" RENAME TO "shortcuts";
ALTER TABLE "social_login_connection" RENAME TO "social_login_connections";
ALTER TABLE "state" RENAME TO "states";
ALTER TABLE "team" RENAME TO "teams";
ALTER TABLE "team_member" RENAME TO "team_members";
ALTER TABLE "issue_timeline" RENAME TO "issue_timelines";
ALTER TABLE "user" RENAME TO "users";
ALTER TABLE "user_groups" RENAME TO "users_groups";
ALTER TABLE "user_user_permissions" RENAME TO "users_user_permissions";
ALTER TABLE "view" RENAME TO "views";
ALTER TABLE "workspace" RENAME TO "workspaces";
ALTER TABLE "workspace_member" RENAME TO "workspace_members";
ALTER TABLE "workspace_member_invite" RENAME TO "workspace_member_invites";
CREATE TABLE "module_links" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "title" varchar(255) NULL, "url" varchar(200) NOT NULL, "created_by_id" uuid NULL, "module_id" uuid NOT NULL, "project_id" uuid NOT NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
ALTER TABLE "module_links" ADD CONSTRAINT "module_links_created_by_id_eaf6492f_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_links" ADD CONSTRAINT "module_links_module_id_0fda3f8a_fk_modules_id" FOREIGN KEY ("module_id") REFERENCES "modules" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_links" ADD CONSTRAINT "module_links_project_id_f720bb79_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_links" ADD CONSTRAINT "module_links_updated_by_id_4da419e7_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_links" ADD CONSTRAINT "module_links_workspace_id_0521c11c_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "module_links_created_by_id_eaf6492f" ON "module_links" ("created_by_id");
CREATE INDEX "module_links_module_id_0fda3f8a" ON "module_links" ("module_id");
CREATE INDEX "module_links_project_id_f720bb79" ON "module_links" ("project_id");
CREATE INDEX "module_links_updated_by_id_4da419e7" ON "module_links" ("updated_by_id");
CREATE INDEX "module_links_workspace_id_0521c11c" ON "module_links" ("workspace_id");
