-- db.0022_auto_20230307_0304, recorded from the Django app this replaced.
ALTER TABLE "cycles" DROP COLUMN "status" CASCADE;
ALTER TABLE "projects" DROP COLUMN "slug" CASCADE;
ALTER TABLE "issue_links" ADD COLUMN "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE "issue_links" ALTER COLUMN "metadata" DROP DEFAULT;
ALTER TABLE "module_links" ADD COLUMN "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE "module_links" ALTER COLUMN "metadata" DROP DEFAULT;
ALTER TABLE "projects" ADD COLUMN "cover_image" varchar(200) NULL;
CREATE TABLE "project_favorites" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "created_by_id" uuid NULL, "project_id" uuid NOT NULL, "updated_by_id" uuid NULL, "user_id" uuid NOT NULL, "workspace_id" uuid NOT NULL);
CREATE TABLE "module_favorites" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "created_by_id" uuid NULL, "module_id" uuid NOT NULL, "project_id" uuid NOT NULL, "updated_by_id" uuid NULL, "user_id" uuid NOT NULL, "workspace_id" uuid NOT NULL);
CREATE TABLE "cycle_favorites" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "created_by_id" uuid NULL, "cycle_id" uuid NOT NULL, "project_id" uuid NOT NULL, "updated_by_id" uuid NULL, "user_id" uuid NOT NULL, "workspace_id" uuid NOT NULL);
ALTER TABLE "project_favorites" ADD CONSTRAINT "project_favorites_project_id_user_id_e7e43312_uniq" UNIQUE ("project_id", "user_id");
ALTER TABLE "project_favorites" ADD CONSTRAINT "project_favorites_created_by_id_613c0717_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "project_favorites" ADD CONSTRAINT "project_favorites_project_id_df76634d_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "project_favorites" ADD CONSTRAINT "project_favorites_updated_by_id_2a663e4d_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "project_favorites" ADD CONSTRAINT "project_favorites_user_id_500f4f5b_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "project_favorites" ADD CONSTRAINT "project_favorites_workspace_id_fa980513_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "project_favorites_created_by_id_613c0717" ON "project_favorites" ("created_by_id");
CREATE INDEX "project_favorites_project_id_df76634d" ON "project_favorites" ("project_id");
CREATE INDEX "project_favorites_updated_by_id_2a663e4d" ON "project_favorites" ("updated_by_id");
CREATE INDEX "project_favorites_user_id_500f4f5b" ON "project_favorites" ("user_id");
CREATE INDEX "project_favorites_workspace_id_fa980513" ON "project_favorites" ("workspace_id");
ALTER TABLE "module_favorites" ADD CONSTRAINT "module_favorites_module_id_user_id_5b36ecc1_uniq" UNIQUE ("module_id", "user_id");
ALTER TABLE "module_favorites" ADD CONSTRAINT "module_favorites_created_by_id_7f84820d_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_favorites" ADD CONSTRAINT "module_favorites_module_id_c4f0736b_fk_modules_id" FOREIGN KEY ("module_id") REFERENCES "modules" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_favorites" ADD CONSTRAINT "module_favorites_project_id_83d9d9e8_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_favorites" ADD CONSTRAINT "module_favorites_updated_by_id_2437fed0_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_favorites" ADD CONSTRAINT "module_favorites_user_id_c5b76375_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_favorites" ADD CONSTRAINT "module_favorites_workspace_id_65a4ac6f_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "module_favorites_created_by_id_7f84820d" ON "module_favorites" ("created_by_id");
CREATE INDEX "module_favorites_module_id_c4f0736b" ON "module_favorites" ("module_id");
CREATE INDEX "module_favorites_project_id_83d9d9e8" ON "module_favorites" ("project_id");
CREATE INDEX "module_favorites_updated_by_id_2437fed0" ON "module_favorites" ("updated_by_id");
CREATE INDEX "module_favorites_user_id_c5b76375" ON "module_favorites" ("user_id");
CREATE INDEX "module_favorites_workspace_id_65a4ac6f" ON "module_favorites" ("workspace_id");
ALTER TABLE "cycle_favorites" ADD CONSTRAINT "cycle_favorites_cycle_id_user_id_51c1ab91_uniq" UNIQUE ("cycle_id", "user_id");
ALTER TABLE "cycle_favorites" ADD CONSTRAINT "cycle_favorites_created_by_id_e888870b_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cycle_favorites" ADD CONSTRAINT "cycle_favorites_cycle_id_8224e5ad_fk_cycles_id" FOREIGN KEY ("cycle_id") REFERENCES "cycles" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cycle_favorites" ADD CONSTRAINT "cycle_favorites_project_id_f2977b66_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cycle_favorites" ADD CONSTRAINT "cycle_favorites_updated_by_id_8576232f_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cycle_favorites" ADD CONSTRAINT "cycle_favorites_user_id_8a04268d_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cycle_favorites" ADD CONSTRAINT "cycle_favorites_workspace_id_07359b0b_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cycle_favorites_created_by_id_e888870b" ON "cycle_favorites" ("created_by_id");
CREATE INDEX "cycle_favorites_cycle_id_8224e5ad" ON "cycle_favorites" ("cycle_id");
CREATE INDEX "cycle_favorites_project_id_f2977b66" ON "cycle_favorites" ("project_id");
CREATE INDEX "cycle_favorites_updated_by_id_8576232f" ON "cycle_favorites" ("updated_by_id");
CREATE INDEX "cycle_favorites_user_id_8a04268d" ON "cycle_favorites" ("user_id");
CREATE INDEX "cycle_favorites_workspace_id_07359b0b" ON "cycle_favorites" ("workspace_id");
