-- db.0023_auto_20230316_0040, recorded from the Django app this replaced.
CREATE TABLE "importers" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "service" varchar(50) NOT NULL, "status" varchar(50) NOT NULL, "metadata" jsonb NOT NULL, "config" jsonb NOT NULL, "data" jsonb NOT NULL, "created_by_id" uuid NULL, "initiated_by_id" uuid NOT NULL, "project_id" uuid NOT NULL, "token_id" uuid NOT NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
CREATE TABLE "issue_views" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "name" varchar(255) NOT NULL, "description" text NOT NULL, "query" jsonb NOT NULL, "access" smallint NOT NULL CHECK ("access" >= 0), "query_data" jsonb NOT NULL, "created_by_id" uuid NULL, "project_id" uuid NOT NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
CREATE TABLE "view_favorites" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "created_by_id" uuid NULL, "project_id" uuid NOT NULL, "updated_by_id" uuid NULL, "user_id" uuid NOT NULL, "view_id" uuid NOT NULL, "workspace_id" uuid NOT NULL);
ALTER TABLE "labels" ADD CONSTRAINT "labels_name_project_id_d8b1b810_uniq" UNIQUE ("name", "project_id");
DROP TABLE "views" CASCADE;
ALTER TABLE "importers" ADD CONSTRAINT "importers_created_by_id_7dd06433_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "importers" ADD CONSTRAINT "importers_initiated_by_id_3cddbd23_fk_users_id" FOREIGN KEY ("initiated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "importers" ADD CONSTRAINT "importers_project_id_1f8b43ef_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "importers" ADD CONSTRAINT "importers_token_id_c951e89f_fk_api_tokens_id" FOREIGN KEY ("token_id") REFERENCES "api_tokens" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "importers" ADD CONSTRAINT "importers_updated_by_id_3915139e_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "importers" ADD CONSTRAINT "importers_workspace_id_795b8985_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "importers_created_by_id_7dd06433" ON "importers" ("created_by_id");
CREATE INDEX "importers_initiated_by_id_3cddbd23" ON "importers" ("initiated_by_id");
CREATE INDEX "importers_project_id_1f8b43ef" ON "importers" ("project_id");
CREATE INDEX "importers_token_id_c951e89f" ON "importers" ("token_id");
CREATE INDEX "importers_updated_by_id_3915139e" ON "importers" ("updated_by_id");
CREATE INDEX "importers_workspace_id_795b8985" ON "importers" ("workspace_id");
ALTER TABLE "issue_views" ADD CONSTRAINT "issue_views_created_by_id_0d2e456b_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_views" ADD CONSTRAINT "issue_views_project_id_55ee009f_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_views" ADD CONSTRAINT "issue_views_updated_by_id_28cd9870_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_views" ADD CONSTRAINT "issue_views_workspace_id_8785e03d_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "issue_views_created_by_id_0d2e456b" ON "issue_views" ("created_by_id");
CREATE INDEX "issue_views_project_id_55ee009f" ON "issue_views" ("project_id");
CREATE INDEX "issue_views_updated_by_id_28cd9870" ON "issue_views" ("updated_by_id");
CREATE INDEX "issue_views_workspace_id_8785e03d" ON "issue_views" ("workspace_id");
ALTER TABLE "view_favorites" ADD CONSTRAINT "view_favorites_view_id_user_id_3f287788_uniq" UNIQUE ("view_id", "user_id");
ALTER TABLE "view_favorites" ADD CONSTRAINT "view_favorites_created_by_id_dc6047f5_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "view_favorites" ADD CONSTRAINT "view_favorites_project_id_241c521d_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "view_favorites" ADD CONSTRAINT "view_favorites_updated_by_id_2418b683_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "view_favorites" ADD CONSTRAINT "view_favorites_user_id_b1e94c2e_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "view_favorites" ADD CONSTRAINT "view_favorites_view_id_3111e893_fk_issue_views_id" FOREIGN KEY ("view_id") REFERENCES "issue_views" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "view_favorites" ADD CONSTRAINT "view_favorites_workspace_id_3dbdd2a2_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "view_favorites_created_by_id_dc6047f5" ON "view_favorites" ("created_by_id");
CREATE INDEX "view_favorites_project_id_241c521d" ON "view_favorites" ("project_id");
CREATE INDEX "view_favorites_updated_by_id_2418b683" ON "view_favorites" ("updated_by_id");
CREATE INDEX "view_favorites_user_id_b1e94c2e" ON "view_favorites" ("user_id");
CREATE INDEX "view_favorites_view_id_3111e893" ON "view_favorites" ("view_id");
CREATE INDEX "view_favorites_workspace_id_3dbdd2a2" ON "view_favorites" ("workspace_id");
