-- db.0024_auto_20230322_0138, recorded by apps/api-go/tools/generate_migration_sql.py. Do not edit by hand.
CREATE TABLE "pages" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "name" varchar(255) NOT NULL, "description" jsonb NOT NULL, "description_html" text NOT NULL, "description_stripped" text NULL, "access" smallint NOT NULL CHECK ("access" >= 0), "created_by_id" uuid NULL, "owned_by_id" uuid NOT NULL);
ALTER TABLE "projects" ADD COLUMN "issue_views_view" boolean DEFAULT true NOT NULL;
ALTER TABLE "projects" ALTER COLUMN "issue_views_view" DROP DEFAULT;
ALTER TABLE "projects" ALTER COLUMN "cover_image" TYPE varchar(800);
CREATE TABLE "page_blocks" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "name" varchar(255) NOT NULL, "description" jsonb NOT NULL, "description_html" text NOT NULL, "description_stripped" text NULL, "completed_at" timestamp with time zone NULL, "created_by_id" uuid NULL, "issue_id" uuid NULL, "page_id" uuid NOT NULL, "project_id" uuid NOT NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
ALTER TABLE "pages" ADD COLUMN "project_id" uuid NOT NULL CONSTRAINT "pages_project_id_272eed09_fk_projects_id" REFERENCES "projects"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "pages_project_id_272eed09_fk_projects_id" IMMEDIATE;
ALTER TABLE "pages" ADD COLUMN "updated_by_id" uuid NULL CONSTRAINT "pages_updated_by_id_6c42de3e_fk_users_id" REFERENCES "users"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "pages_updated_by_id_6c42de3e_fk_users_id" IMMEDIATE;
ALTER TABLE "pages" ADD COLUMN "workspace_id" uuid NOT NULL CONSTRAINT "pages_workspace_id_c6c51010_fk_workspaces_id" REFERENCES "workspaces"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "pages_workspace_id_c6c51010_fk_workspaces_id" IMMEDIATE;
CREATE TABLE "page_favorites" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "created_by_id" uuid NULL, "page_id" uuid NOT NULL, "project_id" uuid NOT NULL, "updated_by_id" uuid NULL, "user_id" uuid NOT NULL, "workspace_id" uuid NOT NULL);
ALTER TABLE "pages" ADD CONSTRAINT "pages_created_by_id_d109a675_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "pages" ADD CONSTRAINT "pages_owned_by_id_bf50485f_fk_users_id" FOREIGN KEY ("owned_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "pages_created_by_id_d109a675" ON "pages" ("created_by_id");
CREATE INDEX "pages_owned_by_id_bf50485f" ON "pages" ("owned_by_id");
ALTER TABLE "page_blocks" ADD CONSTRAINT "page_blocks_created_by_id_696391e1_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "page_blocks" ADD CONSTRAINT "page_blocks_issue_id_33cad86b_fk_issues_id" FOREIGN KEY ("issue_id") REFERENCES "issues" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "page_blocks" ADD CONSTRAINT "page_blocks_page_id_5f55e114_fk_pages_id" FOREIGN KEY ("page_id") REFERENCES "pages" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "page_blocks" ADD CONSTRAINT "page_blocks_project_id_068d80f7_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "page_blocks" ADD CONSTRAINT "page_blocks_updated_by_id_1a29acb7_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "page_blocks" ADD CONSTRAINT "page_blocks_workspace_id_b051825d_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "page_blocks_created_by_id_696391e1" ON "page_blocks" ("created_by_id");
CREATE INDEX "page_blocks_issue_id_33cad86b" ON "page_blocks" ("issue_id");
CREATE INDEX "page_blocks_page_id_5f55e114" ON "page_blocks" ("page_id");
CREATE INDEX "page_blocks_project_id_068d80f7" ON "page_blocks" ("project_id");
CREATE INDEX "page_blocks_updated_by_id_1a29acb7" ON "page_blocks" ("updated_by_id");
CREATE INDEX "page_blocks_workspace_id_b051825d" ON "page_blocks" ("workspace_id");
CREATE INDEX "pages_project_id_272eed09" ON "pages" ("project_id");
CREATE INDEX "pages_updated_by_id_6c42de3e" ON "pages" ("updated_by_id");
CREATE INDEX "pages_workspace_id_c6c51010" ON "pages" ("workspace_id");
ALTER TABLE "page_favorites" ADD CONSTRAINT "page_favorites_page_id_user_id_6e2c24ba_uniq" UNIQUE ("page_id", "user_id");
ALTER TABLE "page_favorites" ADD CONSTRAINT "page_favorites_created_by_id_3b672270_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "page_favorites" ADD CONSTRAINT "page_favorites_page_id_0896034b_fk_pages_id" FOREIGN KEY ("page_id") REFERENCES "pages" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "page_favorites" ADD CONSTRAINT "page_favorites_project_id_e0e3c871_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "page_favorites" ADD CONSTRAINT "page_favorites_updated_by_id_623c7ac5_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "page_favorites" ADD CONSTRAINT "page_favorites_user_id_162640a9_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "page_favorites" ADD CONSTRAINT "page_favorites_workspace_id_4b7858d9_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "page_favorites_created_by_id_3b672270" ON "page_favorites" ("created_by_id");
CREATE INDEX "page_favorites_page_id_0896034b" ON "page_favorites" ("page_id");
CREATE INDEX "page_favorites_project_id_e0e3c871" ON "page_favorites" ("project_id");
CREATE INDEX "page_favorites_updated_by_id_623c7ac5" ON "page_favorites" ("updated_by_id");
CREATE INDEX "page_favorites_user_id_162640a9" ON "page_favorites" ("user_id");
CREATE INDEX "page_favorites_workspace_id_4b7858d9" ON "page_favorites" ("workspace_id");
