-- db.0037_issue_archived_at_project_archive_in_and_more, recorded by apps/api-go/tools/generate_migration_sql.py. Do not edit by hand.
ALTER TABLE "issues" ADD COLUMN "archived_at" date NULL;
ALTER TABLE "projects" ADD COLUMN "archive_in" integer DEFAULT 0 NOT NULL;
ALTER TABLE "projects" ALTER COLUMN "archive_in" DROP DEFAULT;
ALTER TABLE "projects" ADD COLUMN "close_in" integer DEFAULT 0 NOT NULL;
ALTER TABLE "projects" ALTER COLUMN "close_in" DROP DEFAULT;
ALTER TABLE "projects" ADD COLUMN "default_state_id" uuid NULL CONSTRAINT "projects_default_state_id_f13e8b95_fk_states_id" REFERENCES "states"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "projects_default_state_id_f13e8b95_fk_states_id" IMMEDIATE;
ALTER TABLE "users" ADD COLUMN "is_tour_completed" boolean DEFAULT false NOT NULL;
ALTER TABLE "users" ALTER COLUMN "is_tour_completed" DROP DEFAULT;
ALTER TABLE "users" ADD COLUMN "onboarding_step" jsonb DEFAULT '{"profile_complete": false, "workspace_create": false, "workspace_invite": false, "workspace_join": false}'::jsonb NOT NULL;
ALTER TABLE "users" ALTER COLUMN "onboarding_step" DROP DEFAULT;
CREATE TABLE "notifications" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "data" jsonb NULL, "entity_identifier" uuid NULL, "entity_name" varchar(255) NOT NULL, "title" text NOT NULL, "message" jsonb NULL, "message_html" text NOT NULL, "message_stripped" text NULL, "sender" varchar(255) NOT NULL, "read_at" timestamp with time zone NULL, "snoozed_till" timestamp with time zone NULL, "archived_at" timestamp with time zone NULL, "created_by_id" uuid NULL, "project_id" uuid NULL, "receiver_id" uuid NOT NULL, "triggered_by_id" uuid NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
CREATE TABLE "issue_subscribers" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "created_by_id" uuid NULL, "issue_id" uuid NOT NULL, "project_id" uuid NOT NULL, "subscriber_id" uuid NOT NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
CREATE INDEX "projects_default_state_id_f13e8b95" ON "projects" ("default_state_id");
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_created_by_id_b9c3f81b_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_project_id_e4d4f192_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_receiver_id_b708b2b0_fk_users_id" FOREIGN KEY ("receiver_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_triggered_by_id_31cdec21_fk_users_id" FOREIGN KEY ("triggered_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_updated_by_id_8a651e96_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_workspace_id_b2f09ef7_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "notifications_created_by_id_b9c3f81b" ON "notifications" ("created_by_id");
CREATE INDEX "notifications_project_id_e4d4f192" ON "notifications" ("project_id");
CREATE INDEX "notifications_receiver_id_b708b2b0" ON "notifications" ("receiver_id");
CREATE INDEX "notifications_triggered_by_id_31cdec21" ON "notifications" ("triggered_by_id");
CREATE INDEX "notifications_updated_by_id_8a651e96" ON "notifications" ("updated_by_id");
CREATE INDEX "notifications_workspace_id_b2f09ef7" ON "notifications" ("workspace_id");
ALTER TABLE "issue_subscribers" ADD CONSTRAINT "issue_subscribers_issue_id_subscriber_id_5038c5f8_uniq" UNIQUE ("issue_id", "subscriber_id");
ALTER TABLE "issue_subscribers" ADD CONSTRAINT "issue_subscribers_created_by_id_b6ea0157_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_subscribers" ADD CONSTRAINT "issue_subscribers_issue_id_85cf2093_fk_issues_id" FOREIGN KEY ("issue_id") REFERENCES "issues" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_subscribers" ADD CONSTRAINT "issue_subscribers_project_id_cf48d75f_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_subscribers" ADD CONSTRAINT "issue_subscribers_subscriber_id_2d89c988_fk_users_id" FOREIGN KEY ("subscriber_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_subscribers" ADD CONSTRAINT "issue_subscribers_updated_by_id_1bfc2f55_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_subscribers" ADD CONSTRAINT "issue_subscribers_workspace_id_96afa91f_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "issue_subscribers_created_by_id_b6ea0157" ON "issue_subscribers" ("created_by_id");
CREATE INDEX "issue_subscribers_issue_id_85cf2093" ON "issue_subscribers" ("issue_id");
CREATE INDEX "issue_subscribers_project_id_cf48d75f" ON "issue_subscribers" ("project_id");
CREATE INDEX "issue_subscribers_subscriber_id_2d89c988" ON "issue_subscribers" ("subscriber_id");
CREATE INDEX "issue_subscribers_updated_by_id_1bfc2f55" ON "issue_subscribers" ("updated_by_id");
CREATE INDEX "issue_subscribers_workspace_id_96afa91f" ON "issue_subscribers" ("workspace_id");
