-- db.0052_auto_20231220_1141, recorded from the Django app this replaced.
ALTER TABLE "issue_views" RENAME COLUMN "query_data" TO "filters";
ALTER TABLE "issue_properties" RENAME COLUMN "properties" TO "display_properties";
ALTER TABLE "issue_properties" ADD COLUMN "display_filters" jsonb DEFAULT '{"group_by": null, "order_by": "-created_at", "type": null, "sub_issue": true, "show_empty_groups": true, "layout": "list", "calendar_date_range": ""}'::jsonb NOT NULL;
ALTER TABLE "issue_properties" ALTER COLUMN "display_filters" DROP DEFAULT;
ALTER TABLE "issue_properties" ADD COLUMN "filters" jsonb DEFAULT '{"priority": null, "state": null, "state_group": null, "assignees": null, "created_by": null, "labels": null, "start_date": null, "target_date": null, "subscriber": null}'::jsonb NOT NULL;
ALTER TABLE "issue_properties" ALTER COLUMN "filters" DROP DEFAULT;
ALTER TABLE "issue_views" ADD COLUMN "display_filters" jsonb DEFAULT '{"group_by": null, "order_by": "-created_at", "type": null, "sub_issue": true, "show_empty_groups": true, "layout": "list", "calendar_date_range": ""}'::jsonb NOT NULL;
ALTER TABLE "issue_views" ALTER COLUMN "display_filters" DROP DEFAULT;
ALTER TABLE "issue_views" ADD COLUMN "display_properties" jsonb DEFAULT '{"assignee": true, "attachment_count": true, "created_on": true, "due_date": true, "estimate": true, "key": true, "labels": true, "link": true, "priority": true, "start_date": true, "state": true, "sub_issue_count": true, "updated_on": true}'::jsonb NOT NULL;
ALTER TABLE "issue_views" ALTER COLUMN "display_properties" DROP DEFAULT;
ALTER TABLE "issue_views" ADD COLUMN "sort_order" double precision DEFAULT 65535.0 NOT NULL;
ALTER TABLE "issue_views" ALTER COLUMN "sort_order" DROP DEFAULT;
SET CONSTRAINTS "issue_views_project_id_55ee009f_fk_projects_id" IMMEDIATE; ALTER TABLE "issue_views" DROP CONSTRAINT "issue_views_project_id_55ee009f_fk_projects_id";
ALTER TABLE "issue_views" ALTER COLUMN "project_id" DROP NOT NULL;
ALTER TABLE "issue_views" ADD CONSTRAINT "issue_views_project_id_55ee009f_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE "workspace_user_properties" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "filters" jsonb NOT NULL, "display_filters" jsonb NOT NULL, "display_properties" jsonb NOT NULL, "created_by_id" uuid NULL, "updated_by_id" uuid NULL, "user_id" uuid NOT NULL, "workspace_id" uuid NOT NULL);
CREATE TABLE "module_user_properties" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "filters" jsonb NOT NULL, "display_filters" jsonb NOT NULL, "display_properties" jsonb NOT NULL, "created_by_id" uuid NULL, "module_id" uuid NOT NULL, "project_id" uuid NOT NULL, "updated_by_id" uuid NULL, "user_id" uuid NOT NULL, "workspace_id" uuid NOT NULL);
CREATE TABLE "cycle_user_properties" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "filters" jsonb NOT NULL, "display_filters" jsonb NOT NULL, "display_properties" jsonb NOT NULL, "created_by_id" uuid NULL, "cycle_id" uuid NOT NULL, "project_id" uuid NOT NULL, "updated_by_id" uuid NULL, "user_id" uuid NOT NULL, "workspace_id" uuid NOT NULL);
ALTER TABLE "workspace_user_properties" ADD CONSTRAINT "workspace_user_properties_workspace_id_user_id_f1a46435_uniq" UNIQUE ("workspace_id", "user_id");
ALTER TABLE "workspace_user_properties" ADD CONSTRAINT "workspace_user_properties_created_by_id_6d8d1c4e_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "workspace_user_properties" ADD CONSTRAINT "workspace_user_properties_updated_by_id_910a2cc5_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "workspace_user_properties" ADD CONSTRAINT "workspace_user_properties_user_id_b1079e07_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "workspace_user_properties" ADD CONSTRAINT "workspace_user_prope_workspace_id_1dc3e2a6_fk_workspace" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "workspace_user_properties_created_by_id_6d8d1c4e" ON "workspace_user_properties" ("created_by_id");
CREATE INDEX "workspace_user_properties_updated_by_id_910a2cc5" ON "workspace_user_properties" ("updated_by_id");
CREATE INDEX "workspace_user_properties_user_id_b1079e07" ON "workspace_user_properties" ("user_id");
CREATE INDEX "workspace_user_properties_workspace_id_1dc3e2a6" ON "workspace_user_properties" ("workspace_id");
ALTER TABLE "module_user_properties" ADD CONSTRAINT "module_user_properties_module_id_user_id_2d9cc934_uniq" UNIQUE ("module_id", "user_id");
ALTER TABLE "module_user_properties" ADD CONSTRAINT "module_user_properties_created_by_id_bdd98440_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_user_properties" ADD CONSTRAINT "module_user_properties_module_id_e95b158a_fk_modules_id" FOREIGN KEY ("module_id") REFERENCES "modules" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_user_properties" ADD CONSTRAINT "module_user_properties_project_id_3c5a4972_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_user_properties" ADD CONSTRAINT "module_user_properties_updated_by_id_b7dafc77_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_user_properties" ADD CONSTRAINT "module_user_properties_user_id_e83a1c2c_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_user_properties" ADD CONSTRAINT "module_user_properties_workspace_id_ddaf807c_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "module_user_properties_created_by_id_bdd98440" ON "module_user_properties" ("created_by_id");
CREATE INDEX "module_user_properties_module_id_e95b158a" ON "module_user_properties" ("module_id");
CREATE INDEX "module_user_properties_project_id_3c5a4972" ON "module_user_properties" ("project_id");
CREATE INDEX "module_user_properties_updated_by_id_b7dafc77" ON "module_user_properties" ("updated_by_id");
CREATE INDEX "module_user_properties_user_id_e83a1c2c" ON "module_user_properties" ("user_id");
CREATE INDEX "module_user_properties_workspace_id_ddaf807c" ON "module_user_properties" ("workspace_id");
ALTER TABLE "cycle_user_properties" ADD CONSTRAINT "cycle_user_properties_cycle_id_user_id_1b8597f8_uniq" UNIQUE ("cycle_id", "user_id");
ALTER TABLE "cycle_user_properties" ADD CONSTRAINT "cycle_user_properties_created_by_id_501f371c_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cycle_user_properties" ADD CONSTRAINT "cycle_user_properties_cycle_id_1f8bdf35_fk_cycles_id" FOREIGN KEY ("cycle_id") REFERENCES "cycles" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cycle_user_properties" ADD CONSTRAINT "cycle_user_properties_project_id_4efc0f07_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cycle_user_properties" ADD CONSTRAINT "cycle_user_properties_updated_by_id_1b5ac27b_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cycle_user_properties" ADD CONSTRAINT "cycle_user_properties_user_id_9e9ef97d_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cycle_user_properties" ADD CONSTRAINT "cycle_user_properties_workspace_id_62d65d71_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cycle_user_properties_created_by_id_501f371c" ON "cycle_user_properties" ("created_by_id");
CREATE INDEX "cycle_user_properties_cycle_id_1f8bdf35" ON "cycle_user_properties" ("cycle_id");
CREATE INDEX "cycle_user_properties_project_id_4efc0f07" ON "cycle_user_properties" ("project_id");
CREATE INDEX "cycle_user_properties_updated_by_id_1b5ac27b" ON "cycle_user_properties" ("updated_by_id");
CREATE INDEX "cycle_user_properties_user_id_9e9ef97d" ON "cycle_user_properties" ("user_id");
CREATE INDEX "cycle_user_properties_workspace_id_62d65d71" ON "cycle_user_properties" ("workspace_id");
