-- db.0068_remove_pagelabel_project_remove_pagelog_project_and_more, recorded from the Django app this replaced.
ALTER TABLE "pages" ADD COLUMN "is_global" boolean DEFAULT false NOT NULL;
ALTER TABLE "pages" ALTER COLUMN "is_global" DROP DEFAULT;
CREATE TABLE "project_pages" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "created_by_id" uuid NULL, "page_id" uuid NOT NULL, "project_id" uuid NOT NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
CREATE TABLE "team_pages" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "created_by_id" uuid NULL, "page_id" uuid NOT NULL, "team_id" uuid NOT NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
-- RUN db.0068_remove_pagelabel_project_remove_pagelog_project_and_more.migrate_pages
SET CONSTRAINTS "pages_project_id_272eed09_fk_projects_id" IMMEDIATE; ALTER TABLE "pages" DROP CONSTRAINT "pages_project_id_272eed09_fk_projects_id";
ALTER TABLE "pages" DROP COLUMN "project_id" CASCADE;
SET CONSTRAINTS "page_labels_project_id_938a63ca_fk_projects_id" IMMEDIATE; ALTER TABLE "page_labels" DROP CONSTRAINT "page_labels_project_id_938a63ca_fk_projects_id";
ALTER TABLE "page_labels" DROP COLUMN "project_id" CASCADE;
SET CONSTRAINTS "page_logs_project_id_d5117f7a_fk_projects_id" IMMEDIATE; ALTER TABLE "page_logs" DROP CONSTRAINT "page_logs_project_id_d5117f7a_fk_projects_id";
ALTER TABLE "page_logs" DROP COLUMN "project_id" CASCADE;
ALTER TABLE "project_pages" ADD CONSTRAINT "project_pages_project_id_page_id_7c702c91_uniq" UNIQUE ("project_id", "page_id");
ALTER TABLE "project_pages" ADD CONSTRAINT "project_pages_created_by_id_b9d02062_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "project_pages" ADD CONSTRAINT "project_pages_page_id_a0f54439_fk_pages_id" FOREIGN KEY ("page_id") REFERENCES "pages" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "project_pages" ADD CONSTRAINT "project_pages_project_id_376ba35a_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "project_pages" ADD CONSTRAINT "project_pages_updated_by_id_b80bf0f4_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "project_pages" ADD CONSTRAINT "project_pages_workspace_id_13ed9e73_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "project_pages_created_by_id_b9d02062" ON "project_pages" ("created_by_id");
CREATE INDEX "project_pages_page_id_a0f54439" ON "project_pages" ("page_id");
CREATE INDEX "project_pages_project_id_376ba35a" ON "project_pages" ("project_id");
CREATE INDEX "project_pages_updated_by_id_b80bf0f4" ON "project_pages" ("updated_by_id");
CREATE INDEX "project_pages_workspace_id_13ed9e73" ON "project_pages" ("workspace_id");
ALTER TABLE "team_pages" ADD CONSTRAINT "team_pages_team_id_page_id_3becadbb_uniq" UNIQUE ("team_id", "page_id");
ALTER TABLE "team_pages" ADD CONSTRAINT "team_pages_created_by_id_3714b9d0_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "team_pages" ADD CONSTRAINT "team_pages_page_id_a0020d6b_fk_pages_id" FOREIGN KEY ("page_id") REFERENCES "pages" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "team_pages" ADD CONSTRAINT "team_pages_team_id_bba5bf9e_fk_teams_id" FOREIGN KEY ("team_id") REFERENCES "teams" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "team_pages" ADD CONSTRAINT "team_pages_updated_by_id_fd082008_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "team_pages" ADD CONSTRAINT "team_pages_workspace_id_56609aa6_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "team_pages_created_by_id_3714b9d0" ON "team_pages" ("created_by_id");
CREATE INDEX "team_pages_page_id_a0020d6b" ON "team_pages" ("page_id");
CREATE INDEX "team_pages_team_id_bba5bf9e" ON "team_pages" ("team_id");
CREATE INDEX "team_pages_updated_by_id_fd082008" ON "team_pages" ("updated_by_id");
CREATE INDEX "team_pages_workspace_id_56609aa6" ON "team_pages" ("workspace_id");
