-- db.0070_apitoken_is_service_exporterhistory_filters_and_more, recorded by apps/api-go/tools/generate_migration_sql.py. Do not edit by hand.
ALTER TABLE "api_tokens" ADD COLUMN "is_service" boolean DEFAULT false NOT NULL;
ALTER TABLE "api_tokens" ALTER COLUMN "is_service" DROP DEFAULT;
ALTER TABLE "exporters" ADD COLUMN "filters" jsonb NULL;
ALTER TABLE "exporters" ADD COLUMN "name" varchar(255) NULL;
ALTER TABLE "exporters" ADD COLUMN "type" varchar(50) DEFAULT 'issue_exports' NOT NULL;
ALTER TABLE "exporters" ALTER COLUMN "type" DROP DEFAULT;
ALTER TABLE "projects" ADD COLUMN "is_time_tracking_enabled" boolean DEFAULT false NOT NULL;
ALTER TABLE "projects" ALTER COLUMN "is_time_tracking_enabled" DROP DEFAULT;
ALTER TABLE "projects" ADD COLUMN "start_date" timestamp with time zone NULL;
ALTER TABLE "projects" ADD COLUMN "target_date" timestamp with time zone NULL;
CREATE TABLE "page_versions" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "last_saved_at" timestamp with time zone NOT NULL, "description_binary" bytea NULL, "description_html" text NOT NULL, "description_stripped" text NULL, "description_json" jsonb NOT NULL, "created_by_id" uuid NULL, "owned_by_id" uuid NOT NULL, "page_id" uuid NOT NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
CREATE TABLE "issue_types" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "name" varchar(255) NOT NULL, "description" text NOT NULL, "logo_props" jsonb NOT NULL, "sort_order" double precision NOT NULL, "is_default" boolean NOT NULL, "weight" integer NOT NULL CHECK ("weight" >= 0), "created_by_id" uuid NULL, "project_id" uuid NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
ALTER TABLE "issues" ADD COLUMN "type_id" uuid NULL CONSTRAINT "issues_type_id_a4710b19_fk_issue_types_id" REFERENCES "issue_types"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "issues_type_id_a4710b19_fk_issue_types_id" IMMEDIATE;
ALTER TABLE "page_versions" ADD CONSTRAINT "page_versions_created_by_id_d660b13b_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "page_versions" ADD CONSTRAINT "page_versions_owned_by_id_6d9143db_fk_users_id" FOREIGN KEY ("owned_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "page_versions" ADD CONSTRAINT "page_versions_page_id_c46471da_fk_pages_id" FOREIGN KEY ("page_id") REFERENCES "pages" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "page_versions" ADD CONSTRAINT "page_versions_updated_by_id_72d5e579_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "page_versions" ADD CONSTRAINT "page_versions_workspace_id_8330a200_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "page_versions_created_by_id_d660b13b" ON "page_versions" ("created_by_id");
CREATE INDEX "page_versions_owned_by_id_6d9143db" ON "page_versions" ("owned_by_id");
CREATE INDEX "page_versions_page_id_c46471da" ON "page_versions" ("page_id");
CREATE INDEX "page_versions_updated_by_id_72d5e579" ON "page_versions" ("updated_by_id");
CREATE INDEX "page_versions_workspace_id_8330a200" ON "page_versions" ("workspace_id");
ALTER TABLE "issue_types" ADD CONSTRAINT "issue_types_project_id_name_6da59c5e_uniq" UNIQUE ("project_id", "name");
ALTER TABLE "issue_types" ADD CONSTRAINT "issue_types_created_by_id_48764f53_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_types" ADD CONSTRAINT "issue_types_project_id_a040d097_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_types" ADD CONSTRAINT "issue_types_updated_by_id_4919203b_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_types" ADD CONSTRAINT "issue_types_workspace_id_591c6f3b_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "issue_types_created_by_id_48764f53" ON "issue_types" ("created_by_id");
CREATE INDEX "issue_types_project_id_a040d097" ON "issue_types" ("project_id");
CREATE INDEX "issue_types_updated_by_id_4919203b" ON "issue_types" ("updated_by_id");
CREATE INDEX "issue_types_workspace_id_591c6f3b" ON "issue_types" ("workspace_id");
CREATE INDEX "issues_type_id_a4710b19" ON "issues" ("type_id");
