-- db.0073_alter_commentreaction_unique_together_and_more, recorded by apps/api-go/tools/generate_migration_sql.py. Do not edit by hand.
ALTER TABLE "comment_reactions" DROP CONSTRAINT "comment_reactions_comment_id_actor_id_reaction_523d21ad_uniq";
ALTER TABLE "cycle_user_properties" DROP CONSTRAINT "cycle_user_properties_cycle_id_user_id_1b8597f8_uniq";
ALTER TABLE "dashboard_widgets" DROP CONSTRAINT "dashboard_widgets_widget_id_dashboard_id_149a0e15_uniq";
ALTER TABLE "deploy_boards" DROP CONSTRAINT "deploy_boards_entity_name_entity_identifier_e58644ac_uniq";
ALTER TABLE "estimates" DROP CONSTRAINT "estimates_name_project_id_2b42c12c_uniq";
ALTER TABLE "inboxes" DROP CONSTRAINT "inboxes_name_project_id_daf38984_uniq";
ALTER TABLE "issue_assignees" DROP CONSTRAINT "issue_assignee_issue_id_assignee_id_4ee260b4_uniq";
ALTER TABLE "issue_mentions" DROP CONSTRAINT "issue_mentions_issue_id_mention_id_ce91a005_uniq";
ALTER TABLE "issue_reactions" DROP CONSTRAINT "issue_reactions_issue_id_actor_id_reaction_4751a642_uniq";
ALTER TABLE "issue_relations" DROP CONSTRAINT "issue_relations_issue_id_related_issue_id_640e8062_uniq";
ALTER TABLE "issue_subscribers" DROP CONSTRAINT "issue_subscribers_issue_id_subscriber_id_5038c5f8_uniq";
ALTER TABLE "issue_types" DROP CONSTRAINT "issue_types_project_id_name_6da59c5e_uniq";
ALTER TABLE "issue_user_properties" DROP CONSTRAINT "issue_property_user_id_project_id_fe52668f_uniq";
ALTER TABLE "issue_votes" DROP CONSTRAINT "issue_votes_issue_id_actor_id_086954ee_uniq";
ALTER TABLE "labels" DROP CONSTRAINT "labels_name_project_id_d8b1b810_uniq";
ALTER TABLE "modules" DROP CONSTRAINT "module_name_project_id_c730d437_uniq";
ALTER TABLE "module_issues" DROP CONSTRAINT "module_issues_issue_id_module_id_d0042711_uniq";
ALTER TABLE "module_members" DROP CONSTRAINT "module_member_module_id_member_id_1421c56c_uniq";
ALTER TABLE "module_user_properties" DROP CONSTRAINT "module_user_properties_module_id_user_id_2d9cc934_uniq";
ALTER TABLE "projects" DROP CONSTRAINT "project_name_workspace_id_e858a38f_uniq";
ALTER TABLE "projects" DROP CONSTRAINT "project_identifier_workspace_id_35e9a4bf_uniq";
ALTER TABLE "project_identifiers" DROP CONSTRAINT "project_identifier_name_workspace_id_4b7404cb_uniq";
ALTER TABLE "project_members" DROP CONSTRAINT "project_member_project_id_member_id_9489e47c_uniq";
ALTER TABLE "project_pages" DROP CONSTRAINT "project_pages_project_id_page_id_7c702c91_uniq";
ALTER TABLE "project_public_members" DROP CONSTRAINT "project_public_members_project_id_member_id_51cd09a4_uniq";
ALTER TABLE "states" DROP CONSTRAINT "state_name_project_id_89897f31_uniq";
ALTER TABLE "teams" DROP CONSTRAINT "team_name_workspace_id_9538db2e_uniq";
ALTER TABLE "team_members" DROP CONSTRAINT "team_member_team_id_member_id_d0325b97_uniq";
ALTER TABLE "team_pages" DROP CONSTRAINT "team_pages_team_id_page_id_3becadbb_uniq";
ALTER TABLE "user_favorites" DROP CONSTRAINT "user_favorites_entity_type_user_id_enti_1fe6e83d_uniq";
ALTER TABLE "workspace_members" DROP CONSTRAINT "workspace_member_workspace_id_member_id_2b61b0e8_uniq";
ALTER TABLE "workspace_member_invites" DROP CONSTRAINT "workspace_member_invites_email_workspace_id_9d830009_uniq";
ALTER TABLE "workspace_themes" DROP CONSTRAINT "workspace_themes_workspace_id_name_500d4836_uniq";
ALTER TABLE "workspace_user_properties" DROP CONSTRAINT "workspace_user_properties_workspace_id_user_id_f1a46435_uniq";
ALTER TABLE "analytic_views" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "api_activity_logs" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "api_tokens" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "comment_reactions" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "cycles" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "cycle_favorites" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "cycle_issues" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "cycle_user_properties" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "dashboards" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "dashboard_widgets" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "deploy_boards" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "email_notification_logs" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "estimates" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "estimate_points" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "exporters" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "file_assets" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "github_comment_syncs" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "github_issue_syncs" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "github_repositories" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "github_repository_syncs" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "global_views" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "importers" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "inboxes" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "inbox_issues" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "integrations" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "issues" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "issue_activities" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "issue_assignees" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "issue_attachments" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "issue_blockers" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "issue_comments" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "issue_labels" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "issue_links" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "issue_mentions" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "issue_reactions" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "issue_relations" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "issue_sequences" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "issue_subscribers" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "issue_types" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "issue_user_properties" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "issue_views" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "view_favorites" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "issue_votes" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "labels" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "modules" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "module_favorites" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "module_issues" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "module_links" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "module_members" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "module_user_properties" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "notifications" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "pages" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "page_blocks" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "page_favorites" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "page_labels" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "page_logs" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "page_versions" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "projects" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "project_deploy_boards" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "project_favorites" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "project_identifiers" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "project_members" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "project_member_invites" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "project_pages" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "project_public_members" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "slack_project_syncs" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "social_login_connections" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "states" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "teams" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "team_members" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "team_pages" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "user_favorites" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "user_notification_preferences" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "user_recent_visits" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "webhooks" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "webhook_logs" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "workspaces" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "workspace_integrations" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "workspace_members" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "workspace_member_invites" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "workspace_themes" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "workspace_user_properties" ADD COLUMN "deleted_at" timestamp with time zone NULL;
ALTER TABLE "comment_reactions" ADD CONSTRAINT "comment_reactions_comment_id_actor_id_reac_24dc2de6_uniq" UNIQUE ("comment_id", "actor_id", "reaction", "deleted_at");
ALTER TABLE "cycle_user_properties" ADD CONSTRAINT "cycle_user_properties_cycle_id_user_id_deleted_at_fbe00cf4_uniq" UNIQUE ("cycle_id", "user_id", "deleted_at");
ALTER TABLE "dashboard_widgets" ADD CONSTRAINT "dashboard_widgets_widget_id_dashboard_id_d_190c068f_uniq" UNIQUE ("widget_id", "dashboard_id", "deleted_at");
ALTER TABLE "deploy_boards" ADD CONSTRAINT "deploy_boards_entity_name_entity_ident_800ce160_uniq" UNIQUE ("entity_name", "entity_identifier", "deleted_at");
ALTER TABLE "estimates" ADD CONSTRAINT "estimates_name_project_id_deleted_at_41d66639_uniq" UNIQUE ("name", "project_id", "deleted_at");
ALTER TABLE "inboxes" ADD CONSTRAINT "inboxes_name_project_id_deleted_at_95043f72_uniq" UNIQUE ("name", "project_id", "deleted_at");
ALTER TABLE "issue_assignees" ADD CONSTRAINT "issue_assignees_issue_id_assignee_id_deleted_at_b2623a0e_uniq" UNIQUE ("issue_id", "assignee_id", "deleted_at");
ALTER TABLE "issue_mentions" ADD CONSTRAINT "issue_mentions_issue_id_mention_id_deleted_at_f6ecd6ed_uniq" UNIQUE ("issue_id", "mention_id", "deleted_at");
ALTER TABLE "issue_reactions" ADD CONSTRAINT "issue_reactions_issue_id_actor_id_reacti_7da73ced_uniq" UNIQUE ("issue_id", "actor_id", "reaction", "deleted_at");
ALTER TABLE "issue_relations" ADD CONSTRAINT "issue_relations_issue_id_related_issue_i_cc724584_uniq" UNIQUE ("issue_id", "related_issue_id", "deleted_at");
ALTER TABLE "issue_subscribers" ADD CONSTRAINT "issue_subscribers_issue_id_subscriber_id_d_587dec1a_uniq" UNIQUE ("issue_id", "subscriber_id", "deleted_at");
ALTER TABLE "issue_types" ADD CONSTRAINT "issue_types_project_id_name_deleted_at_caa8a8cc_uniq" UNIQUE ("project_id", "name", "deleted_at");
ALTER TABLE "issue_user_properties" ADD CONSTRAINT "issue_user_properties_user_id_project_id_delet_2217dce5_uniq" UNIQUE ("user_id", "project_id", "deleted_at");
ALTER TABLE "issue_votes" ADD CONSTRAINT "issue_votes_issue_id_actor_id_deleted_at_886f34e8_uniq" UNIQUE ("issue_id", "actor_id", "deleted_at");
ALTER TABLE "labels" ADD CONSTRAINT "labels_name_project_id_deleted_at_eebc553a_uniq" UNIQUE ("name", "project_id", "deleted_at");
ALTER TABLE "modules" ADD CONSTRAINT "modules_name_project_id_deleted_at_328e2346_uniq" UNIQUE ("name", "project_id", "deleted_at");
ALTER TABLE "module_issues" ADD CONSTRAINT "module_issues_issue_id_module_id_deleted_at_f944f7c9_uniq" UNIQUE ("issue_id", "module_id", "deleted_at");
ALTER TABLE "module_members" ADD CONSTRAINT "module_members_module_id_member_id_deleted_at_bb7a6f00_uniq" UNIQUE ("module_id", "member_id", "deleted_at");
ALTER TABLE "module_user_properties" ADD CONSTRAINT "module_user_properties_module_id_user_id_delete_3269582d_uniq" UNIQUE ("module_id", "user_id", "deleted_at");
ALTER TABLE "projects" ADD CONSTRAINT "projects_name_workspace_id_deleted_at_c7aa56f7_uniq" UNIQUE ("name", "workspace_id", "deleted_at");
ALTER TABLE "projects" ADD CONSTRAINT "projects_identifier_workspace_id_deleted_at_7d2fa8c1_uniq" UNIQUE ("identifier", "workspace_id", "deleted_at");
ALTER TABLE "project_identifiers" ADD CONSTRAINT "project_identifiers_name_workspace_id_deleted_at_d332e701_uniq" UNIQUE ("name", "workspace_id", "deleted_at");
ALTER TABLE "project_members" ADD CONSTRAINT "project_members_project_id_member_id_deleted_at_0299122d_uniq" UNIQUE ("project_id", "member_id", "deleted_at");
ALTER TABLE "project_pages" ADD CONSTRAINT "project_pages_project_id_page_id_deleted_at_7c80a40c_uniq" UNIQUE ("project_id", "page_id", "deleted_at");
ALTER TABLE "project_public_members" ADD CONSTRAINT "project_public_members_project_id_member_id_del_9acd89b5_uniq" UNIQUE ("project_id", "member_id", "deleted_at");
ALTER TABLE "states" ADD CONSTRAINT "states_name_project_id_deleted_at_02f90488_uniq" UNIQUE ("name", "project_id", "deleted_at");
ALTER TABLE "teams" ADD CONSTRAINT "teams_name_workspace_id_deleted_at_4b131aa2_uniq" UNIQUE ("name", "workspace_id", "deleted_at");
ALTER TABLE "team_members" ADD CONSTRAINT "team_members_team_id_member_id_deleted_at_268e9be6_uniq" UNIQUE ("team_id", "member_id", "deleted_at");
ALTER TABLE "team_pages" ADD CONSTRAINT "team_pages_team_id_page_id_deleted_at_5f089157_uniq" UNIQUE ("team_id", "page_id", "deleted_at");
ALTER TABLE "user_favorites" ADD CONSTRAINT "user_favorites_entity_type_user_id_enti_22b103ff_uniq" UNIQUE ("entity_type", "user_id", "entity_identifier", "deleted_at");
ALTER TABLE "workspace_members" ADD CONSTRAINT "workspace_members_workspace_id_member_id_d_d7bfa872_uniq" UNIQUE ("workspace_id", "member_id", "deleted_at");
ALTER TABLE "workspace_member_invites" ADD CONSTRAINT "workspace_member_invites_email_workspace_id_delet_2f03573e_uniq" UNIQUE ("email", "workspace_id", "deleted_at");
ALTER TABLE "workspace_themes" ADD CONSTRAINT "workspace_themes_workspace_id_name_deleted_at_b536ffd3_uniq" UNIQUE ("workspace_id", "name", "deleted_at");
ALTER TABLE "workspace_user_properties" ADD CONSTRAINT "workspace_user_propertie_workspace_id_user_id_del_a7cf15bc_uniq" UNIQUE ("workspace_id", "user_id", "deleted_at");
CREATE UNIQUE INDEX "comment_reaction_unique_comment_actor_reaction_when_deleted_at_null" ON "comment_reactions" ("comment_id", "actor_id", "reaction") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "cycle_user_properties_unique_cycle_user_when_deleted_at_null" ON "cycle_user_properties" ("cycle_id", "user_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "dashboard_widget_unique_widget_dashboard_when_deleted_at_null" ON "dashboard_widgets" ("widget_id", "dashboard_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "deploy_board_unique_entity_name_entity_identifier_when_deleted_at_null" ON "deploy_boards" ("entity_name", "entity_identifier") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "estimate_unique_name_project_when_deleted_at_null" ON "estimates" ("name", "project_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "inbox_unique_name_project_when_deleted_at_null" ON "inboxes" ("name", "project_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "issue_assignee_unique_issue_assignee_when_deleted_at_null" ON "issue_assignees" ("issue_id", "assignee_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "issue_mention_unique_issue_mention_when_deleted_at_null" ON "issue_mentions" ("issue_id", "mention_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "issue_reaction_unique_issue_actor_reaction_when_deleted_at_null" ON "issue_reactions" ("issue_id", "actor_id", "reaction") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "issue_relation_unique_issue_related_issue_when_deleted_at_null" ON "issue_relations" ("issue_id", "related_issue_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "issue_subscriber_unique_issue_subscriber_when_deleted_at_null" ON "issue_subscribers" ("issue_id", "subscriber_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "issue_type_unique_name_project_when_deleted_at_null" ON "issue_types" ("name", "project_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "issue_user_property_unique_user_project_when_deleted_at_null" ON "issue_user_properties" ("user_id", "project_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "issue_vote_unique_issue_actor_when_deleted_at_null" ON "issue_votes" ("issue_id", "actor_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "label_unique_name_project_when_deleted_at_null" ON "labels" ("name", "project_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "module_unique_name_project_when_deleted_at_null" ON "modules" ("name", "project_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "module_issue_unique_issue_module_when_deleted_at_null" ON "module_issues" ("issue_id", "module_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "module_member_unique_module_member_when_deleted_at_null" ON "module_members" ("module_id", "member_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "module_user_properties_unique_module_user_when_deleted_at_null" ON "module_user_properties" ("module_id", "user_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "project_unique_identifier_workspace_when_deleted_at_null" ON "projects" ("identifier", "workspace_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "project_unique_name_workspace_when_deleted_at_null" ON "projects" ("name", "workspace_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "unique_name_workspace_when_deleted_at_null" ON "project_identifiers" ("name", "workspace_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "project_member_unique_project_member_when_deleted_at_null" ON "project_members" ("project_id", "member_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "project_page_unique_project_page_when_deleted_at_null" ON "project_pages" ("project_id", "page_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "project_public_member_unique_project_member_when_deleted_at_null" ON "project_public_members" ("project_id", "member_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "state_unique_name_project_when_deleted_at_null" ON "states" ("name", "project_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "team_unique_name_workspace_when_deleted_at_null" ON "teams" ("name", "workspace_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "team_member_unique_team_member_when_deleted_at_null" ON "team_members" ("team_id", "member_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "team_page_unique_team_page_when_deleted_at_null" ON "team_pages" ("team_id", "page_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "user_favorite_unique_entity_type_entity_identifier_user_when_deleted_at_null" ON "user_favorites" ("entity_type", "entity_identifier", "user_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "workspace_member_unique_workspace_member_when_deleted_at_null" ON "workspace_members" ("workspace_id", "member_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "workspace_member_invite_unique_email_workspace_when_deleted_at_null" ON "workspace_member_invites" ("email", "workspace_id") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "workspace_theme_unique_workspace_name_when_deleted_at_null" ON "workspace_themes" ("workspace_id", "name") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "workspace_user_properties_unique_workspace_user_when_deleted_at_null" ON "workspace_user_properties" ("workspace_id", "user_id") WHERE "deleted_at" IS NULL;
