-- db.0086_issueversion_alter_teampage_unique_together_and_more, recorded by apps/api-go/tools/generate_migration_sql.py. Do not edit by hand.
CREATE TABLE "issue_versions" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "deleted_at" timestamp with time zone NULL, "id" uuid NOT NULL PRIMARY KEY, "parent" uuid NULL, "state" uuid NULL, "estimate_point" uuid NULL, "name" varchar(255) NOT NULL, "description" jsonb NOT NULL, "description_html" text NOT NULL, "description_stripped" text NULL, "description_binary" bytea NULL, "priority" varchar(30) NOT NULL, "start_date" date NULL, "target_date" date NULL, "sequence_id" integer NOT NULL, "sort_order" double precision NOT NULL, "completed_at" timestamp with time zone NULL, "archived_at" date NULL, "is_draft" boolean NOT NULL, "external_source" varchar(255) NULL, "external_id" varchar(255) NULL, "type" uuid NULL, "last_saved_at" timestamp with time zone NOT NULL, "owned_by" uuid NOT NULL, "assignees" uuid[] NOT NULL, "labels" uuid[] NOT NULL, "cycle" uuid NULL, "modules" uuid[] NOT NULL, "properties" jsonb NOT NULL, "meta" jsonb NOT NULL, "created_by_id" uuid NULL, "issue_id" uuid NOT NULL, "project_id" uuid NOT NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
ALTER TABLE "team_pages" DROP CONSTRAINT "team_pages_team_id_page_id_deleted_at_5f089157_uniq";
SET CONSTRAINTS "team_pages_created_by_id_3714b9d0_fk_users_id" IMMEDIATE; ALTER TABLE "team_pages" DROP CONSTRAINT "team_pages_created_by_id_3714b9d0_fk_users_id";
ALTER TABLE "team_pages" DROP COLUMN "created_by_id" CASCADE;
SET CONSTRAINTS "team_pages_page_id_a0020d6b_fk_pages_id" IMMEDIATE; ALTER TABLE "team_pages" DROP CONSTRAINT "team_pages_page_id_a0020d6b_fk_pages_id";
ALTER TABLE "team_pages" DROP COLUMN "page_id" CASCADE;
SET CONSTRAINTS "team_pages_team_id_bba5bf9e_fk_teams_id" IMMEDIATE; ALTER TABLE "team_pages" DROP CONSTRAINT "team_pages_team_id_bba5bf9e_fk_teams_id";
ALTER TABLE "team_pages" DROP COLUMN "team_id" CASCADE;
SET CONSTRAINTS "team_pages_updated_by_id_fd082008_fk_users_id" IMMEDIATE; ALTER TABLE "team_pages" DROP CONSTRAINT "team_pages_updated_by_id_fd082008_fk_users_id";
ALTER TABLE "team_pages" DROP COLUMN "updated_by_id" CASCADE;
SET CONSTRAINTS "team_pages_workspace_id_56609aa6_fk_workspaces_id" IMMEDIATE; ALTER TABLE "team_pages" DROP CONSTRAINT "team_pages_workspace_id_56609aa6_fk_workspaces_id";
ALTER TABLE "team_pages" DROP COLUMN "workspace_id" CASCADE;
ALTER TABLE "file_assets" ADD COLUMN "entity_identifier" varchar(255) NULL;
ALTER TABLE "webhooks" ADD COLUMN "is_internal" boolean DEFAULT false NOT NULL;
ALTER TABLE "webhooks" ALTER COLUMN "is_internal" DROP DEFAULT;
ALTER TABLE "webhooks" ALTER COLUMN "url" TYPE varchar(1024);
DROP TABLE "team_members" CASCADE;
DROP TABLE "team_pages" CASCADE;
ALTER TABLE "issue_versions" ADD CONSTRAINT "issue_versions_created_by_id_a782830a_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_versions" ADD CONSTRAINT "issue_versions_issue_id_25cf001c_fk_issues_id" FOREIGN KEY ("issue_id") REFERENCES "issues" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_versions" ADD CONSTRAINT "issue_versions_project_id_a069ad03_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_versions" ADD CONSTRAINT "issue_versions_updated_by_id_dcae6dd2_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_versions" ADD CONSTRAINT "issue_versions_workspace_id_b8c48b7c_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "issue_versions_created_by_id_a782830a" ON "issue_versions" ("created_by_id");
CREATE INDEX "issue_versions_issue_id_25cf001c" ON "issue_versions" ("issue_id");
CREATE INDEX "issue_versions_project_id_a069ad03" ON "issue_versions" ("project_id");
CREATE INDEX "issue_versions_updated_by_id_dcae6dd2" ON "issue_versions" ("updated_by_id");
CREATE INDEX "issue_versions_workspace_id_b8c48b7c" ON "issue_versions" ("workspace_id");
