-- db.0087_remove_issueversion_description_and_more, recorded from the Django app this replaced.
ALTER TABLE "issue_versions" DROP COLUMN "description" CASCADE;
ALTER TABLE "issue_versions" DROP COLUMN "description_binary" CASCADE;
ALTER TABLE "issue_versions" DROP COLUMN "description_html" CASCADE;
ALTER TABLE "issue_versions" DROP COLUMN "description_stripped" CASCADE;
ALTER TABLE "issue_versions" ADD COLUMN "activity_id" uuid NULL CONSTRAINT "issue_versions_activity_id_b1872ffc_fk_issue_activities_id" REFERENCES "issue_activities"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "issue_versions_activity_id_b1872ffc_fk_issue_activities_id" IMMEDIATE;
ALTER TABLE "profiles" ADD COLUMN "is_mobile_onboarded" boolean DEFAULT false NOT NULL;
ALTER TABLE "profiles" ALTER COLUMN "is_mobile_onboarded" DROP DEFAULT;
ALTER TABLE "profiles" ADD COLUMN "mobile_onboarding_step" jsonb DEFAULT '{"profile_complete": false, "workspace_create": false, "workspace_join": false}'::jsonb NOT NULL;
ALTER TABLE "profiles" ALTER COLUMN "mobile_onboarding_step" DROP DEFAULT;
ALTER TABLE "profiles" ADD COLUMN "mobile_timezone_auto_set" boolean DEFAULT false NOT NULL;
ALTER TABLE "profiles" ALTER COLUMN "mobile_timezone_auto_set" DROP DEFAULT;
ALTER TABLE "profiles" ADD COLUMN "language" varchar(255) DEFAULT 'en' NOT NULL;
ALTER TABLE "profiles" ALTER COLUMN "language" DROP DEFAULT;
ALTER TABLE "issue_versions" RENAME COLUMN "owned_by" TO "owned_by_id";
CREATE INDEX "issue_versions_owned_by_id_7586378d" ON "issue_versions" ("owned_by_id");
ALTER TABLE "issue_versions" ADD CONSTRAINT "issue_versions_owned_by_id_7586378d_fk_users_id" FOREIGN KEY ("owned_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE "stickies" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "deleted_at" timestamp with time zone NULL, "id" uuid NOT NULL PRIMARY KEY, "name" text NOT NULL, "description" jsonb NOT NULL, "description_html" text NOT NULL, "description_stripped" text NULL, "description_binary" bytea NULL, "logo_props" jsonb NOT NULL, "color" varchar(255) NULL, "background_color" varchar(255) NULL, "created_by_id" uuid NULL, "owner_id" uuid NOT NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
CREATE TABLE "issue_description_versions" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "deleted_at" timestamp with time zone NULL, "id" uuid NOT NULL PRIMARY KEY, "description_binary" bytea NULL, "description_html" text NOT NULL, "description_stripped" text NULL, "description_json" jsonb NOT NULL, "last_saved_at" timestamp with time zone NOT NULL, "created_by_id" uuid NULL, "issue_id" uuid NOT NULL, "owned_by_id" uuid NOT NULL, "project_id" uuid NOT NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
CREATE INDEX "issue_versions_activity_id_b1872ffc" ON "issue_versions" ("activity_id");
ALTER TABLE "stickies" ADD CONSTRAINT "stickies_created_by_id_f72e05c4_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "stickies" ADD CONSTRAINT "stickies_owner_id_6ee3be2b_fk_users_id" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "stickies" ADD CONSTRAINT "stickies_updated_by_id_d660f1fb_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "stickies" ADD CONSTRAINT "stickies_workspace_id_0094496a_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "stickies_created_by_id_f72e05c4" ON "stickies" ("created_by_id");
CREATE INDEX "stickies_owner_id_6ee3be2b" ON "stickies" ("owner_id");
CREATE INDEX "stickies_updated_by_id_d660f1fb" ON "stickies" ("updated_by_id");
CREATE INDEX "stickies_workspace_id_0094496a" ON "stickies" ("workspace_id");
ALTER TABLE "issue_description_versions" ADD CONSTRAINT "issue_description_versions_created_by_id_3f7e62a1_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_description_versions" ADD CONSTRAINT "issue_description_versions_issue_id_c8baa13e_fk_issues_id" FOREIGN KEY ("issue_id") REFERENCES "issues" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_description_versions" ADD CONSTRAINT "issue_description_versions_owned_by_id_0effe4d0_fk_users_id" FOREIGN KEY ("owned_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_description_versions" ADD CONSTRAINT "issue_description_versions_project_id_536b23ef_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_description_versions" ADD CONSTRAINT "issue_description_versions_updated_by_id_6530365d_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_description_versions" ADD CONSTRAINT "issue_description_ve_workspace_id_88e930f9_fk_workspace" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "issue_description_versions_created_by_id_3f7e62a1" ON "issue_description_versions" ("created_by_id");
CREATE INDEX "issue_description_versions_issue_id_c8baa13e" ON "issue_description_versions" ("issue_id");
CREATE INDEX "issue_description_versions_owned_by_id_0effe4d0" ON "issue_description_versions" ("owned_by_id");
CREATE INDEX "issue_description_versions_project_id_536b23ef" ON "issue_description_versions" ("project_id");
CREATE INDEX "issue_description_versions_updated_by_id_6530365d" ON "issue_description_versions" ("updated_by_id");
CREATE INDEX "issue_description_versions_workspace_id_88e930f9" ON "issue_description_versions" ("workspace_id");
