// Package pdfdoc draws a page's document as a PDF.
//
// It is a port of the exporter the live service ran, and the one piece of that service whose output cannot be reproduced exactly. The original lays a page out with react-pdf, which is a flexbox engine; this lays it out by flowing blocks down the page. The same fonts are embedded and every measurement, colour and spacing is read out of the original's own stylesheet, so a page looks like the same page — but the two are not the same bytes and a long document may break across pages differently.
package pdfdoc

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

// stylesJSON is the exporter's stylesheet, generated by tools/generate_pdf_styles.mjs. Every number in a rendered page comes from it.
//
//go:embed styles.json
var stylesJSON []byte

// Style is one entry of the stylesheet, with the properties this renderer reads. A property the stylesheet does not set is left at its zero, which is what the renderer treats as absent.
type Style struct {
	FontSize   float64 `json:"fontSize"`
	FontWeight any     `json:"fontWeight"`
	FontStyle  string  `json:"fontStyle"`
	FontFamily string  `json:"fontFamily"`
	LineHeight float64 `json:"lineHeight"`
	Color      string  `json:"color"`

	Padding           float64 `json:"padding"`
	PaddingLeft       float64 `json:"paddingLeft"`
	PaddingRight      float64 `json:"paddingRight"`
	PaddingHorizontal float64 `json:"paddingHorizontal"`
	MarginTop         float64 `json:"marginTop"`
	MarginBottom      float64 `json:"marginBottom"`
	MarginLeft        float64 `json:"marginLeft"`
	MarginVertical    float64 `json:"marginVertical"`

	BackgroundColor   string  `json:"backgroundColor"`
	BorderWidth       float64 `json:"borderWidth"`
	BorderColor       string  `json:"borderColor"`
	BorderLeftWidth   float64 `json:"borderLeftWidth"`
	BorderLeftColor   string  `json:"borderLeftColor"`
	BorderBottomWidth float64 `json:"borderBottomWidth"`
	BorderBottomColor string  `json:"borderBottomColor"`
	BorderRightWidth  float64 `json:"borderRightWidth"`
	BorderRightColor  string  `json:"borderRightColor"`
	BorderRadius      float64 `json:"borderRadius"`

	Width          float64 `json:"width"`
	Height         float64 `json:"height"`
	Gap            float64 `json:"gap"`
	TextDecoration string  `json:"textDecoration"`
}

// Weight is the style's font weight as a number, zero when it sets none. The stylesheet spells it both ways — as a number and as the word bold — so both are read.
func (s Style) Weight() int {
	switch value := s.FontWeight.(type) {
	case float64:
		return int(value)
	case string:
		if value == "bold" {
			return 700
		}
		if parsed, err := strconv.Atoi(value); err == nil {
			return parsed
		}
	}
	return 0
}

// stylesheet is the whole of it, plus the colours the renderer reaches for by name.
type stylesheet struct {
	Styles map[string]Style             `json:"styles"`
	Colors map[string]map[string]string `json:"colors"`
}

var styles = mustLoadStyles()

func mustLoadStyles() stylesheet {
	var sheet stylesheet
	if err := json.Unmarshal(stylesJSON, &sheet); err != nil {
		panic(fmt.Sprintf("pdfdoc: styles.json is not readable: %v", err))
	}
	if _, ok := sheet.Styles["page"]; !ok {
		panic("pdfdoc: styles.json has no page style")
	}
	return sheet
}

// style returns one entry by name, and an empty one when the stylesheet has no such entry — which is how a node type the stylesheet says nothing about ends up drawn with the page's own settings.
func style(name string) Style { return styles.Styles[name] }

// rgb turns a colour written the way the stylesheet writes it into the three components a PDF wants. Anything it cannot read is black, which is the page's own colour.
func rgb(colour string) (int, int, int) {
	value := strings.TrimPrefix(strings.TrimSpace(colour), "#")
	switch len(value) {
	case 3:
		value = string([]byte{value[0], value[0], value[1], value[1], value[2], value[2]})
	case 6:
	case 8:
		// An alpha channel is dropped: a PDF fill has no transparency here, and the colours that carry one are backgrounds where the difference is slight.
		value = value[:6]
	default:
		return 0, 0, 0
	}
	parsed, err := strconv.ParseUint(value, 16, 32)
	if err != nil {
		return 0, 0, 0
	}
	return int(parsed >> 16 & 0xff), int(parsed >> 8 & 0xff), int(parsed & 0xff)
}
