-- django_celery_beat.0002_auto_20161118_0346, recorded from the Django app this replaced.
CREATE TABLE "django_celery_beat_solarschedule" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "event" varchar(24) NOT NULL, "latitude" numeric(9, 6) NOT NULL, "longitude" numeric(9, 6) NOT NULL);
ALTER TABLE "django_celery_beat_periodictask" ADD COLUMN "solar_id" integer NULL CONSTRAINT "django_celery_beat_p_solar_id_a87ce72c_fk_django_ce" REFERENCES "django_celery_beat_solarschedule"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "django_celery_beat_p_solar_id_a87ce72c_fk_django_ce" IMMEDIATE;
CREATE INDEX "django_celery_beat_periodictask_solar_id_a87ce72c" ON "django_celery_beat_periodictask" ("solar_id");
