-- The ledger table, which Django's MigrationRecorder creates before the first migration runs. Recorded from the Django app this replaced, which is gone; it does not change.
CREATE TABLE "django_migrations" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" timestamp with time zone NOT NULL);
