-- The ledger table, which Django's MigrationRecorder creates before the first migration runs. Recorded by apps/api-go/tools/generate_migration_sql.py. Do not edit by hand.
CREATE TABLE "django_migrations" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" timestamp with time zone NOT NULL);
