services:
  web:
    image: ${PLANE_IMAGE_OWNER:-local}/plane-frontend:${APP_RELEASE:-latest}
    build:
      context: ../../
      dockerfile: apps/web/Dockerfile.web

  space:
    image: ${PLANE_IMAGE_OWNER:-local}/plane-space:${APP_RELEASE:-latest}
    build:
      context: ../../
      dockerfile: apps/space/Dockerfile.space

  admin:
    image: ${PLANE_IMAGE_OWNER:-local}/plane-admin:${APP_RELEASE:-latest}
    build:
      context: ../../
      dockerfile: apps/admin/Dockerfile.admin

  live:
    image: ${PLANE_IMAGE_OWNER:-local}/plane-live:${APP_RELEASE:-latest}
    build:
      context: ../../apps/api-go
      dockerfile: Dockerfile.live

  api:
    image: ${PLANE_IMAGE_OWNER:-local}/plane-backend:${APP_RELEASE:-latest}
    build:
      context: ../../apps/api-go
      dockerfile: Dockerfile

  proxy:
    image: ${PLANE_IMAGE_OWNER:-local}/plane-proxy:${APP_RELEASE:-latest}
    build:
      context: ../../apps/proxy
      dockerfile: Dockerfile.ce
