-- The rows post_migrate leaves behind, recorded from the Django app this replaced, which is gone; it does not change.
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (1, 'contenttypes', 'contenttype');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (2, 'auth', 'permission');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (3, 'auth', 'group');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (4, 'db', 'user');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (5, 'db', 'cycle');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (6, 'db', 'issue');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (7, 'db', 'project');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (8, 'db', 'team');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (9, 'db', 'workspace');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (10, 'db', 'workspacememberinvite');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (11, 'db', 'view');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (12, 'db', 'timelineissue');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (13, 'db', 'teammember');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (14, 'db', 'state');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (15, 'db', 'socialloginconnection');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (16, 'db', 'shortcut');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (17, 'db', 'projectmemberinvite');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (18, 'db', 'projectidentifier');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (19, 'db', 'label');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (20, 'db', 'issuesequence');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (21, 'db', 'projectuserproperty');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (22, 'db', 'issuelabel');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (23, 'db', 'issuecomment');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (24, 'db', 'issueblocker');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (25, 'db', 'issueassignee');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (26, 'db', 'issueactivity');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (27, 'db', 'fileasset');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (28, 'db', 'cycleissue');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (29, 'db', 'workspacemember');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (30, 'db', 'projectmember');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (31, 'db', 'module');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (32, 'db', 'modulemember');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (33, 'db', 'moduleissue');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (34, 'db', 'modulelink');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (35, 'db', 'apitoken');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (36, 'db', 'integration');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (37, 'db', 'githubrepositorysync');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (38, 'db', 'githubissuesync');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (39, 'db', 'issuelink');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (40, 'db', 'workspaceintegration');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (41, 'db', 'githubcommentsync');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (42, 'db', 'githubrepository');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (43, 'db', 'projectfavorite');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (44, 'db', 'modulefavorite');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (45, 'db', 'cyclefavorite');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (46, 'db', 'importer');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (47, 'db', 'issueview');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (48, 'db', 'issueviewfavorite');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (49, 'db', 'page');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (50, 'db', 'pageblock');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (51, 'db', 'pagefavorite');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (52, 'db', 'pagelabel');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (53, 'db', 'estimate');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (54, 'db', 'issueattachment');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (55, 'db', 'estimatepoint');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (56, 'db', 'workspacetheme');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (57, 'db', 'slackprojectsync');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (58, 'db', 'analyticview');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (59, 'db', 'intake');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (60, 'db', 'intakeissue');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (61, 'db', 'notification');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (62, 'db', 'issuesubscriber');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (63, 'db', 'issuereaction');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (64, 'db', 'commentreaction');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (65, 'db', 'exporterhistory');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (66, 'db', 'projectdeployboard');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (67, 'db', 'issuevote');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (68, 'db', 'projectpublicmember');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (69, 'db', 'issuerelation');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (70, 'db', 'globalview');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (71, 'db', 'issuemention');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (72, 'db', 'webhook');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (73, 'db', 'webhooklog');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (74, 'db', 'apiactivitylog');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (75, 'db', 'pagelog');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (76, 'db', 'workspaceuserproperties');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (77, 'db', 'moduleuserproperties');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (78, 'db', 'cycleuserproperties');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (79, 'db', 'deprecatedwidget');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (80, 'db', 'deprecateddashboard');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (81, 'db', 'deprecateddashboardwidget');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (82, 'db', 'usernotificationpreference');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (83, 'db', 'emailnotificationlog');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (84, 'db', 'session');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (85, 'db', 'profile');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (86, 'db', 'account');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (87, 'db', 'userfavorite');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (88, 'db', 'deployboard');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (89, 'db', 'projectpage');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (90, 'db', 'teampage');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (91, 'db', 'pageversion');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (92, 'db', 'issuetype');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (93, 'db', 'userrecentvisit');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (94, 'db', 'projectissuetype');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (95, 'db', 'draftissue');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (96, 'db', 'draftissuemodule');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (97, 'db', 'draftissuelabel');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (98, 'db', 'draftissuecycle');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (99, 'db', 'draftissueassignee');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (100, 'db', 'device');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (101, 'db', 'devicesession');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (102, 'db', 'issueversion');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (103, 'db', 'sticky');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (104, 'db', 'issuedescriptionversion');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (105, 'db', 'workspaceuserlink');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (106, 'db', 'workspacehomepreference');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (107, 'db', 'workspaceuserpreference');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (108, 'db', 'description');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (109, 'db', 'descriptionversion');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (110, 'db', 'projectwebhook');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (111, 'django_celery_beat', 'intervalschedule');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (112, 'django_celery_beat', 'periodictask');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (113, 'django_celery_beat', 'crontabschedule');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (114, 'django_celery_beat', 'periodictasks');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (115, 'django_celery_beat', 'solarschedule');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (116, 'django_celery_beat', 'clockedschedule');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (117, 'license', 'instanceadmin');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (118, 'license', 'instance');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (119, 'license', 'instanceconfiguration');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (120, 'license', 'changelog');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (121, 'sessions', 'session');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (1, 'Can add permission', 2, 'add_permission');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (2, 'Can change permission', 2, 'change_permission');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (3, 'Can delete permission', 2, 'delete_permission');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (4, 'Can view permission', 2, 'view_permission');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (5, 'Can add group', 3, 'add_group');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (6, 'Can change group', 3, 'change_group');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (7, 'Can delete group', 3, 'delete_group');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (8, 'Can view group', 3, 'view_group');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (9, 'Can add content type', 1, 'add_contenttype');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (10, 'Can change content type', 1, 'change_contenttype');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (11, 'Can delete content type', 1, 'delete_contenttype');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (12, 'Can view content type', 1, 'view_contenttype');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (13, 'Can add User', 4, 'add_user');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (14, 'Can change User', 4, 'change_user');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (15, 'Can delete User', 4, 'delete_user');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (16, 'Can view User', 4, 'view_user');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (17, 'Can add Cycle', 5, 'add_cycle');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (18, 'Can change Cycle', 5, 'change_cycle');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (19, 'Can delete Cycle', 5, 'delete_cycle');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (20, 'Can view Cycle', 5, 'view_cycle');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (21, 'Can add Issue', 6, 'add_issue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (22, 'Can change Issue', 6, 'change_issue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (23, 'Can delete Issue', 6, 'delete_issue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (24, 'Can view Issue', 6, 'view_issue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (25, 'Can add Project', 7, 'add_project');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (26, 'Can change Project', 7, 'change_project');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (27, 'Can delete Project', 7, 'delete_project');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (28, 'Can view Project', 7, 'view_project');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (29, 'Can add Team', 8, 'add_team');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (30, 'Can change Team', 8, 'change_team');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (31, 'Can delete Team', 8, 'delete_team');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (32, 'Can view Team', 8, 'view_team');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (33, 'Can add Workspace', 9, 'add_workspace');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (34, 'Can change Workspace', 9, 'change_workspace');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (35, 'Can delete Workspace', 9, 'delete_workspace');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (36, 'Can view Workspace', 9, 'view_workspace');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (37, 'Can add Workspace Member Invite', 10, 'add_workspacememberinvite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (38, 'Can change Workspace Member Invite', 10, 'change_workspacememberinvite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (39, 'Can delete Workspace Member Invite', 10, 'delete_workspacememberinvite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (40, 'Can view Workspace Member Invite', 10, 'view_workspacememberinvite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (41, 'Can add View', 11, 'add_view');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (42, 'Can change View', 11, 'change_view');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (43, 'Can delete View', 11, 'delete_view');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (44, 'Can view View', 11, 'view_view');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (45, 'Can add Timeline Issue', 12, 'add_timelineissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (46, 'Can change Timeline Issue', 12, 'change_timelineissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (47, 'Can delete Timeline Issue', 12, 'delete_timelineissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (48, 'Can view Timeline Issue', 12, 'view_timelineissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (49, 'Can add Team Member', 13, 'add_teammember');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (50, 'Can change Team Member', 13, 'change_teammember');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (51, 'Can delete Team Member', 13, 'delete_teammember');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (52, 'Can view Team Member', 13, 'view_teammember');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (53, 'Can add State', 14, 'add_state');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (54, 'Can change State', 14, 'change_state');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (55, 'Can delete State', 14, 'delete_state');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (56, 'Can view State', 14, 'view_state');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (57, 'Can add Social Login Connection', 15, 'add_socialloginconnection');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (58, 'Can change Social Login Connection', 15, 'change_socialloginconnection');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (59, 'Can delete Social Login Connection', 15, 'delete_socialloginconnection');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (60, 'Can view Social Login Connection', 15, 'view_socialloginconnection');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (61, 'Can add Shortcut', 16, 'add_shortcut');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (62, 'Can change Shortcut', 16, 'change_shortcut');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (63, 'Can delete Shortcut', 16, 'delete_shortcut');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (64, 'Can view Shortcut', 16, 'view_shortcut');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (65, 'Can add Project Member Invite', 17, 'add_projectmemberinvite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (66, 'Can change Project Member Invite', 17, 'change_projectmemberinvite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (67, 'Can delete Project Member Invite', 17, 'delete_projectmemberinvite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (68, 'Can view Project Member Invite', 17, 'view_projectmemberinvite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (69, 'Can add Project Identifier', 18, 'add_projectidentifier');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (70, 'Can change Project Identifier', 18, 'change_projectidentifier');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (71, 'Can delete Project Identifier', 18, 'delete_projectidentifier');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (72, 'Can view Project Identifier', 18, 'view_projectidentifier');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (73, 'Can add Label', 19, 'add_label');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (74, 'Can change Label', 19, 'change_label');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (75, 'Can delete Label', 19, 'delete_label');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (76, 'Can view Label', 19, 'view_label');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (77, 'Can add Issue Sequence', 20, 'add_issuesequence');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (78, 'Can change Issue Sequence', 20, 'change_issuesequence');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (79, 'Can delete Issue Sequence', 20, 'delete_issuesequence');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (80, 'Can view Issue Sequence', 20, 'view_issuesequence');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (81, 'Can add Issue Property', 21, 'add_issueproperty');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (82, 'Can change Issue Property', 21, 'change_issueproperty');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (83, 'Can delete Issue Property', 21, 'delete_issueproperty');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (84, 'Can view Issue Property', 21, 'view_issueproperty');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (85, 'Can add Issue Label', 22, 'add_issuelabel');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (86, 'Can change Issue Label', 22, 'change_issuelabel');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (87, 'Can delete Issue Label', 22, 'delete_issuelabel');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (88, 'Can view Issue Label', 22, 'view_issuelabel');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (89, 'Can add Issue Comment', 23, 'add_issuecomment');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (90, 'Can change Issue Comment', 23, 'change_issuecomment');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (91, 'Can delete Issue Comment', 23, 'delete_issuecomment');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (92, 'Can view Issue Comment', 23, 'view_issuecomment');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (93, 'Can add Issue Blocker', 24, 'add_issueblocker');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (94, 'Can change Issue Blocker', 24, 'change_issueblocker');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (95, 'Can delete Issue Blocker', 24, 'delete_issueblocker');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (96, 'Can view Issue Blocker', 24, 'view_issueblocker');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (97, 'Can add Issue Assignee', 25, 'add_issueassignee');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (98, 'Can change Issue Assignee', 25, 'change_issueassignee');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (99, 'Can delete Issue Assignee', 25, 'delete_issueassignee');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (100, 'Can view Issue Assignee', 25, 'view_issueassignee');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (101, 'Can add Issue Activity', 26, 'add_issueactivity');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (102, 'Can change Issue Activity', 26, 'change_issueactivity');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (103, 'Can delete Issue Activity', 26, 'delete_issueactivity');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (104, 'Can view Issue Activity', 26, 'view_issueactivity');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (105, 'Can add File Asset', 27, 'add_fileasset');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (106, 'Can change File Asset', 27, 'change_fileasset');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (107, 'Can delete File Asset', 27, 'delete_fileasset');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (108, 'Can view File Asset', 27, 'view_fileasset');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (109, 'Can add Cycle Issue', 28, 'add_cycleissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (110, 'Can change Cycle Issue', 28, 'change_cycleissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (111, 'Can delete Cycle Issue', 28, 'delete_cycleissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (112, 'Can view Cycle Issue', 28, 'view_cycleissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (113, 'Can add Workspace Member', 29, 'add_workspacemember');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (114, 'Can change Workspace Member', 29, 'change_workspacemember');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (115, 'Can delete Workspace Member', 29, 'delete_workspacemember');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (116, 'Can view Workspace Member', 29, 'view_workspacemember');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (117, 'Can add Project Member', 30, 'add_projectmember');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (118, 'Can change Project Member', 30, 'change_projectmember');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (119, 'Can delete Project Member', 30, 'delete_projectmember');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (120, 'Can view Project Member', 30, 'view_projectmember');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (121, 'Can add Module', 31, 'add_module');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (122, 'Can change Module', 31, 'change_module');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (123, 'Can delete Module', 31, 'delete_module');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (124, 'Can view Module', 31, 'view_module');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (125, 'Can add Module Member', 32, 'add_modulemember');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (126, 'Can change Module Member', 32, 'change_modulemember');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (127, 'Can delete Module Member', 32, 'delete_modulemember');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (128, 'Can view Module Member', 32, 'view_modulemember');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (129, 'Can add Module Issue', 33, 'add_moduleissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (130, 'Can change Module Issue', 33, 'change_moduleissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (131, 'Can delete Module Issue', 33, 'delete_moduleissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (132, 'Can view Module Issue', 33, 'view_moduleissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (133, 'Can add Module Link', 34, 'add_modulelink');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (134, 'Can change Module Link', 34, 'change_modulelink');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (135, 'Can delete Module Link', 34, 'delete_modulelink');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (136, 'Can view Module Link', 34, 'view_modulelink');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (137, 'Can add API Token', 35, 'add_apitoken');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (138, 'Can change API Token', 35, 'change_apitoken');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (139, 'Can delete API Token', 35, 'delete_apitoken');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (140, 'Can view API Token', 35, 'view_apitoken');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (141, 'Can add Integration', 36, 'add_integration');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (142, 'Can change Integration', 36, 'change_integration');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (143, 'Can delete Integration', 36, 'delete_integration');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (144, 'Can view Integration', 36, 'view_integration');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (145, 'Can add Github Repository Sync', 37, 'add_githubrepositorysync');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (146, 'Can change Github Repository Sync', 37, 'change_githubrepositorysync');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (147, 'Can delete Github Repository Sync', 37, 'delete_githubrepositorysync');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (148, 'Can view Github Repository Sync', 37, 'view_githubrepositorysync');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (149, 'Can add Github Issue Sync', 38, 'add_githubissuesync');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (150, 'Can change Github Issue Sync', 38, 'change_githubissuesync');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (151, 'Can delete Github Issue Sync', 38, 'delete_githubissuesync');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (152, 'Can view Github Issue Sync', 38, 'view_githubissuesync');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (153, 'Can add Issue Link', 39, 'add_issuelink');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (154, 'Can change Issue Link', 39, 'change_issuelink');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (155, 'Can delete Issue Link', 39, 'delete_issuelink');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (156, 'Can view Issue Link', 39, 'view_issuelink');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (157, 'Can add Workspace Integration', 40, 'add_workspaceintegration');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (158, 'Can change Workspace Integration', 40, 'change_workspaceintegration');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (159, 'Can delete Workspace Integration', 40, 'delete_workspaceintegration');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (160, 'Can view Workspace Integration', 40, 'view_workspaceintegration');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (161, 'Can add Github Comment Sync', 41, 'add_githubcommentsync');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (162, 'Can change Github Comment Sync', 41, 'change_githubcommentsync');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (163, 'Can delete Github Comment Sync', 41, 'delete_githubcommentsync');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (164, 'Can view Github Comment Sync', 41, 'view_githubcommentsync');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (165, 'Can add Repository', 42, 'add_githubrepository');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (166, 'Can change Repository', 42, 'change_githubrepository');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (167, 'Can delete Repository', 42, 'delete_githubrepository');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (168, 'Can view Repository', 42, 'view_githubrepository');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (169, 'Can add Project Favorite', 43, 'add_projectfavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (170, 'Can change Project Favorite', 43, 'change_projectfavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (171, 'Can delete Project Favorite', 43, 'delete_projectfavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (172, 'Can view Project Favorite', 43, 'view_projectfavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (173, 'Can add Module Favorite', 44, 'add_modulefavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (174, 'Can change Module Favorite', 44, 'change_modulefavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (175, 'Can delete Module Favorite', 44, 'delete_modulefavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (176, 'Can view Module Favorite', 44, 'view_modulefavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (177, 'Can add Cycle Favorite', 45, 'add_cyclefavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (178, 'Can change Cycle Favorite', 45, 'change_cyclefavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (179, 'Can delete Cycle Favorite', 45, 'delete_cyclefavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (180, 'Can view Cycle Favorite', 45, 'view_cyclefavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (181, 'Can add Importer', 46, 'add_importer');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (182, 'Can change Importer', 46, 'change_importer');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (183, 'Can delete Importer', 46, 'delete_importer');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (184, 'Can view Importer', 46, 'view_importer');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (185, 'Can add Issue View', 47, 'add_issueview');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (186, 'Can change Issue View', 47, 'change_issueview');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (187, 'Can delete Issue View', 47, 'delete_issueview');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (188, 'Can view Issue View', 47, 'view_issueview');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (189, 'Can add View Favorite', 48, 'add_issueviewfavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (190, 'Can change View Favorite', 48, 'change_issueviewfavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (191, 'Can delete View Favorite', 48, 'delete_issueviewfavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (192, 'Can view View Favorite', 48, 'view_issueviewfavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (193, 'Can add Page', 49, 'add_page');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (194, 'Can change Page', 49, 'change_page');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (195, 'Can delete Page', 49, 'delete_page');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (196, 'Can view Page', 49, 'view_page');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (197, 'Can add Page Block', 50, 'add_pageblock');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (198, 'Can change Page Block', 50, 'change_pageblock');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (199, 'Can delete Page Block', 50, 'delete_pageblock');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (200, 'Can view Page Block', 50, 'view_pageblock');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (201, 'Can add Page Favorite', 51, 'add_pagefavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (202, 'Can change Page Favorite', 51, 'change_pagefavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (203, 'Can delete Page Favorite', 51, 'delete_pagefavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (204, 'Can view Page Favorite', 51, 'view_pagefavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (205, 'Can add Page Label', 52, 'add_pagelabel');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (206, 'Can change Page Label', 52, 'change_pagelabel');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (207, 'Can delete Page Label', 52, 'delete_pagelabel');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (208, 'Can view Page Label', 52, 'view_pagelabel');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (209, 'Can add Estimate', 53, 'add_estimate');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (210, 'Can change Estimate', 53, 'change_estimate');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (211, 'Can delete Estimate', 53, 'delete_estimate');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (212, 'Can view Estimate', 53, 'view_estimate');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (213, 'Can add Issue Attachment', 54, 'add_issueattachment');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (214, 'Can change Issue Attachment', 54, 'change_issueattachment');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (215, 'Can delete Issue Attachment', 54, 'delete_issueattachment');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (216, 'Can view Issue Attachment', 54, 'view_issueattachment');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (217, 'Can add Estimate Point', 55, 'add_estimatepoint');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (218, 'Can change Estimate Point', 55, 'change_estimatepoint');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (219, 'Can delete Estimate Point', 55, 'delete_estimatepoint');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (220, 'Can view Estimate Point', 55, 'view_estimatepoint');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (221, 'Can add Workspace Theme', 56, 'add_workspacetheme');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (222, 'Can change Workspace Theme', 56, 'change_workspacetheme');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (223, 'Can delete Workspace Theme', 56, 'delete_workspacetheme');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (224, 'Can view Workspace Theme', 56, 'view_workspacetheme');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (225, 'Can add Slack Project Sync', 57, 'add_slackprojectsync');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (226, 'Can change Slack Project Sync', 57, 'change_slackprojectsync');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (227, 'Can delete Slack Project Sync', 57, 'delete_slackprojectsync');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (228, 'Can view Slack Project Sync', 57, 'view_slackprojectsync');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (229, 'Can add Analytic', 58, 'add_analyticview');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (230, 'Can change Analytic', 58, 'change_analyticview');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (231, 'Can delete Analytic', 58, 'delete_analyticview');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (232, 'Can view Analytic', 58, 'view_analyticview');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (233, 'Can add Inbox', 59, 'add_inbox');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (234, 'Can change Inbox', 59, 'change_inbox');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (235, 'Can delete Inbox', 59, 'delete_inbox');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (236, 'Can view Inbox', 59, 'view_inbox');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (237, 'Can add InboxIssue', 60, 'add_inboxissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (238, 'Can change InboxIssue', 60, 'change_inboxissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (239, 'Can delete InboxIssue', 60, 'delete_inboxissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (240, 'Can view InboxIssue', 60, 'view_inboxissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (241, 'Can add Notification', 61, 'add_notification');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (242, 'Can change Notification', 61, 'change_notification');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (243, 'Can delete Notification', 61, 'delete_notification');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (244, 'Can view Notification', 61, 'view_notification');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (245, 'Can add Issue Subscriber', 62, 'add_issuesubscriber');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (246, 'Can change Issue Subscriber', 62, 'change_issuesubscriber');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (247, 'Can delete Issue Subscriber', 62, 'delete_issuesubscriber');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (248, 'Can view Issue Subscriber', 62, 'view_issuesubscriber');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (249, 'Can add Issue Reaction', 63, 'add_issuereaction');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (250, 'Can change Issue Reaction', 63, 'change_issuereaction');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (251, 'Can delete Issue Reaction', 63, 'delete_issuereaction');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (252, 'Can view Issue Reaction', 63, 'view_issuereaction');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (253, 'Can add Comment Reaction', 64, 'add_commentreaction');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (254, 'Can change Comment Reaction', 64, 'change_commentreaction');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (255, 'Can delete Comment Reaction', 64, 'delete_commentreaction');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (256, 'Can view Comment Reaction', 64, 'view_commentreaction');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (257, 'Can add Exporter', 65, 'add_exporterhistory');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (258, 'Can change Exporter', 65, 'change_exporterhistory');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (259, 'Can delete Exporter', 65, 'delete_exporterhistory');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (260, 'Can view Exporter', 65, 'view_exporterhistory');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (261, 'Can add Project Deploy Board', 66, 'add_projectdeployboard');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (262, 'Can change Project Deploy Board', 66, 'change_projectdeployboard');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (263, 'Can delete Project Deploy Board', 66, 'delete_projectdeployboard');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (264, 'Can view Project Deploy Board', 66, 'view_projectdeployboard');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (265, 'Can add Issue Vote', 67, 'add_issuevote');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (266, 'Can change Issue Vote', 67, 'change_issuevote');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (267, 'Can delete Issue Vote', 67, 'delete_issuevote');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (268, 'Can view Issue Vote', 67, 'view_issuevote');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (269, 'Can add Project Public Member', 68, 'add_projectpublicmember');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (270, 'Can change Project Public Member', 68, 'change_projectpublicmember');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (271, 'Can delete Project Public Member', 68, 'delete_projectpublicmember');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (272, 'Can view Project Public Member', 68, 'view_projectpublicmember');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (273, 'Can add Issue Relation', 69, 'add_issuerelation');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (274, 'Can change Issue Relation', 69, 'change_issuerelation');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (275, 'Can delete Issue Relation', 69, 'delete_issuerelation');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (276, 'Can view Issue Relation', 69, 'view_issuerelation');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (277, 'Can add Global View', 70, 'add_globalview');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (278, 'Can change Global View', 70, 'change_globalview');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (279, 'Can delete Global View', 70, 'delete_globalview');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (280, 'Can view Global View', 70, 'view_globalview');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (281, 'Can add Issue Mention', 71, 'add_issuemention');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (282, 'Can change Issue Mention', 71, 'change_issuemention');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (283, 'Can delete Issue Mention', 71, 'delete_issuemention');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (284, 'Can view Issue Mention', 71, 'view_issuemention');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (285, 'Can add Webhook', 72, 'add_webhook');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (286, 'Can change Webhook', 72, 'change_webhook');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (287, 'Can delete Webhook', 72, 'delete_webhook');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (288, 'Can view Webhook', 72, 'view_webhook');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (289, 'Can add Webhook Log', 73, 'add_webhooklog');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (290, 'Can change Webhook Log', 73, 'change_webhooklog');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (291, 'Can delete Webhook Log', 73, 'delete_webhooklog');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (292, 'Can view Webhook Log', 73, 'view_webhooklog');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (293, 'Can add API Activity Log', 74, 'add_apiactivitylog');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (294, 'Can change API Activity Log', 74, 'change_apiactivitylog');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (295, 'Can delete API Activity Log', 74, 'delete_apiactivitylog');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (296, 'Can view API Activity Log', 74, 'view_apiactivitylog');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (297, 'Can add Page Log', 75, 'add_pagelog');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (298, 'Can change Page Log', 75, 'change_pagelog');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (299, 'Can delete Page Log', 75, 'delete_pagelog');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (300, 'Can view Page Log', 75, 'view_pagelog');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (301, 'Can add Workspace User Property', 76, 'add_workspaceuserproperties');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (302, 'Can change Workspace User Property', 76, 'change_workspaceuserproperties');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (303, 'Can delete Workspace User Property', 76, 'delete_workspaceuserproperties');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (304, 'Can view Workspace User Property', 76, 'view_workspaceuserproperties');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (305, 'Can add Module User Property', 77, 'add_moduleuserproperties');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (306, 'Can change Module User Property', 77, 'change_moduleuserproperties');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (307, 'Can delete Module User Property', 77, 'delete_moduleuserproperties');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (308, 'Can view Module User Property', 77, 'view_moduleuserproperties');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (309, 'Can add Cycle User Property', 78, 'add_cycleuserproperties');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (310, 'Can change Cycle User Property', 78, 'change_cycleuserproperties');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (311, 'Can delete Cycle User Property', 78, 'delete_cycleuserproperties');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (312, 'Can view Cycle User Property', 78, 'view_cycleuserproperties');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (313, 'Can add Widget', 79, 'add_widget');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (314, 'Can change Widget', 79, 'change_widget');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (315, 'Can delete Widget', 79, 'delete_widget');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (316, 'Can view Widget', 79, 'view_widget');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (317, 'Can add Dashboard', 80, 'add_dashboard');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (318, 'Can change Dashboard', 80, 'change_dashboard');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (319, 'Can delete Dashboard', 80, 'delete_dashboard');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (320, 'Can view Dashboard', 80, 'view_dashboard');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (321, 'Can add Dashboard Widget', 81, 'add_dashboardwidget');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (322, 'Can change Dashboard Widget', 81, 'change_dashboardwidget');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (323, 'Can delete Dashboard Widget', 81, 'delete_dashboardwidget');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (324, 'Can view Dashboard Widget', 81, 'view_dashboardwidget');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (325, 'Can add UserNotificationPreference', 82, 'add_usernotificationpreference');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (326, 'Can change UserNotificationPreference', 82, 'change_usernotificationpreference');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (327, 'Can delete UserNotificationPreference', 82, 'delete_usernotificationpreference');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (328, 'Can view UserNotificationPreference', 82, 'view_usernotificationpreference');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (329, 'Can add Email Notification Log', 83, 'add_emailnotificationlog');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (330, 'Can change Email Notification Log', 83, 'change_emailnotificationlog');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (331, 'Can delete Email Notification Log', 83, 'delete_emailnotificationlog');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (332, 'Can view Email Notification Log', 83, 'view_emailnotificationlog');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (333, 'Can add session', 84, 'add_session');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (334, 'Can change session', 84, 'change_session');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (335, 'Can delete session', 84, 'delete_session');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (336, 'Can view session', 84, 'view_session');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (337, 'Can add Profile', 85, 'add_profile');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (338, 'Can change Profile', 85, 'change_profile');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (339, 'Can delete Profile', 85, 'delete_profile');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (340, 'Can view Profile', 85, 'view_profile');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (341, 'Can add Account', 86, 'add_account');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (342, 'Can change Account', 86, 'change_account');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (343, 'Can delete Account', 86, 'delete_account');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (344, 'Can view Account', 86, 'view_account');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (345, 'Can add User Favorite', 87, 'add_userfavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (346, 'Can change User Favorite', 87, 'change_userfavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (347, 'Can delete User Favorite', 87, 'delete_userfavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (348, 'Can view User Favorite', 87, 'view_userfavorite');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (349, 'Can add Deploy Board', 88, 'add_deployboard');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (350, 'Can change Deploy Board', 88, 'change_deployboard');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (351, 'Can delete Deploy Board', 88, 'delete_deployboard');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (352, 'Can view Deploy Board', 88, 'view_deployboard');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (353, 'Can add Project Page', 89, 'add_projectpage');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (354, 'Can change Project Page', 89, 'change_projectpage');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (355, 'Can delete Project Page', 89, 'delete_projectpage');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (356, 'Can view Project Page', 89, 'view_projectpage');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (357, 'Can add Team Page', 90, 'add_teampage');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (358, 'Can change Team Page', 90, 'change_teampage');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (359, 'Can delete Team Page', 90, 'delete_teampage');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (360, 'Can view Team Page', 90, 'view_teampage');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (361, 'Can add Page Version', 91, 'add_pageversion');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (362, 'Can change Page Version', 91, 'change_pageversion');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (363, 'Can delete Page Version', 91, 'delete_pageversion');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (364, 'Can view Page Version', 91, 'view_pageversion');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (365, 'Can add Issue Type', 92, 'add_issuetype');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (366, 'Can change Issue Type', 92, 'change_issuetype');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (367, 'Can delete Issue Type', 92, 'delete_issuetype');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (368, 'Can view Issue Type', 92, 'view_issuetype');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (369, 'Can add Issue User Property', 21, 'add_issueuserproperty');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (370, 'Can change Issue User Property', 21, 'change_issueuserproperty');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (371, 'Can delete Issue User Property', 21, 'delete_issueuserproperty');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (372, 'Can view Issue User Property', 21, 'view_issueuserproperty');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (373, 'Can add User Recent Visit', 93, 'add_userrecentvisit');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (374, 'Can change User Recent Visit', 93, 'change_userrecentvisit');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (375, 'Can delete User Recent Visit', 93, 'delete_userrecentvisit');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (376, 'Can view User Recent Visit', 93, 'view_userrecentvisit');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (377, 'Can add Project Issue Type', 94, 'add_projectissuetype');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (378, 'Can change Project Issue Type', 94, 'change_projectissuetype');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (379, 'Can delete Project Issue Type', 94, 'delete_projectissuetype');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (380, 'Can view Project Issue Type', 94, 'view_projectissuetype');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (381, 'Can add DraftIssue', 95, 'add_draftissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (382, 'Can change DraftIssue', 95, 'change_draftissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (383, 'Can delete DraftIssue', 95, 'delete_draftissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (384, 'Can view DraftIssue', 95, 'view_draftissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (385, 'Can add Draft Issue Module', 96, 'add_draftissuemodule');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (386, 'Can change Draft Issue Module', 96, 'change_draftissuemodule');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (387, 'Can delete Draft Issue Module', 96, 'delete_draftissuemodule');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (388, 'Can view Draft Issue Module', 96, 'view_draftissuemodule');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (389, 'Can add Draft Issue Label', 97, 'add_draftissuelabel');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (390, 'Can change Draft Issue Label', 97, 'change_draftissuelabel');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (391, 'Can delete Draft Issue Label', 97, 'delete_draftissuelabel');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (392, 'Can view Draft Issue Label', 97, 'view_draftissuelabel');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (393, 'Can add Draft Issue Cycle', 98, 'add_draftissuecycle');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (394, 'Can change Draft Issue Cycle', 98, 'change_draftissuecycle');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (395, 'Can delete Draft Issue Cycle', 98, 'delete_draftissuecycle');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (396, 'Can view Draft Issue Cycle', 98, 'view_draftissuecycle');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (397, 'Can add Draft Issue Assignee', 99, 'add_draftissueassignee');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (398, 'Can change Draft Issue Assignee', 99, 'change_draftissueassignee');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (399, 'Can delete Draft Issue Assignee', 99, 'delete_draftissueassignee');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (400, 'Can view Draft Issue Assignee', 99, 'view_draftissueassignee');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (401, 'Can add Device', 100, 'add_device');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (402, 'Can change Device', 100, 'change_device');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (403, 'Can delete Device', 100, 'delete_device');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (404, 'Can view Device', 100, 'view_device');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (405, 'Can add Device Session', 101, 'add_devicesession');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (406, 'Can change Device Session', 101, 'change_devicesession');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (407, 'Can delete Device Session', 101, 'delete_devicesession');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (408, 'Can view Device Session', 101, 'view_devicesession');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (409, 'Can add Intake', 59, 'add_intake');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (410, 'Can change Intake', 59, 'change_intake');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (411, 'Can delete Intake', 59, 'delete_intake');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (412, 'Can view Intake', 59, 'view_intake');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (413, 'Can add IntakeIssue', 60, 'add_intakeissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (414, 'Can change IntakeIssue', 60, 'change_intakeissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (415, 'Can delete IntakeIssue', 60, 'delete_intakeissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (416, 'Can view IntakeIssue', 60, 'view_intakeissue');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (417, 'Can add Issue Version', 102, 'add_issueversion');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (418, 'Can change Issue Version', 102, 'change_issueversion');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (419, 'Can delete Issue Version', 102, 'delete_issueversion');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (420, 'Can view Issue Version', 102, 'view_issueversion');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (421, 'Can add Sticky', 103, 'add_sticky');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (422, 'Can change Sticky', 103, 'change_sticky');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (423, 'Can delete Sticky', 103, 'delete_sticky');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (424, 'Can view Sticky', 103, 'view_sticky');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (425, 'Can add Issue Description Version', 104, 'add_issuedescriptionversion');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (426, 'Can change Issue Description Version', 104, 'change_issuedescriptionversion');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (427, 'Can delete Issue Description Version', 104, 'delete_issuedescriptionversion');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (428, 'Can view Issue Description Version', 104, 'view_issuedescriptionversion');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (429, 'Can add Workspace User Link', 105, 'add_workspaceuserlink');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (430, 'Can change Workspace User Link', 105, 'change_workspaceuserlink');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (431, 'Can delete Workspace User Link', 105, 'delete_workspaceuserlink');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (432, 'Can view Workspace User Link', 105, 'view_workspaceuserlink');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (433, 'Can add Workspace Home Preference', 106, 'add_workspacehomepreference');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (434, 'Can change Workspace Home Preference', 106, 'change_workspacehomepreference');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (435, 'Can delete Workspace Home Preference', 106, 'delete_workspacehomepreference');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (436, 'Can view Workspace Home Preference', 106, 'view_workspacehomepreference');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (437, 'Can add DeprecatedDashboard', 80, 'add_deprecateddashboard');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (438, 'Can change DeprecatedDashboard', 80, 'change_deprecateddashboard');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (439, 'Can delete DeprecatedDashboard', 80, 'delete_deprecateddashboard');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (440, 'Can view DeprecatedDashboard', 80, 'view_deprecateddashboard');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (441, 'Can add Deprecated Dashboard Widget', 81, 'add_deprecateddashboardwidget');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (442, 'Can change Deprecated Dashboard Widget', 81, 'change_deprecateddashboardwidget');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (443, 'Can delete Deprecated Dashboard Widget', 81, 'delete_deprecateddashboardwidget');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (444, 'Can view Deprecated Dashboard Widget', 81, 'view_deprecateddashboardwidget');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (445, 'Can add DeprecatedWidget', 79, 'add_deprecatedwidget');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (446, 'Can change DeprecatedWidget', 79, 'change_deprecatedwidget');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (447, 'Can delete DeprecatedWidget', 79, 'delete_deprecatedwidget');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (448, 'Can view DeprecatedWidget', 79, 'view_deprecatedwidget');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (449, 'Can add Workspace User Preference', 107, 'add_workspaceuserpreference');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (450, 'Can change Workspace User Preference', 107, 'change_workspaceuserpreference');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (451, 'Can delete Workspace User Preference', 107, 'delete_workspaceuserpreference');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (452, 'Can view Workspace User Preference', 107, 'view_workspaceuserpreference');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (453, 'Can add Description', 108, 'add_description');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (454, 'Can change Description', 108, 'change_description');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (455, 'Can delete Description', 108, 'delete_description');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (456, 'Can view Description', 108, 'view_description');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (457, 'Can add Description Version', 109, 'add_descriptionversion');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (458, 'Can change Description Version', 109, 'change_descriptionversion');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (459, 'Can delete Description Version', 109, 'delete_descriptionversion');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (460, 'Can view Description Version', 109, 'view_descriptionversion');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (461, 'Can add Project Webhook', 110, 'add_projectwebhook');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (462, 'Can change Project Webhook', 110, 'change_projectwebhook');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (463, 'Can delete Project Webhook', 110, 'delete_projectwebhook');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (464, 'Can view Project Webhook', 110, 'view_projectwebhook');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (465, 'Can add Project User Property', 21, 'add_projectuserproperty');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (466, 'Can change Project User Property', 21, 'change_projectuserproperty');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (467, 'Can delete Project User Property', 21, 'delete_projectuserproperty');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (468, 'Can view Project User Property', 21, 'view_projectuserproperty');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (469, 'Can add interval', 111, 'add_intervalschedule');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (470, 'Can change interval', 111, 'change_intervalschedule');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (471, 'Can delete interval', 111, 'delete_intervalschedule');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (472, 'Can view interval', 111, 'view_intervalschedule');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (473, 'Can add periodic task', 112, 'add_periodictask');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (474, 'Can change periodic task', 112, 'change_periodictask');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (475, 'Can delete periodic task', 112, 'delete_periodictask');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (476, 'Can view periodic task', 112, 'view_periodictask');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (477, 'Can add crontab', 113, 'add_crontabschedule');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (478, 'Can change crontab', 113, 'change_crontabschedule');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (479, 'Can delete crontab', 113, 'delete_crontabschedule');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (480, 'Can view crontab', 113, 'view_crontabschedule');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (481, 'Can add periodic tasks', 114, 'add_periodictasks');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (482, 'Can change periodic tasks', 114, 'change_periodictasks');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (483, 'Can delete periodic tasks', 114, 'delete_periodictasks');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (484, 'Can view periodic tasks', 114, 'view_periodictasks');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (485, 'Can add solar', 115, 'add_solarschedule');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (486, 'Can change solar', 115, 'change_solarschedule');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (487, 'Can delete solar', 115, 'delete_solarschedule');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (488, 'Can view solar', 115, 'view_solarschedule');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (489, 'Can add clocked', 116, 'add_clockedschedule');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (490, 'Can change clocked', 116, 'change_clockedschedule');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (491, 'Can delete clocked', 116, 'delete_clockedschedule');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (492, 'Can view clocked', 116, 'view_clockedschedule');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (493, 'Can add Instance Admin', 117, 'add_instanceadmin');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (494, 'Can change Instance Admin', 117, 'change_instanceadmin');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (495, 'Can delete Instance Admin', 117, 'delete_instanceadmin');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (496, 'Can view Instance Admin', 117, 'view_instanceadmin');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (497, 'Can add Instance', 118, 'add_instance');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (498, 'Can change Instance', 118, 'change_instance');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (499, 'Can delete Instance', 118, 'delete_instance');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (500, 'Can view Instance', 118, 'view_instance');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (501, 'Can add Instance Configuration', 119, 'add_instanceconfiguration');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (502, 'Can change Instance Configuration', 119, 'change_instanceconfiguration');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (503, 'Can delete Instance Configuration', 119, 'delete_instanceconfiguration');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (504, 'Can view Instance Configuration', 119, 'view_instanceconfiguration');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (505, 'Can add Change Log', 120, 'add_changelog');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (506, 'Can change Change Log', 120, 'change_changelog');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (507, 'Can delete Change Log', 120, 'delete_changelog');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (508, 'Can view Change Log', 120, 'view_changelog');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (509, 'Can add session', 121, 'add_session');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (510, 'Can change session', 121, 'change_session');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (511, 'Can delete session', 121, 'delete_session');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES (512, 'Can view session', 121, 'view_session');
SELECT setval(pg_get_serial_sequence('django_content_type', 'id'), (SELECT MAX(id) FROM django_content_type));
SELECT setval(pg_get_serial_sequence('auth_permission', 'id'), (SELECT MAX(id) FROM auth_permission));
