"""Print the timezone list the app offers, in the order the endpoint declares it.

The endpoint pairs a friendly name with an IANA identifier and then sorts by the offset each
identifier has *right now*, so the order changes with daylight saving and cannot be baked in. The
pairs themselves can be, and they are what this prints — CI regenerates it so a zone added or
renamed upstream cannot be missed here.

Run from apps/api:

    python ../api-go/tools/generate_timezone_list.py > ../api-go/internal/project/timezones.tsv
"""

import ast
import os
import sys

SOURCE = "plane/app/views/timezone/base.py"

if not os.path.exists(SOURCE):
    sys.exit(f"{SOURCE} is missing; run this from apps/api")

tree = ast.parse(open(SOURCE).read())
pairs = []
for node in ast.walk(tree):
    if not isinstance(node, ast.Assign):
        continue
    if not any(isinstance(target, ast.Name) and target.id == "timezone_locations" for target in node.targets):
        continue
    for element in node.value.elts:
        name, identifier = (ast.literal_eval(part) for part in element.elts)
        pairs.append((name, identifier))

if not pairs:
    sys.exit("no timezone pairs found")

print("# The timezones apps/api offers, generated by apps/api-go/tools/generate_timezone_list.py.")
print("# Columns: label\tIANA identifier, in the order the endpoint declares them. Do not edit by hand.")
for name, identifier in pairs:
    print(f"{name}\t{identifier}")
