#!/usr/bin/env python
"""Emit the ISO-8601 rendering DRF gives a datetime.

internal/drf reproduces it, and the fixture this writes is what its test diffs against. The rule worth pinning is the one Go's own encoder does not follow: Python pads the fraction to six digits whenever it is non-zero and omits it entirely when it is zero, where Go trims trailing zeros, so 03:04:05.120000 renders as `.120000Z` on Django and `.12Z` on Go.

Both DRF paths are checked against each other here: DateTimeField.to_representation with the default ISO_8601 format, which serializer output goes through, and the JSONEncoder the renderer falls back to for a raw values() dict. Neither is configured away in plane/settings.

Run from apps/api against a configured Django:

    python ../api-go/tools/generate_drf_time_fixture.py > ../api-go/internal/drf/testdata/iso8601.tsv
"""

import datetime
import json
import os
import sys
from datetime import timedelta, timezone

import django

sys.path.insert(0, os.getcwd())
django.setup()

from django.conf import settings  # noqa: E402
from rest_framework.fields import DateTimeField  # noqa: E402
from rest_framework.utils.encoders import JSONEncoder  # noqa: E402

# A microsecond value ending in one or more zeros is the whole point; the rest cover the boundaries.
MICROSECONDS = (0, 1, 10, 1000, 100000, 120000, 123456, 999999)

# UTC is what the columns hold. The offsets are what the sub-issue read produces once it moves a timestamp into the caller's timezone, including one that is not a whole hour.
ZONES = (timezone.utc, timezone(timedelta(hours=8)), timezone(timedelta(hours=-5, minutes=-30)))


def main():
    if settings.TIME_ZONE != "UTC":
        raise SystemExit(f"expected TIME_ZONE=UTC, found {settings.TIME_ZONE!r}: DateTimeField would localize away from the stored value")
    print(
        "# DRF ISO-8601 rendering, generated by apps/api-go/tools/generate_drf_time_fixture.py. Do not edit by hand."
    )
    for zone in ZONES:
        for microsecond in MICROSECONDS:
            moment = datetime.datetime(2026, 1, 2, 3, 4, 5, microsecond, tzinfo=zone)
            rendered = json.loads(json.dumps(moment, cls=JSONEncoder))
            if zone is timezone.utc:
                # The serializer field and the raw renderer have to agree, or one Go type cannot cover both paths.
                assert rendered == DateTimeField().to_representation(moment), moment
            print(f"{moment.isoformat()}\t{rendered}")


if __name__ == "__main__":
    main()
