#!/usr/bin/env python
"""Emit what lxml makes of a work item description.

The external API's IssueSerializer parses `description_html` with `lxml.html.fromstring` and writes it back with `tostring` before it ever reaches the sanitizer, so what gets stored is libxml2's reading of the markup rather than the markup the caller sent. `internal/htmlsanitizer.RoundTrip` reproduces that, and this fixture is what its test diffs against.

Generating it beats reading lxml's source: the wrapper it chooses depends on whether the fragment holds a block-level tag, a fragment that parses to nothing is an error rather than an empty string, and the trailing whitespace after a single root survives while the leading whitespace does not — none of which is visible in the view or the serializer.

Run from apps/api against a configured Django:

    python ../api-go/tools/generate_lxml_fragment_fixture.py > ../api-go/internal/htmlsanitizer/testdata/lxml_fragment.tsv
"""

import json

from lxml import html

CASES = [
    # What the editor really sends.
    "<p>ok</p>",
    "<p></p>",
    "<p><br></p>",
    "<p>a</p><p>b</p>",
    "<h1>t</h1><p>b</p>",
    "<div><p>x</p></div>",
    "<p>a<b>c</b>d</p>",
    "<p class='x' id='y'>z</p>",
    "<ul><li>a<li>b</ul>",
    "<ol><li>one</li></ol>",
    "<blockquote><p>q</p></blockquote>",
    "<pre><code>x = 1</code></pre>",
    "<table><tr><td>1</table>",
    "<table><tbody><tr><td>1</td></tr></tbody></table>",
    "<table><thead><tr><th>h</th></tr></thead><tbody><tr><td>1</td></tr></tbody></table>",
    "<p>a</p><p>b</p><p>c</p>",
    "<img src=x>",
    "<p><img src='x' alt='a'></p>",
    "<a href='https://example.com'>link</a>",
    # A single root keeps its trailing whitespace and loses its leading whitespace.
    "  <p>x</p>  ",
    "<p>a</p> ",
    "\n<p>a</p>\n",
    # Text at the top level is wrapped, and the wrapper depends on whether a block tag is in there.
    "plain text",
    "5",
    "&amp;",
    "text <b>bold</b>",
    "text<p>x</p>",
    "<p>a</p>trailing",
    "<span>a</span><span>b</span>",
    "<b>a</b><i>b</i>",
    "<span>a</span><p>b</p>",
    # Markup that is not closed, or closed in the wrong order.
    "<p>unclosed",
    "<p><b>a</p>",
    "<div><p>a</div>",
    # Head-level content has no body to return, so the whole document comes back.
    "<script>alert(1)</script>",
    "<style>a{}</style>",
    "<title>t</title>",
    "<meta charset='utf-8'>",
    "<head><title>t</title></head>",
    # A document that says it is one is returned whole.
    "<html><body><p>x</p></body></html>",
    "<!DOCTYPE html><html><body><p>x</p></body></html>",
    "<body><p>x</p></body>",
    # Comments.
    "<!-- c --><p>x</p>",
    "<p>a</p><!-- c -->",
    "<p>a<!-- c -->b</p>",
    # Nothing to parse at all.
    "",
    "   ",
    "\n\t ",
    "<!-- only comment -->",
    # Entities, case and quoting are all rewritten.
    "<P>UP</P>",
    "<p>&lt;script&gt;</p>",
    "<p>a &amp; b</p>",
    "<p>a & b</p>",
    "<p title='he said \"hi\"'>x</p>",
    '<p title="a&quot;b&#39;c">x</p>',
    '<p title="a&lt;b&amp;c">x</p>',
    "<p>a>b</p>",
    "<script>if (a<b) {}</script>",
    "<pre>  x  </pre>",
    "<p>中文</p>",
    "<br>",
    "<hr/>",
    "<input type=text value=1>",
    # What the sanitizer is there to catch, before it gets there.
    "<p>a</p><img src=x onerror=alert(1)>",
    "<a href='javascript:alert(1)'>x</a>",
]


def main():
    print(
        "# Ground truth for lxml.html.fromstring + tostring over a work item description, generated by "
        "apps/api-go/tools/generate_lxml_fragment_fixture.py. Do not edit by hand."
    )
    print("# Each row is a JSON-quoted input, the outcome, and a JSON-quoted result. ERROR means lxml refused it.")
    for case in CASES:
        try:
            rendered = html.tostring(html.fromstring(case), encoding="unicode")
            print(f"{json.dumps(case)}\tOK\t{json.dumps(rendered)}")
        except Exception:
            print(f"{json.dumps(case)}\tERROR\t{json.dumps('')}")


if __name__ == "__main__":
    main()
