#!/usr/bin/env python
"""Emit the ORDER BY the external work item list renders for every allowlisted ordering.

`IssueListCreateAPIEndpoint.get` orders inline rather than through `order_issue_queryset`, and the two disagree: this one carries no secondary key, reverses the priority list instead of ordering the same way twice, and gives the state `Case` a default. The fixture this writes is what `internal/externalapi`'s test diffs against, so those differences are pinned by the SQL Django really renders rather than by a reading of the view.

Run from apps/api against a configured Django:

    python ../api-go/tools/generate_external_issue_order_fixture.py > ../api-go/internal/externalapi/testdata/issue_order_by.tsv
"""

import os
import re
import sys

import django

sys.path.insert(0, os.getcwd())
django.setup()

from django.db.models import Case, CharField, Max, Value, When  # noqa: E402

from plane.db.models import Issue  # noqa: E402
from plane.utils.order_queryset import ISSUE_ORDER_BY_ALLOWLIST, sanitize_order_by  # noqa: E402

# The ORDER BY refers to an annotation by its position in the select list, so the reference is resolved back to the expression it points at.
ANNOTATION = re.compile(r"(CASE .*? END|MAX\([^)]*\)) AS \"(\w+)\"")

ALIASES = {"issues": "", "states": "state.", "users": "user.", "labels": "label.", "modules": "module."}


def ordered_queryset(order_by_param):
    """The ordering branch of IssueListCreateAPIEndpoint.get, kept in step with it by hand."""
    priority_order = ["urgent", "high", "medium", "low", "none"]
    state_order = ["backlog", "unstarted", "started", "completed", "cancelled"]
    queryset = Issue.issue_objects.all().order_by("-created_at")

    if order_by_param in ("priority", "-priority"):
        priority_order = priority_order if order_by_param == "priority" else priority_order[::-1]
        return queryset.annotate(
            priority_order=Case(
                *[When(priority=p, then=Value(i)) for i, p in enumerate(priority_order)],
                output_field=CharField(),
            )
        ).order_by("priority_order")

    if order_by_param in ("state__name", "state__group", "-state__name", "-state__group"):
        state_order = state_order if order_by_param in ("state__name", "state__group") else state_order[::-1]
        return queryset.annotate(
            state_order=Case(
                *[When(state__group=state_group, then=Value(i)) for i, state_group in enumerate(state_order)],
                default=Value(len(state_order)),
                output_field=CharField(),
            )
        ).order_by("state_order")

    if order_by_param in ("labels__name", "-labels__name", "assignees__first_name", "-assignees__first_name"):
        return queryset.annotate(
            max_values=Max(order_by_param[1::] if order_by_param.startswith("-") else order_by_param)
        ).order_by("-max_values" if order_by_param.startswith("-") else "max_values")

    return queryset.order_by(order_by_param)


def order_by_clause(value):
    order_by_param = sanitize_order_by(value, ISSUE_ORDER_BY_ALLOWLIST, default="-created_at")
    sql = str(ordered_queryset(order_by_param).query)
    clause = sql[sql.rindex(" ORDER BY ") + len(" ORDER BY ") :]
    annotation = ANNOTATION.search(sql)
    if annotation:
        position = sql[: sql.index(" FROM ")].count(",") + 1
        clause = re.sub(rf"\b{position}\b", annotation.group(1), clause)
    for table, prefix in ALIASES.items():
        clause = clause.replace(f'"{table}".', prefix)
    return clause.replace('"', "")


def main():
    print(
        "# Ground truth for the external work item list ordering, generated by "
        "apps/api-go/tools/generate_external_issue_order_fixture.py. Do not edit by hand."
    )
    for bare in sorted(ISSUE_ORDER_BY_ALLOWLIST):
        for value in (bare, f"-{bare}"):
            print(f"{value}\t{order_by_clause(value)}")
    # A name outside the allowlist falls back, and so does a doubled dash.
    for value in ("", "--created_at", "project__name", "state__id"):
        print(f"{value}\t{order_by_clause(value)}")


if __name__ == "__main__":
    main()
