"""Print every migration the Django app ships, so the Go side can tell whether they are applied.

wait_for_migrations asks Django's migration executor whether anything is pending. There is no
executor here, so the question is asked of the database instead: is every migration this app
ships recorded in django_migrations? The list has to come from the app itself, and CI regenerates
it so a new migration cannot be forgotten.

Run from apps/api:

    python ../api-go/tools/generate_migration_list.py > ../api-go/internal/manage/migrations.tsv
"""

import os
import sys

ROOT = os.getcwd()

print("# Every migration apps/api ships, generated by apps/api-go/tools/generate_migration_list.py. Columns: app\tname. Do not edit by hand.")
rows = []
for app in sorted(os.listdir(os.path.join(ROOT, "plane"))):
    directory = os.path.join(ROOT, "plane", app, "migrations")
    if not os.path.isdir(directory):
        continue
    for entry in sorted(os.listdir(directory)):
        if not entry.endswith(".py") or entry == "__init__.py":
            continue
        rows.append((app, entry[:-3]))

for app, name in sorted(rows):
    print(f"{app}\t{name}")

if not rows:
    sys.exit("no migrations found; run this from apps/api")
