#!/usr/bin/env python
"""Emit what OffsetPaginator and BasePaginator.paginate decide for a request.

This is the second of the three paginators in the codebase, and the one behind the issue list. It is not the cursor paginator internal/pagination already ports: its cursor carries a page size and a backwards flag, its envelope has twelve keys rather than nine, and it answers "is there a next page" by fetching one row more than the page and seeing whether it arrived.

The arithmetic is pure over the cursor and the totals, so it is reproduced here from the same expressions the class uses rather than from a database.

Run from apps/api against a configured Django:

    python ../api-go/tools/generate_offset_paginator_fixture.py > ../api-go/internal/pagination/testdata/offset.tsv
"""

import math

MAX_LIMIT = 1000


def plan(per_page, cursor_value, cursor_offset, total, max_limit=MAX_LIMIT):
    """The window, the cursors and the counts, exactly as get_result computes them."""
    limit = min(per_page, max_limit)
    page = cursor_offset
    offset = cursor_offset * limit
    stop = offset + limit + 1

    # The rows the window would return, and whether one more than the page arrived.
    window = max(0, min(stop, total) - offset)
    next_has_results = window > limit
    prev_has_results = page > 0

    returned = min(window, limit)
    max_hits = math.ceil(total / limit) if limit else None

    return {
        "offset": offset,
        "stop": stop,
        "returned": returned,
        "next_cursor": f"{limit}:{page + 1}:0",
        "prev_cursor": f"{limit}:{page - 1}:1",
        "next_page_results": next_has_results,
        "prev_page_results": prev_has_results,
        "total_count": total,
        "total_pages": max_hits,
    }


def main():
    print(
        "# OffsetPaginator, generated by apps/api-go/tools/generate_offset_paginator_fixture.py. "
        "Columns: per_page cursor_value cursor_offset total -> offset stop returned next_cursor prev_cursor "
        "next_page_results prev_page_results total_count total_pages. Do not edit by hand."
    )
    for total in (0, 1, 9, 10, 11, 25, 1000, 2500):
        for per_page in (1, 10, 25, 1000, 2000):
            for cursor_offset in (0, 1, 2, 5, 40):
                cursor_value = per_page
                result = plan(per_page, cursor_value, cursor_offset, total)
                print("\t".join(str(item) for item in [
                    per_page, cursor_value, cursor_offset, total,
                    result["offset"], result["stop"], result["returned"],
                    result["next_cursor"], result["prev_cursor"],
                    int(result["next_page_results"]), int(result["prev_page_results"]),
                    result["total_count"], result["total_pages"],
                ]))


if __name__ == "__main__":
    main()
