#!/usr/bin/env python
"""Emit what GroupedOffsetPaginator does to a page of rows.

internal/pagination reproduces two halves of that class: the offset arithmetic that decides which window of row numbers a cursor asks for, and process_results, which turns a flat page of rows into the grouped body the issue list returns. Both are pure over their inputs, so both can be diffed without a database.

The grouping is where the surprises are. A group-by over a many-to-many field makes the queryset fan one issue into several rows, so the paginator collects the group ids per issue, rewrites the issue's own id array from them, and files the issue under each — and an issue in no group at all is filed under the literal string None with an empty array. A group-by over a plain column instead pre-seeds every known group, so a group with no rows still appears with an empty result list, which the many-to-many path does not do.

Run from apps/api against a configured Django:

    python ../api-go/tools/generate_grouped_paginator_fixture.py > ../api-go/internal/pagination/testdata/grouped.tsv
"""

import json
import os
import random
import types

SOURCE = os.path.join(os.getcwd(), "plane", "utils", "paginator.py")

FIELD_MAPPER = {
    "labels__id": "label_ids",
    "assignees__id": "assignee_ids",
    "issue_module__module_id": "module_ids",
}

PLAIN_FIELDS = ["state_id", "priority", "state__group", "cycle_id"]

RANDOM_PAGES = 120
SEED = 23


def load_paginator():
    """Load the paginator module without importing Django's ORM, which it only needs at query time."""
    source = open(SOURCE).read()
    source = source.replace("from django.db.models import Count, F, Window", "")
    source = source.replace("from django.db.models.functions import RowNumber", "")
    source = source.replace("from rest_framework.exceptions import ParseError", "class ParseError(Exception):\n    pass")
    source = source.replace("from rest_framework.response import Response", "")
    source = source.replace("from plane.utils.order_queryset import ISSUE_GROUP_BY_ALLOWLIST", "ISSUE_GROUP_BY_ALLOWLIST = frozenset()")
    module = types.ModuleType("paginator_pure")
    exec(compile(source, SOURCE, "exec"), module.__dict__)
    return module


class FakePaginator:
    """The two methods under test, with the queryset-backed totals supplied directly."""

    def __init__(self, paginator_module, group_by_field_name, group_by_fields, totals):
        self.instance = paginator_module.GroupedOffsetPaginator.__new__(paginator_module.GroupedOffsetPaginator)
        self.instance.group_by_field_name = group_by_field_name
        self.instance.group_by_fields = group_by_fields
        self.instance.FIELD_MAPPER = FIELD_MAPPER
        self.totals = totals
        # The private helpers read the queryset; only their dictionary output matters here.
        self.instance._GroupedOffsetPaginator__get_total_dict = lambda: totals

    def process(self, results):
        return self.instance.process_results(results)


def sort_id_arrays(processed):
    """Sort the id arrays the many-to-many path writes.

    Django builds them from a Python set, whose iteration order is not stable across processes because string hashing is randomized. The order is therefore arbitrary rather than meaningful, and sorting both sides is what makes the fixture reproducible; the Go port sorts too, which is a valid reading of an arbitrary order and a more useful one.
    """
    for group in processed.values():
        for row in group["results"]:
            for key in FIELD_MAPPER.values():
                if isinstance(row.get(key), list):
                    row[key] = sorted(row[key])


def offsets(page, value, limit):
    """The window of row numbers a cursor asks for."""
    offset = page * value
    stop = offset + (value or limit) + 1
    return offset, stop


def main():
    module = load_paginator()
    random.seed(SEED)

    print(
        "# GroupedOffsetPaginator, generated by apps/api-go/tools/generate_grouped_paginator_fixture.py. "
        "Rows are either an offset case or a grouping case. Do not edit by hand."
    )

    # The offset arithmetic, which uses the page size baked into the cursor rather than the request's limit.
    for page in (0, 1, 2, 7):
        for value in (0, 1, 10, 50):
            for limit in (1, 10, 50):
                offset, stop = offsets(page, value, limit)
                print(f"offset\t{page}\t{value}\t{limit}\t{offset}\t{stop}")

    # The grouping, over both kinds of group field.
    identifiers = [f"id-{index}" for index in range(1, 7)]
    groups = [f"group-{index}" for index in range(1, 4)]

    cases = []
    for field in list(FIELD_MAPPER) + PLAIN_FIELDS:
        # An issue in exactly one group, one in several, and one in none.
        cases.append((field, [
            {"id": identifiers[0], field: groups[0]},
            {"id": identifiers[1], field: groups[0]},
            {"id": identifiers[1], field: groups[1]},
            {"id": identifiers[2], field: None},
        ]))
        cases.append((field, []))
        cases.append((field, [{"id": identifiers[0], field: groups[0]}]))

    for _ in range(RANDOM_PAGES):
        field = random.choice(list(FIELD_MAPPER) + PLAIN_FIELDS)
        rows = []
        for _ in range(random.randint(1, 6)):
            rows.append({
                "id": random.choice(identifiers),
                field: random.choice(groups + [None]),
            })
        cases.append((field, rows))

    seen = set()
    for field, rows in cases:
        key = (field, json.dumps(rows, sort_keys=True))
        if key in seen:
            continue
        seen.add(key)
        totals = {group: index + 1 for index, group in enumerate(groups)}
        totals["None"] = 9
        paginator = FakePaginator(module, field, groups + ["None"], totals)
        # process_results mutates its input for the many-to-many path, so it is handed a copy.
        processed = paginator.process([dict(row) for row in rows])
        sort_id_arrays(processed)
        print(f"group\t{field}\t{json.dumps(rows, sort_keys=True)}\t{json.dumps(totals, sort_keys=True)}\t{json.dumps(processed, sort_keys=True)}")


if __name__ == "__main__":
    main()
