"""Generate the truth table for the work item activity trackers that need no database.

Each line is a tab-separated triple: the json the request carried, the json the snapshot
carried, and what the tracker appended — rendered as `field|verb|old|new|comment`, with
one entry per row and `-` for nothing at all.

The trackers that read the database (state, parent, labels, assignees, estimate) are not
here: what they write depends on rows, not on the two snapshots, so a table of values
would only be testing the fixture.

Run from apps/api with the project's settings on the path:

    DJANGO_SETTINGS_MODULE=plane.settings.production SECRET_KEY=x \
    REDIS_URL=redis://localhost:6379/ DATABASE_URL=postgresql://u:p@localhost:5432/plane \
    python ../api-go/tools/generate_issue_activity_fixture.py > \
    ../api-go/internal/worker/testdata/issue_activity.tsv
"""

import json
import os
import sys

sys.path.insert(0, os.getcwd())

import django  # noqa: E402

django.setup()

from plane.bgtasks.issue_activities_task import (  # noqa: E402
    track_archive_at,
    track_name,
    track_priority,
    track_start_date,
    track_target_date,
)

TRACKERS = {
    "name": track_name,
    "priority": track_priority,
    "target_date": track_target_date,
    "start_date": track_start_date,
    "archived_at": track_archive_at,
}


def render(activities):
    if not activities:
        return "-"
    parts = []
    for activity in activities:
        parts.append(
            "|".join(
                [
                    str(activity.field),
                    str(activity.verb),
                    "<none>" if activity.old_value is None else str(activity.old_value),
                    "<none>" if activity.new_value is None else str(activity.new_value),
                    str(activity.comment),
                ]
            )
        )
    return ";".join(parts)


CASES = [
    ("name", {"name": "After"}, {"name": "Before"}),
    ("name", {"name": "Same"}, {"name": "Same"}),
    ("name", {"name": "New"}, {}),
    ("name", {"name": None}, {"name": "Before"}),
    ("name", {"name": ""}, {"name": "Before"}),
    ("priority", {"priority": "high"}, {"priority": "low"}),
    ("priority", {"priority": "none"}, {"priority": "none"}),
    ("priority", {"priority": None}, {"priority": "urgent"}),
    ("target_date", {"target_date": "2026-01-02"}, {"target_date": None}),
    ("target_date", {"target_date": None}, {"target_date": "2026-01-02"}),
    ("target_date", {"target_date": "2026-01-02"}, {"target_date": "2026-01-02"}),
    ("target_date", {"target_date": "2026-02-03"}, {"target_date": "2026-01-02"}),
    ("start_date", {"start_date": "2026-01-02"}, {"start_date": None}),
    ("start_date", {"start_date": None}, {"start_date": "2026-01-02"}),
    ("start_date", {"start_date": "2026-02-03"}, {"start_date": "2026-01-02"}),
    ("archived_at", {"archived_at": None}, {"archived_at": "2026-01-02"}),
    ("archived_at", {"archived_at": "2026-01-02"}, {"archived_at": None}),
    ("archived_at", {"archived_at": "2026-01-02", "automation": True}, {"archived_at": None}),
    ("archived_at", {"archived_at": "2026-01-02", "automation": False}, {"archived_at": None}),
    ("archived_at", {"archived_at": "2026-01-02"}, {"archived_at": "2026-01-02"}),
]


def main():
    print("# The work item activity trackers that need no database, generated by "
          "apps/api-go/tools/generate_issue_activity_fixture.py. Do not edit by hand.")
    for tracker, requested, current in CASES:
        activities = []
        TRACKERS[tracker](
            requested_data=requested,
            current_instance=current,
            issue_id="11111111-1111-1111-1111-111111111111",
            project_id="22222222-2222-2222-2222-222222222222",
            workspace_id="33333333-3333-3333-3333-333333333333",
            actor_id="44444444-4444-4444-4444-444444444444",
            issue_activities=activities,
            epoch=1700000000,
        )
        print("\t".join([
            tracker,
            json.dumps(requested, sort_keys=True, separators=(",", ":")),
            json.dumps(current, sort_keys=True, separators=(",", ":")),
            render(activities),
        ]))


if __name__ == "__main__":
    main()
