#!/usr/bin/env python
"""Emit the ORDER BY Django renders for every allowlisted issue ordering.

internal/project/issue_ordering.go reproduces order_issue_queryset, and the fixture this writes is what its test diffs against. Generating it beats reading the Python: three of the behaviours it pins — that no clause carries a NULLS position, that the priority Case has no default, and that the priority ordering is identical in both directions — are invisible in the source and only show up in the rendered SQL.

Run from apps/api against a configured Django:

    python ../api-go/tools/generate_issue_order_fixture.py > ../api-go/internal/project/testdata/issue_order_by.tsv
"""

import os
import re
import sys

import django

sys.path.insert(0, os.getcwd())
django.setup()

from plane.db.models import Issue  # noqa: E402
from plane.utils.order_queryset import ISSUE_ORDER_BY_ALLOWLIST, order_issue_queryset  # noqa: E402

# The workflow exports DJANGO_SETTINGS_MODULE, the same as for the relation graph.

# The ORDER BY refers to an annotation by its position in the select list, so the reference is resolved back to the expression it points at. Otherwise every Case ordering would render as a bare column number.
ANNOTATION = re.compile(r"(CASE .*? END|MIN\([^)]*\)) AS \"(\w+)\"")

# Table aliases are rewritten to a stable name so the fixture does not depend on Django's join numbering: the issue table drops out entirely and each joined table keeps a singular prefix.
ALIASES = {"issues": "", "states": "state.", "users": "user.", "labels": "label.", "modules": "module."}


def order_by_clause(value):
    queryset, _ = order_issue_queryset(Issue.issue_objects.all(), value)
    sql = str(queryset.query)
    clause = sql[sql.rindex(" ORDER BY ") + len(" ORDER BY ") :]
    annotation = ANNOTATION.search(sql)
    if annotation:
        position = sql[: sql.index(" FROM ")].count(",") + 1
        clause = re.sub(rf"\b{position}\b", annotation.group(1), clause)
    for table, prefix in ALIASES.items():
        clause = clause.replace(f'"{table}".', prefix)
    return clause.replace('"', "")


def main():
    print(
        "# Ground truth for order_issue_queryset, generated by "
        "apps/api-go/tools/generate_issue_order_fixture.py. Do not edit by hand."
    )
    for bare in sorted(ISSUE_ORDER_BY_ALLOWLIST):
        for value in (bare, f"-{bare}"):
            print(f"{value}\t{order_by_clause(value)}")


if __name__ == "__main__":
    main()
