#!/usr/bin/env python
"""Emit every route Django serves, as a method and a shape.

The proxy cuts traffic over by path, not by method, so cutting a path over while only some of its methods are implemented sends the rest into a 404. That happened once; this fixture is what turns it into a build failure instead.

Each line is a method and the path with every parameter replaced by a star, which is the same shape internal/server derives from the Go router and the Caddyfile. A path that Django serves and the proxy has cut over must have every one of its methods on the Go side.

Run from apps/api against a configured Django:

    python ../api-go/tools/generate_django_routes.py > ../api-go/internal/server/testdata/django_routes.tsv
"""

import inspect
import os
import re
import sys

import django

sys.path.insert(0, os.getcwd())
django.setup()

from django.urls import get_resolver  # noqa: E402
from django.urls.resolvers import URLPattern, URLResolver  # noqa: E402

PARAMETER = re.compile(r"<[^>]+>")
PARAMETER_NAME = re.compile(r"<[^:>]*:?([^>]+)>")
# A DRF router contributes regex patterns rather than path() routes, so its entries arrive as raw
# regular expressions. They are rewritten into the same <name> notation before anything else looks
# at them, or the table would carry literal patterns that match nothing and the guard would silently
# stop checking those paths.
REGEX_GROUP = re.compile(r"\(\?P<([^>]+)>[^)]*\)")
OPTIONAL_SLASH = re.compile(r"/\?$")
METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE"]


def shape(route):
    """The path with every parameter replaced by a star."""
    return "/" + PARAMETER.sub("*", route).lstrip("/")


def methods_for(pattern, route):
    """The HTTP methods a view answers on this path, read off the view rather than guessed.

    A ViewSet routed through as_view({...}) records its mapping, so that one is exact. A plain APIView has no mapping: it dispatches on the method name, so every handler it defines is reachable on every path bound to it — but a handler whose signature does not match the path's captured parameters raises TypeError before it does anything. Those are not routes the proxy needs to serve, so the signature is compared and they are left out.
    """
    callback = pattern.callback
    mapping = getattr(callback, "actions", None)
    if mapping:
        return sorted({method.upper() for method in mapping})
    view_class = getattr(callback, "cls", None) or getattr(callback, "view_class", None)
    if view_class is None:
        return []

    captured = set(PARAMETER_NAME.findall(route))
    answered = []
    for method in METHODS:
        handler = getattr(view_class, method.lower(), None)
        if handler is None:
            continue
        if accepts(handler, captured):
            answered.append(method)
    return sorted(answered)


def accepts(handler, captured):
    """Whether a handler can be called with exactly the parameters this path captures."""
    try:
        signature = inspect.signature(handler)
    except (TypeError, ValueError):
        return True
    required = set()
    optional = set()
    for name, parameter in list(signature.parameters.items())[2:]:
        if parameter.kind in (parameter.VAR_POSITIONAL, parameter.VAR_KEYWORD):
            # A handler taking **kwargs accepts whatever the path captures.
            return True
        if parameter.default is parameter.empty:
            required.add(name)
        else:
            optional.add(name)
    return required <= captured <= (required | optional)


def normalize(pattern):
    """The route a pattern contributes, in path() notation whether it was written that way or not."""
    route = getattr(pattern.pattern, "_route", None)
    if route is not None:
        return str(route)
    # A regex pattern: strip the anchors and the trailing optional slash, unescape the literal dots
    # a format suffix carries, and turn each named group into <name>. The format-suffix routes a DRF
    # router appends are kept rather than dropped: they are paths Django really serves, and the guard
    # is only useful if the table is complete.
    expression = str(pattern.pattern).lstrip("^").rstrip("$")
    expression = OPTIONAL_SLASH.sub("", expression)
    expression = expression.replace("\\.", ".")
    return REGEX_GROUP.sub(lambda match: "<" + match.group(1) + ">", expression)


def walk(resolver, prefix=""):
    for pattern in resolver.url_patterns:
        route = prefix + normalize(pattern)
        if isinstance(pattern, URLResolver):
            yield from walk(pattern, route)
            continue
        if not isinstance(pattern, URLPattern):
            continue
        for method in methods_for(pattern, route):
            yield method, shape(route)


def main():
    print(
        "# Every route Django serves, generated by apps/api-go/tools/generate_django_routes.py. "
        "Each line is a method and the path with every parameter replaced by a star. Do not edit by hand."
    )
    seen = set()
    for method, path in sorted(walk(get_resolver())):
        if (method, path) in seen:
            continue
        seen.add((method, path))
        print(f"{method}\t{path}")


if __name__ == "__main__":
    main()
