#!/usr/bin/env python
"""Emit what the external API's IssueSerializer says about a bad work item payload.

`internal/externalapi` answers with the serializer's own errors, and a body that differs from DRF's is a body no integration can read. The fixture this writes is what its test diffs against.

Only payloads that are decided without reading a row are listed, so the fixture is the same whether or not a database is in reach. The checks that do look a row up — a state in another project, a parent that does not exist — are covered by tests of their own.

Run from apps/api against a configured Django:

    python ../api-go/tools/generate_external_issue_validation_fixture.py > ../api-go/internal/externalapi/testdata/issue_validation.tsv
"""

import json
import os
import sys

import django

sys.path.insert(0, os.getcwd())
django.setup()

from plane.api.serializers.issue import IssueSerializer  # noqa: E402

CASES = [
    {},
    {"name": ""},
    {"name": None},
    {"name": "x" * 256},
    {"name": "ok"},
    {"name": "ok", "priority": "critical"},
    {"name": "ok", "priority": None},
    {"name": "ok", "priority": "urgent"},
    {"name": "ok", "start_date": "2026-05-01", "target_date": "2026-04-01"},
    {"name": "ok", "start_date": "2026-04-01", "target_date": "2026-05-01"},
    {"name": "ok", "start_date": "not-a-date"},
    {"name": "ok", "start_date": None, "target_date": None},
    {"name": "ok", "archived_at": "nonsense"},
    {"name": "ok", "archived_at": "2026-04-01"},
    {"name": "ok", "deleted_at": "nonsense"},
    {"name": "ok", "deleted_at": "2026-04-01T10:00:00Z"},
    {"name": "ok", "point": 99},
    {"name": "ok", "point": -1},
    {"name": "ok", "point": "abc"},
    {"name": "ok", "point": None},
    {"name": "ok", "point": 12},
    {"name": "ok", "is_draft": "maybe"},
    {"name": "ok", "is_draft": True},
    {"name": "ok", "sort_order": "abc"},
    {"name": "ok", "sort_order": 1.5},
    {"name": "ok", "sequence_id": "abc"},
    {"name": "ok", "external_id": "x" * 256},
    {"name": "ok", "external_source": None},
    {"name": "ok", "unknown_field": 1},
    {"name": "ok", "description_html": ""},
    {"name": "ok", "description_html": "   "},
    {"name": "ok", "description_html": None},
    {"name": "ok", "description_html": "<p>ok</p>"},
    {"name": "ok", "description_html": "<p>a</p><p>b</p>"},
    {"name": "ok", "description_html": "<p>a</p><img src=x onerror=alert(1)>"},
    {"name": "ok", "description_html": 5},
    # A malformed identifier is refused before any row is read.
    {"name": "ok", "state": "not-a-uuid"},
    {"name": "ok", "parent": "not-a-uuid"},
    {"name": "ok", "type_id": "not-a-uuid"},
    {"name": "ok", "estimate_point": "not-a-uuid"},
    {"name": "ok", "created_by": "not-a-uuid"},
    {"name": "ok", "assignees": "nope"},
    {"name": "ok", "assignees": ["not-a-uuid"]},
    {"name": "ok", "labels": {}},
    {"name": "ok", "labels": ["not-a-uuid"]},
    # Coercion, and more than one bad field at once.
    {"name": 5},
    {"name": True},
    {"name": ["a"]},
    {"name": "ok", "point": 1.5},
    {"name": "ok", "point": "12"},
    {"name": "ok", "deleted_at": "2026-04-01"},
    {"name": "ok", "is_draft": "true"},
    {"name": "ok", "is_draft": 1},
    {"name": "ok", "sort_order": "1.5"},
    {"name": "", "priority": "critical"},
    {"name": "ok", "start_date": "2026-04-01T10:00:00Z"},
    {"name": "ok", "description_html": True},
    {"name": "ok", "description_html": "<script>x</script>"},
    {"name": "ok", "assignees": []},
    {"name": "ok", "labels": []},
]


def main():
    print(
        "# Ground truth for the external work item serializer, generated by "
        "apps/api-go/tools/generate_external_issue_validation_fixture.py. Do not edit by hand."
    )
    print("# Each row is a JSON payload, the outcome, and the JSON body DRF answers with. VALID means it was accepted.")
    for case in CASES:
        serializer = IssueSerializer(
            data=case,
            context={"project_id": None, "workspace_id": None, "default_assignee_id": None},
        )
        if serializer.is_valid():
            # A payload that is accepted is reported with what the serializer made of its description, which is the one field it rewrites.
            rendered = serializer.validated_data.get("description_html", "")
            print(f"{json.dumps(case, sort_keys=True)}\tVALID\t{json.dumps(rendered)}")
            continue
        errors = json.loads(json.dumps(serializer.errors, default=str))
        print(f"{json.dumps(case, sort_keys=True)}\tINVALID\t{json.dumps(errors, sort_keys=True)}")


if __name__ == "__main__":
    main()
