#!/usr/bin/env python
"""Emit what issue_filters turns a query string into.

internal/project.issueFilters reproduces it, and the fixture this writes is what its test diffs against. The function maps twenty-five query parameters onto ORM lookups, and the mapping is full of small asymmetries that are invisible unless the two are compared row by row: GET splits on commas while POST takes the value whole, some filters drop invalid uuids and others keep whatever they were given, and a literal "None" turns into an isnull lookup on some filters and nothing at all on others.

The relative date terms depend on today's date, so the clock is frozen: the module is loaded with timezone.now().date() replaced by a fixed day, and the Go test is given the same day. Without that the fixture would go stale every morning.

Run from apps/api against a configured Django:

    python ../api-go/tools/generate_issue_filters_fixture.py > ../api-go/internal/project/testdata/issue_filters.tsv
"""

import datetime
import importlib.util
import itertools
import json
import os
import random
import sys
import types
import uuid

# The day the relative terms are measured from. Any fixed date works; this one only has to match the constant the Go test uses.
FROZEN_TODAY = datetime.date(2026, 6, 15)

SOURCE = os.path.join(os.getcwd(), "plane", "utils", "issue_filters.py")

UUIDS = [str(uuid.UUID(int=index)) for index in range(1, 4)]

# Values chosen to hit each branch: an empty string, a literal null, a literal None, one and several uuids, and one that is not a uuid at all.
LIST_VALUES = ["", "null", "None", UUIDS[0], f"{UUIDS[0]},{UUIDS[1]}", "not-a-uuid", f"None,{UUIDS[0]}", f"{UUIDS[0]},null", ","]

DATE_VALUES = [
    "", "2026-01-02", "2026-01-02;after", "2026-01-02;before",
    "2_weeks;after;fromnow", "2_weeks;before;fromnow", "3_months;after;fromnow",
    "3_months;before;fromnow", "2_weeks;after;", "1_months;before;past",
    "2026-01-02;after,2026-03-04;before", "2_weeks", "garbage;after;fromnow",
]

PLAIN_VALUES = ["", "true", "false", "null", "None", "Backlog", "1"]

LIST_FILTERS = ["state", "state_group", "estimate_point", "priority", "parent", "labels", "assignees", "mentions", "created_by", "logged_by", "project", "cycle", "module", "intake_status", "inbox_status", "subscriber"]
DATE_FILTERS = ["created_at", "updated_at", "start_date", "target_date", "completed_at"]
PLAIN_FILTERS = ["name", "type", "sub_issue", "start_target_date"]

RANDOM_COMBINATIONS = 150
SEED = 11


def load_module():
    """Load issue_filters with its clock frozen, so the relative date terms are reproducible."""
    source = open(SOURCE).read()
    source = source.replace("from django.utils import timezone", "")
    source = source.replace("now = timezone.now().date()", "now = FROZEN_TODAY")
    module = types.ModuleType("issue_filters_frozen")
    module.FROZEN_TODAY = FROZEN_TODAY
    exec(compile(source, SOURCE, "exec"), module.__dict__)
    return module


def render(value):
    """Serialize a filter value so the two sides compare literally."""
    if isinstance(value, list):
        return "[" + ",".join(render(item) for item in value) + "]"
    if isinstance(value, uuid.UUID):
        return str(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def main():
    module = load_module()
    random.seed(SEED)

    cases = []
    for name, values in itertools.chain(
        ((name, LIST_VALUES) for name in LIST_FILTERS),
        ((name, DATE_VALUES) for name in DATE_FILTERS),
        ((name, PLAIN_VALUES) for name in PLAIN_FILTERS),
    ):
        for value in values:
            for method in ("GET", "POST"):
                cases.append((method, "", {name: value}))
                cases.append((method, "issue__", {name: value}))

    # A handful of combinations, since the filters share one output dictionary and a later one can overwrite an earlier one's key.
    every = LIST_FILTERS + DATE_FILTERS + PLAIN_FILTERS
    for _ in range(RANDOM_COMBINATIONS):
        chosen = random.sample(every, random.randint(2, 4))
        params = {}
        for name in chosen:
            pool = LIST_VALUES if name in LIST_FILTERS else DATE_VALUES if name in DATE_FILTERS else PLAIN_VALUES
            params[name] = random.choice(pool)
        cases.append((random.choice(["GET", "POST"]), random.choice(["", "issue__"]), params))

    print(
        "# plane.utils.issue_filters.issue_filters, generated by "
        "apps/api-go/tools/generate_issue_filters_fixture.py with the clock frozen to "
        f"{FROZEN_TODAY.isoformat()}. Columns: method, prefix, params json, filter json. Do not edit by hand."
    )
    seen = set()
    for method, prefix, params in cases:
        key = (method, prefix, json.dumps(params, sort_keys=True))
        if key in seen:
            continue
        seen.add(key)
        result = module.issue_filters(params, method, prefix)
        rendered = {lookup: render(value) for lookup, value in sorted(result.items())}
        print(f"{method}\t{prefix}\t{json.dumps(params, sort_keys=True)}\t{json.dumps(rendered, sort_keys=True)}")


if __name__ == "__main__":
    main()
