#!/usr/bin/env python
"""Emit what sanitize_filename does to a corpus of hostile names.

internal/project.sanitizeFilename reproduces it, and the fixture this writes is what its test diffs against. The name becomes part of an S3 object key, so getting it wrong means a caller can write outside the workspace prefix.

Most of the corpus is assembled at random from the characters that actually decide the answer — dots, slashes, backslashes, whitespace and control bytes — because the order of the function's steps matters in ways a hand-written table does not reach. Whitespace is stripped before the leading dots, so " .env" loses both; and Python's basename keeps nothing after a trailing separator, where Go's path.Base would hand back the last component.

Run from apps/api against a configured Django:

    python ../api-go/tools/generate_sanitize_filename_fixture.py > ../api-go/internal/project/testdata/sanitize_filename.tsv
"""

import os
import random
import sys

sys.path.insert(0, os.getcwd())

from plane.utils.path_validator import sanitize_filename  # noqa: E402

FIXED = [
    "report.pdf", "", "   ", ".env", " .env", "..env", "...env",
    "../../etc/passwd", "..\\..\\windows\\system32\\config",
    "dir/sub/file.txt", "dir\\sub\\file.txt", "/absolute/path.txt",
    "trailing/", "trailing\\", "a..b.txt", "....", "..", ".",
    "file\x00name.txt", "tab\tname.txt", "new\nline.txt", "\x7fdel.txt",
    "  spaced  .txt  ", "no_extension", "UPPER.TXT", "中文 文件.pdf",
    "a/b/../c.txt", "....//....//etc/passwd", "~/.ssh/id_rsa",
    "file.tar.gz", "..hidden..txt", " . . . ", "$(whoami).txt",
    "a" * 300 + ".txt",
]

ALPHABET = [".", ".", "/", "\\", "a", "b", ".", " ", "\t", "\x00", "\x7f", "..", "/", "\\"]

RANDOM_CASES = 400
SEED = 7


def main():
    random.seed(SEED)
    cases = list(FIXED)
    for _ in range(RANDOM_CASES):
        cases.append("".join(random.choice(ALPHABET) for _ in range(random.randint(0, 12))))

    print(
        "# plane.utils.path_validator.sanitize_filename, generated by "
        "apps/api-go/tools/generate_sanitize_filename_fixture.py. A result of - means the function returned None, "
        "which the caller replaces with the placeholder. Do not edit by hand."
    )
    seen = set()
    for case in cases:
        if case in seen:
            continue
        seen.add(case)
        result = sanitize_filename(case)
        print(f"{case!r}\t{'-' if result is None else repr(result)}")


if __name__ == "__main__":
    main()
