#!/usr/bin/env python
"""Emit what SubGroupedOffsetPaginator.process_results does to a page of rows.

This is the third grouping shape in the codebase, and the most fragile. A page is nested twice — group, then sub-group — and the two paths through it behave differently: the plain one indexes the pre-seeded dictionary without checking, so a row whose group or sub-group was not pre-seeded raises KeyError and answers 500, while the many-to-many one checks and silently drops the row.

Only sub-groups that actually have a row are pre-seeded, so a group can come back with an empty results dictionary even though its own total is set.

Run from apps/api against a configured Django:

    python ../api-go/tools/generate_subgrouped_fixture.py > ../api-go/internal/pagination/testdata/subgrouped.tsv
"""

import json
import os
import random
import types

SOURCE = os.path.join(os.getcwd(), "plane", "utils", "paginator.py")

FIELD_MAPPER = {
    "labels__id": "label_ids",
    "assignees__id": "assignee_ids",
    "issue_module__module_id": "module_ids",
}

RANDOM_PAGES = 100
SEED = 31


def load_paginator():
    source = open(SOURCE).read()
    source = source.replace("from django.db.models import Count, F, Window", "")
    source = source.replace("from django.db.models.functions import RowNumber", "")
    source = source.replace("from rest_framework.exceptions import ParseError", "class ParseError(Exception):\n    pass")
    source = source.replace("from rest_framework.response import Response", "")
    source = source.replace("from plane.utils.order_queryset import ISSUE_GROUP_BY_ALLOWLIST", "ISSUE_GROUP_BY_ALLOWLIST = frozenset()")
    module = types.ModuleType("paginator_pure")
    exec(compile(source, SOURCE, "exec"), module.__dict__)
    return module


def build(module, group_field, sub_field, group_values, group_totals, sub_totals):
    instance = module.SubGroupedOffsetPaginator.__new__(module.SubGroupedOffsetPaginator)
    instance.group_by_field_name = group_field
    instance.sub_group_by_field_name = sub_field
    instance.group_by_fields = group_values
    instance.FIELD_MAPPER = FIELD_MAPPER
    instance._SubGroupedOffsetPaginator__get_total_dict = lambda: (group_totals, sub_totals)
    return instance


def sort_id_arrays(processed):
    """Sort the id arrays, whose order comes from a Python set and is therefore not stable across processes."""
    for group in processed.values():
        for sub in group["results"].values():
            for row in sub["results"]:
                for key in FIELD_MAPPER.values():
                    if isinstance(row.get(key), list):
                        row[key] = sorted(row[key])


def main():
    module = load_paginator()
    random.seed(SEED)

    print(
        "# SubGroupedOffsetPaginator.process_results, generated by "
        "apps/api-go/tools/generate_subgrouped_fixture.py. Columns: group_field sub_field group_values "
        "group_totals sub_totals rows -> processed, or the exception it raised. Do not edit by hand."
    )

    groups = ["g1", "g2"]
    subs = ["s1", "s2"]
    identifiers = ["i1", "i2", "i3"]
    pairs = [("state_id", "priority"), ("labels__id", "priority"), ("state_id", "assignees__id"), ("labels__id", "assignees__id")]

    cases = []
    for group_field, sub_field in pairs:
        cases.append((group_field, sub_field, [
            {"id": identifiers[0], group_field: groups[0], sub_field: subs[0]},
            {"id": identifiers[1], group_field: groups[0], sub_field: subs[1]},
            {"id": identifiers[1], group_field: groups[1], sub_field: subs[1]},
            {"id": identifiers[2], group_field: None, sub_field: None},
        ]))
        cases.append((group_field, sub_field, []))
        # A row whose group was never pre-seeded, which is where the two paths part company.
        cases.append((group_field, sub_field, [{"id": identifiers[0], group_field: "unseeded", sub_field: subs[0]}]))

    for _ in range(RANDOM_PAGES):
        group_field, sub_field = random.choice(pairs)
        rows = []
        for _ in range(random.randint(1, 5)):
            rows.append({
                "id": random.choice(identifiers),
                group_field: random.choice(groups + [None, "unseeded"]),
                sub_field: random.choice(subs + [None]),
            })
        cases.append((group_field, sub_field, rows))

    group_values = groups + ["None"]
    group_totals = {"g1": 1, "g2": 2, "None": 3}
    sub_totals = {"g1": {"s1": 4, "s2": 5, "None": 6}, "g2": {"s1": 7, "None": 8}, "None": {"None": 9}}

    seen = set()
    for group_field, sub_field, rows in cases:
        key = (group_field, sub_field, json.dumps(rows, sort_keys=True))
        if key in seen:
            continue
        seen.add(key)
        instance = build(module, group_field, sub_field, group_values, group_totals, sub_totals)
        try:
            processed = instance.process_results([dict(row) for row in rows])
            sort_id_arrays(processed)
            rendered = json.dumps(processed, sort_keys=True)
        except Exception as error:
            rendered = f"!{type(error).__name__}"
        print("\t".join([
            group_field, sub_field, json.dumps(group_values),
            json.dumps(group_totals, sort_keys=True), json.dumps(sub_totals, sort_keys=True),
            json.dumps(rows, sort_keys=True), rendered,
        ]))


if __name__ == "__main__":
    main()
