"""Print the instance configuration variables the Django app seeds, without resolving them.

configure_instance writes one row per variable, taking each value from an environment variable.
The Go side needs the same list, so what is printed here is the definition rather than the value:
the key, the environment variable it reads, the default when that is unset, the category, and
whether the value is stored encrypted. CI regenerates it so a variable added there cannot be
missed here.

Run from apps/api:

    python ../api-go/tools/generate_instance_config_variables.py > \
    ../api-go/internal/manage/instance_config.tsv
"""

import ast
import os
import sys

SOURCES = [
    "plane/utils/instance_config_variables/core.py",
    "plane/utils/instance_config_variables/extended.py",
]


def literal(node):
    """Read a constant, or None when the node is anything else."""
    if isinstance(node, ast.Constant):
        return node.value
    return None


def read_entry(node):
    """Turn one {key, value, category, is_encrypted} dict literal into a row."""
    entry = {}
    for key_node, value_node in zip(node.keys, node.values):
        name = literal(key_node)
        if name is None:
            return None
        if name == "value":
            # os.environ.get("NAME") or os.environ.get("NAME", "default")
            if not isinstance(value_node, ast.Call):
                return None
            env_name = literal(value_node.args[0]) if value_node.args else None
            default = literal(value_node.args[1]) if len(value_node.args) > 1 else None
            entry["env"] = env_name or ""
            entry["default"] = "" if default is None else str(default)
        else:
            entry[name] = literal(value_node)
    return entry


rows = []
for source in SOURCES:
    if not os.path.exists(source):
        sys.exit(f"{source} is missing; run this from apps/api")
    tree = ast.parse(open(source).read())
    for node in ast.walk(tree):
        if not isinstance(node, ast.Dict):
            continue
        entry = read_entry(node)
        if not entry or "key" not in entry or entry.get("key") is None:
            continue
        rows.append((
            entry["key"],
            entry.get("env", ""),
            entry.get("default", ""),
            entry.get("category") or "",
            "1" if entry.get("is_encrypted") else "0",
        ))

if not rows:
    sys.exit("no configuration variables found")

print("# The instance configuration variables apps/api seeds, generated by apps/api-go/tools/generate_instance_config_variables.py.")
print("# Columns: key\tenvironment variable\tdefault\tcategory\tencrypted. Do not edit by hand.")
for row in rows:
    print("\t".join(row))
