#!/usr/bin/env python
"""Emit the ORDER BY and the joins Django renders for a plain work item ordering.

The cycle's work item list orders with a bare `.order_by()` rather than through the `Case` machinery the project list uses, so the same parameter means something different here: `priority` sorts the words alphabetically rather than by severity, and the three orderings that reach through a multi-valued relation add joins that **repeat** a work item once per related row, because the queryset carries no `distinct()`.

Neither is visible in the view. The fixture records the clause and the number of joins so both are pinned.

Run from apps/api against a configured Django:

    python ../api-go/tools/generate_plain_issue_order_fixture.py > ../api-go/internal/externalapi/testdata/plain_issue_order_by.tsv
"""

import os
import sys

import django

sys.path.insert(0, os.getcwd())
django.setup()

from plane.db.models import Issue  # noqa: E402
from plane.utils.order_queryset import ISSUE_ORDER_BY_ALLOWLIST, sanitize_order_by  # noqa: E402

ALIASES = {"issues": "", "states": "state.", "users": "user.", "labels": "label.", "modules": "module."}


def rendered(value):
    order = sanitize_order_by(value, ISSUE_ORDER_BY_ALLOWLIST, "created_at")
    sql = str(Issue.issue_objects.all().order_by(order).query)
    clause = sql[sql.rindex(" ORDER BY ") + len(" ORDER BY ") :]
    for table, prefix in ALIASES.items():
        clause = clause.replace(f'"{table}".', prefix)
    # The manager itself joins states and projects, so the count above two is what the ordering added.
    return clause.replace('"', ""), sql.count("JOIN") - 2


def main():
    print(
        "# Ground truth for a plain work item ordering, generated by "
        "apps/api-go/tools/generate_plain_issue_order_fixture.py. Do not edit by hand."
    )
    print("# Each row is the order_by, the clause, and how many joins the ordering itself added.")
    for bare in sorted(ISSUE_ORDER_BY_ALLOWLIST):
        for value in (bare, f"-{bare}"):
            clause, joins = rendered(value)
            print(f"{value}\t{clause}\t{joins}")
    for value in ("", "--created_at", "project__name"):
        clause, joins = rendered(value)
        print(f"{value}\t{clause}\t{joins}")


if __name__ == "__main__":
    main()
