package auth

import "testing"

func TestDecryptDjangoFernetConfiguration(t *testing.T) {
	// Generated by apps/api/plane/license/utils/encryption.py's key
	// derivation and cryptography.Fernet at a fixed timestamp.
	encoded := "gAAAAABlU_EAYPIDhiowEyK9Aa4c833-9Z8Ge98X59NTUtL63oH6LelT3DWaPgalzsTk5vfbmt9-PGSJRNFcvpal0ZKsGGmHZRBC_ewq0PtKQ_REvfpgg30="
	value, err := decryptDjangoConfiguration(encoded, "pace-test-secret")
	if err != nil {
		t.Fatal(err)
	}
	if value != "oauth-client-secret" {
		t.Fatalf("decrypted value = %q", value)
	}
	if _, err := decryptDjangoConfiguration(encoded, "wrong-secret"); err == nil {
		t.Fatal("wrong key should fail authentication")
	}
}
