package worker

import (
	"context"
	_ "embed"
	"encoding/json"
	"fmt"
	"log/slog"
	"time"

	"gorm.io/gorm"
)

// SoftDeleteRelatedObjectsTask is plane.bgtasks.deletion_task.soft_delete_related_objects.
const SoftDeleteRelatedObjectsTask = "plane.bgtasks.deletion_task.soft_delete_related_objects"

// relationGraphJSON is generated by tools/generate_relation_graph.py from the
// Django models. soft_delete_related_objects walks that metadata at runtime;
// PostgreSQL cannot stand in for it, because Django creates its foreign keys
// without ON DELETE actions, so the catalog knows the graph but not whether a
// relation cascades or nulls.
//
//go:embed relation_graph.json
var relationGraphJSON []byte

type relationGraph struct {
	DjangoVersion string                `json:"django_version"`
	Models        map[string]modelGraph `json:"models"`
}

type modelGraph struct {
	Table       string `json:"table"`
	PrimaryKey  string `json:"primary_key"`
	SoftDeletes bool   `json:"soft_deletes"`
	// ClearsAuditUser is true for models whose save is BaseModel.save, which is
	// the one that blanks the audit columns when there is no current user.
	// Models that stop at AuditModel, such as ProjectIdentifier, keep theirs.
	ClearsAuditUser bool       `json:"clears_audit_user"`
	CreatedByColumn string     `json:"created_by_column"`
	UpdatedByColumn string     `json:"updated_by_column"`
	Relations       []relation `json:"relations"`
}

type relation struct {
	Accessor           string `json:"accessor"`
	OnDelete           string `json:"on_delete"`
	OneToOne           bool   `json:"one_to_one"`
	RelatedModel       string `json:"related_model"`
	RelatedTable       string `json:"related_table"`
	RelatedColumn      string `json:"related_column"`
	RelatedSoftDeletes bool   `json:"related_soft_deletes"`
}

func loadRelationGraph() (relationGraph, error) {
	var graph relationGraph
	if err := json.Unmarshal(relationGraphJSON, &graph); err != nil {
		return relationGraph{}, fmt.Errorf("decode relation graph: %w", err)
	}
	if len(graph.Models) == 0 {
		return relationGraph{}, fmt.Errorf("relation graph is empty")
	}
	return graph, nil
}

// DeletionTasks owns the cascade that follows a soft delete.
type DeletionTasks struct {
	db     *gorm.DB
	graph  relationGraph
	logger *slog.Logger
	clock  func() time.Time
	// maxDepth stops a cycle in the relation graph from recursing forever.
	// Django relies on the deleted_at guard for that; the same guard applies
	// here, and this is a second line of defence.
	maxDepth int
}

func NewDeletionTasks(db *gorm.DB, logger *slog.Logger) (*DeletionTasks, error) {
	graph, err := loadRelationGraph()
	if err != nil {
		return nil, err
	}
	if logger == nil {
		logger = slog.Default()
	}
	return &DeletionTasks{db: db, graph: graph, logger: logger, clock: time.Now, maxDepth: 12}, nil
}

func (tasks *DeletionTasks) Register(consumer *Consumer) {
	consumer.Register(SoftDeleteRelatedObjectsTask, tasks.softDeleteRelatedObjects)
}

func (tasks *DeletionTasks) softDeleteRelatedObjects(ctx context.Context, arguments []any, keywords map[string]any) error {
	appLabel := stringArgument(arguments, keywords, 0, "app_label")
	modelName := stringArgument(arguments, keywords, 1, "model_name")
	instancePK := stringArgument(arguments, keywords, 2, "instance_pk")
	return tasks.cascade(ctx, appLabel+"."+modelName, instancePK, 0)
}

func (tasks *DeletionTasks) cascade(ctx context.Context, modelKey, instancePK string, depth int) error {
	if depth > tasks.maxDepth {
		tasks.logger.Warn("soft delete cascade stopped at the depth limit", "model", modelKey, "pk", instancePK)
		return nil
	}
	model, known := tasks.graph.Models[modelKey]
	if !known {
		// Django's apps.get_model would raise here; log rather than retry.
		tasks.logger.Error("unknown model in the relation graph", "model", modelKey)
		return nil
	}
	// Django reads through all_objects so an already soft-deleted row is still
	// found and its children are still cascaded.
	var existing map[string]any
	err := tasks.db.WithContext(ctx).Table(model.Table).
		Where(model.PrimaryKey+" = ?", instancePK).Limit(1).Take(&existing).Error
	if err != nil {
		// DoesNotExist simply returns in Django.
		return nil
	}
	now := tasks.clock().UTC()

	for _, relation := range model.Relations {
		switch relation.OnDelete {
		case "DO_NOTHING":
			continue
		case "SET_NULL":
			if err := tasks.setNull(ctx, relation, instancePK); err != nil {
				// Django's bare except only wraps the cascade branch, but a
				// failure here would abort the whole task, so it is logged and
				// skipped the same way to keep the rest of the cascade running.
				tasks.logger.Error("clearing a relation failed", "relation", relation.Accessor, "error", err)
			}
		default:
			if err := tasks.cascadeRelation(ctx, relation, instancePK, now, depth); err != nil {
				tasks.logger.Error("cascading a relation failed", "relation", relation.Accessor, "error", err)
			}
		}
	}

	if model.SoftDeletes {
		return tasks.markDeleted(ctx, model, instancePK, now)
	}
	return nil
}

// setNull clears the pointing column. Django does this with a queryset update,
// which never calls save, so no timestamps or audit columns change.
func (tasks *DeletionTasks) setNull(ctx context.Context, relation relation, instancePK string) error {
	query := tasks.db.WithContext(ctx).Table(relation.RelatedTable).
		Where(relation.RelatedColumn+" = ?", instancePK)
	if relation.RelatedSoftDeletes {
		// The related manager is the soft-deleting one, so rows already deleted
		// are left alone.
		query = query.Where("deleted_at IS NULL")
	}
	return query.Update(relation.RelatedColumn, nil).Error
}

func (tasks *DeletionTasks) cascadeRelation(ctx context.Context, relation relation, instancePK string, now time.Time, depth int) error {
	if !relation.RelatedSoftDeletes {
		// Django checks hasattr(related_obj, "deleted_at") and skips otherwise,
		// so a related model without the column is left untouched.
		return nil
	}
	related, known := tasks.graph.Models[relation.RelatedModel]
	if !known {
		return fmt.Errorf("relation %s points at unknown model %s", relation.Accessor, relation.RelatedModel)
	}
	query := tasks.db.WithContext(ctx).Table(relation.RelatedTable).
		Where(relation.RelatedColumn+" = ? AND deleted_at IS NULL", instancePK)
	if relation.OneToOne {
		query = query.Limit(1)
	}
	var identifiers []string
	if err := query.Pluck(related.PrimaryKey, &identifiers).Error; err != nil {
		return err
	}
	for _, identifier := range identifiers {
		if err := tasks.markDeleted(ctx, related, identifier, now); err != nil {
			return err
		}
		if err := tasks.cascade(ctx, relation.RelatedModel, identifier, depth+1); err != nil {
			return err
		}
	}
	return nil
}

// markDeleted reproduces the row-level save Django performs. BaseModel.save
// reads the current user from crum, and a Celery worker has none, so created_by
// and updated_by are set to NULL on every row this touches. That is destructive
// and surprising, but it is what the Django task does today, and diverging
// would mean the same delete produced different data depending on which worker
// picked it up.
func (tasks *DeletionTasks) markDeleted(ctx context.Context, model modelGraph, instancePK string, now time.Time) error {
	updates := map[string]any{"deleted_at": now, "updated_at": now}
	if model.ClearsAuditUser {
		if model.CreatedByColumn != "" {
			updates[model.CreatedByColumn] = nil
		}
		if model.UpdatedByColumn != "" {
			updates[model.UpdatedByColumn] = nil
		}
	}
	return tasks.db.WithContext(ctx).Table(model.Table).
		Where(model.PrimaryKey+" = ? AND deleted_at IS NULL", instancePK).
		Updates(updates).Error
}
