package ydoc

import (
	"encoding/base64"
	"encoding/json"
	"os"
	"reflect"
	"testing"
)

// documentCase is one entry of the corpus in testdata/documents.json, generated by running real documents through the real editor with tools/generate_ydoc_fixture.mjs.
type documentCase struct {
	Name        string          `json:"name"`
	SourceHTML  string          `json:"source_html"`
	SourceTitle string          `json:"source_title"`
	Binary      string          `json:"binary"`
	ContentHTML string          `json:"content_html"`
	ContentJSON json.RawMessage `json:"content_json"`
	TitleJSON   json.RawMessage `json:"title_json"`
	TitleHTML   string          `json:"title_html"`
}

func loadCorpus(t *testing.T) []documentCase {
	t.Helper()
	raw, err := os.ReadFile("testdata/documents.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	var cases []documentCase
	if err := json.Unmarshal(raw, &cases); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}
	if len(cases) == 0 {
		t.Fatal("corpus is empty")
	}
	return cases
}

func (c documentCase) update(t *testing.T) []byte {
	t.Helper()
	update, err := base64.StdEncoding.DecodeString(c.Binary)
	if err != nil {
		t.Fatalf("decode binary: %v", err)
	}
	return update
}

// TestParseMatchesEditor is the whole point of the package: the same Yjs bytes have to come back as the same ProseMirror document here as they do in the editor.
func TestParseMatchesEditor(t *testing.T) {
	for _, testCase := range loadCorpus(t) {
		t.Run(testCase.Name, func(t *testing.T) {
			node, err := Parse(testCase.update(t))
			if err != nil {
				t.Fatalf("parse: %v", err)
			}
			got, err := node.JSON()
			if err != nil {
				t.Fatalf("marshal: %v", err)
			}
			// Compared as values rather than as text: both sides are stored as jsonb, where the order of an object's keys is not preserved anyway.
			if !reflect.DeepEqual(decodeJSON(t, got), decodeJSON(t, testCase.ContentJSON)) {
				t.Errorf("document differs\n go: %s\nwant: %s", got, testCase.ContentJSON)
			}
		})
	}
}

// TestTitleMatchesEditor covers the second fragment: a page's title is stored beside its body in the same update, as a document of its own.
func TestTitleMatchesEditor(t *testing.T) {
	for _, testCase := range loadCorpus(t) {
		t.Run(testCase.Name, func(t *testing.T) {
			node, err := ParseTitle(testCase.update(t))
			if err != nil {
				t.Fatalf("parse title: %v", err)
			}
			got, err := node.JSON()
			if err != nil {
				t.Fatalf("marshal: %v", err)
			}
			if !reflect.DeepEqual(decodeJSON(t, got), decodeJSON(t, testCase.TitleJSON)) {
				t.Errorf("title differs\n go: %s\nwant: %s", got, testCase.TitleJSON)
			}
			if text := node.TextContent(); text != testCase.SourceTitle {
				t.Errorf("title text = %q, want %q", text, testCase.SourceTitle)
			}
		})
	}
}

// TestSchemaCoversCorpus keeps the corpus honest: a schema entry nothing exercises is an entry nobody has checked.
func TestSchemaCoversCorpus(t *testing.T) {
	seenNodes := map[string]bool{}
	seenMarks := map[string]bool{}
	for _, testCase := range loadCorpus(t) {
		node, err := Parse(testCase.update(t))
		if err != nil {
			t.Fatalf("%s: parse: %v", testCase.Name, err)
		}
		walk(node, seenNodes, seenMarks)
	}
	for _, nodeType := range DocumentSchema.Nodes {
		if !seenNodes[nodeType.Name] {
			t.Errorf("no document in the corpus contains a %s node", nodeType.Name)
		}
	}
	for _, markType := range DocumentSchema.Marks {
		if !seenMarks[markType.Name] {
			t.Errorf("no document in the corpus contains a %s mark", markType.Name)
		}
	}
}

func walk(node Node, nodes, marks map[string]bool) {
	nodes[node.Type] = true
	for _, mark := range node.Marks {
		marks[mark.Type] = true
	}
	for _, child := range node.Content {
		walk(child, nodes, marks)
	}
}

func decodeJSON(t *testing.T, raw []byte) any {
	t.Helper()
	var value any
	if err := json.Unmarshal(raw, &value); err != nil {
		t.Fatalf("decode: %v", err)
	}
	return value
}
