package ydoc

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"strings"
)

// parseRulesJSON is the schema's parse rules, generated by tools/generate_parse_rules.mjs. It carries everything about a rule that is data; the functions a rule may also carry are ported by hand and registered by the type and attribute they belong to.
//
//go:embed parse_rules.json
var parseRulesJSON []byte

// attributeReader says how one of a type's attributes is read off an element.
type attributeReader struct {
	Name string `json:"name"`
	// HasParseHTML marks an attribute whose reader is code rather than the element's attribute of the same name. Each one is ported by hand, and the generated file carries the JavaScript beside it so the two can be compared.
	HasParseHTML bool   `json:"has_parse_html"`
	ParseHTML    string `json:"parse_html"`
}

// ParseRule is one rule: an element or a style, and what it produces.
type ParseRule struct {
	// Owner is the node or mark type that declared the rule and OwnerIndex its position among that type's own rules. Sorting mixes the types together, so this is how a hand-ported function is matched back to the rule it came from — and it is not the same as the type the rule produces, because a rule that only clears a mark produces nothing.
	Owner      string `json:"owner"`
	OwnerIndex int    `json:"owner_index"`

	Tag   string            `json:"tag"`
	Style string            `json:"style"`
	Node  string            `json:"node"`
	Mark  string            `json:"mark"`
	Reads []attributeReader `json:"reads"`

	Priority           *int           `json:"priority"`
	Context            string         `json:"context"`
	Ignore             bool           `json:"ignore"`
	Skip               bool           `json:"skip"`
	CloseParent        bool           `json:"close_parent"`
	Consuming          *bool          `json:"consuming"`
	PreserveWhitespace any            `json:"preserve_whitespace"`
	Attrs              map[string]any `json:"attrs"`

	HasGetAttrs       bool `json:"has_get_attrs"`
	HasClearMark      bool `json:"has_clear_mark"`
	HasContentElement bool `json:"has_content_element"`
	HasGetContent     bool `json:"has_get_content"`

	// compiled is the parsed Tag, and styleProperty and styleValue the two halves of a style rule's test.
	compiled      selector
	styleProperty string
	styleValue    string
	hasStyleValue bool
}

// baseRule is a rule as its extension declared it, before Tiptap wrapped it in an attribute reader. It exists so the JavaScript of every hand-ported function is recorded beside the port.
type baseRule struct {
	Owner     string         `json:"owner"`
	Index     int            `json:"index"`
	Tag       string         `json:"tag"`
	Style     string         `json:"style"`
	Attrs     map[string]any `json:"attrs"`
	GetAttrs  string         `json:"get_attrs"`
	ClearMark string         `json:"clear_mark"`
}

// ParseRules is the whole table.
type ParseRules struct {
	Rules []ParseRule `json:"rules"`
	Base  []baseRule  `json:"base_rules"`
	// MatchedStyles is the style properties any rule mentions. The parser looks up only these rather than walking every declaration an element carries.
	MatchedStyles []string `json:"matched_styles"`
	// NormalizeLists is true when no list type in this schema can hold itself, in which case a list nested straight inside another is first moved into the list item above it.
	NormalizeLists bool `json:"normalize_lists"`

	tagRules   []int
	styleRules []int
}

// DocumentParseRules is the document editor's rule table.
var DocumentParseRules = mustLoadParseRules()

func mustLoadParseRules() *ParseRules {
	var table ParseRules
	if err := json.Unmarshal(parseRulesJSON, &table); err != nil {
		panic(fmt.Sprintf("ydoc: parse_rules.json is not readable: %v", err))
	}
	for i := range table.Rules {
		rule := &table.Rules[i]
		switch {
		case rule.Tag != "":
			compiled, err := parseSelector(rule.Tag)
			if err != nil {
				panic(fmt.Sprintf("ydoc: %v", err))
			}
			rule.compiled = compiled
			table.tagRules = append(table.tagRules, i)
		case rule.Style != "":
			property, value, found := strings.Cut(rule.Style, "=")
			rule.styleProperty = property
			rule.styleValue = value
			rule.hasStyleValue = found
			table.styleRules = append(table.styleRules, i)
		}
	}
	return &table
}

// preserveWhitespaceSetting reads the rule's whitespace instruction: whether it is set at all, whether it is on, and whether it is the "full" kind that keeps newlines as newlines.
func (r *ParseRule) preserveWhitespaceSetting() (set bool, on bool, full bool) {
	switch value := r.PreserveWhitespace.(type) {
	case nil:
		return false, false, false
	case bool:
		return true, value, false
	case string:
		return true, true, value == "full"
	default:
		return false, false, false
	}
}
