// Package ydoc rebuilds a page's ProseMirror document from the Yjs update the collaborative editor stores.
//
// A Plane page lives as a Yjs document: an XML fragment named "default" holding the body, and a second one named "title". The live service converts that fragment back into a ProseMirror document every time it persists a page, and the API stores the result as description_json. This package is the Go side of that conversion.
package ydoc

import (
	_ "embed"
	"encoding/json"
	"fmt"
)

// schemaJSON is the document editor's schema, generated by tools/generate_ydoc_schema.mjs from the same extension list the editor builds its schema from. Regenerate it whenever an extension is added, removed or reordered.
//
//go:embed schema.json
var schemaJSON []byte

// Attribute is one declared attribute of a node or mark type.
//
// Three states, not two. An attribute without a default has to be carried by the document, and ProseMirror rejects a node that omits one. An attribute defaulting to undefined is satisfied without the document carrying it, but then holds no value at all and vanishes from the node's JSON — which is not the same as defaulting to null, where a null is stored and serialised.
type Attribute struct {
	HasDefault       bool `json:"has_default"`
	DefaultUndefined bool `json:"default_is_undefined"`
	Default          any  `json:"default"`
}

// NodeType is one node type in the schema. A leaf node may not have a content hole in its rendered spec, and an inline one is told so when a mark wraps it.
type NodeType struct {
	Name     string               `json:"name"`
	IsText   bool                 `json:"is_text"`
	IsLeaf   bool                 `json:"is_leaf"`
	IsInline bool                 `json:"is_inline"`
	Attrs    map[string]Attribute `json:"attrs"`
}

// MarkType is one mark type in the schema. Its position in Schema.Marks is its rank, which is the order ProseMirror sorts a text node's marks into. A mark that is not spanning opens a fresh element for each text node rather than wrapping a run of them.
type MarkType struct {
	Name     string               `json:"name"`
	Spanning bool                 `json:"spanning"`
	Attrs    map[string]Attribute `json:"attrs"`
}

// Schema is the document editor's ProseMirror schema, reduced to what rebuilding a document needs: the attributes of every type, and the order the marks were registered in.
type Schema struct {
	TopNode string     `json:"top_node"`
	Nodes   []NodeType `json:"nodes"`
	Marks   []MarkType `json:"marks"`

	nodesByName map[string]*NodeType
	marksByName map[string]*MarkType
	markRank    map[string]int
}

// DocumentSchema is the schema of the document editor — the one behind every page.
var DocumentSchema = mustLoadSchema()

func mustLoadSchema() *Schema {
	var schema Schema
	if err := json.Unmarshal(schemaJSON, &schema); err != nil {
		panic(fmt.Sprintf("ydoc: schema.json is not readable: %v", err))
	}
	schema.nodesByName = make(map[string]*NodeType, len(schema.Nodes))
	for i := range schema.Nodes {
		schema.nodesByName[schema.Nodes[i].Name] = &schema.Nodes[i]
	}
	schema.marksByName = make(map[string]*MarkType, len(schema.Marks))
	schema.markRank = make(map[string]int, len(schema.Marks))
	for i := range schema.Marks {
		schema.marksByName[schema.Marks[i].Name] = &schema.Marks[i]
		schema.markRank[schema.Marks[i].Name] = i
	}
	if _, ok := schema.nodesByName[schema.TopNode]; !ok {
		panic("ydoc: schema.json has no top node")
	}
	return &schema
}

// NodeType returns the named node type, or nil when the schema does not declare it.
func (s *Schema) NodeType(name string) *NodeType {
	return s.nodesByName[name]
}

// MarkType returns the named mark type, or nil when the schema does not declare it.
func (s *Schema) MarkType(name string) *MarkType {
	return s.marksByName[name]
}

// computeAttrs fills in the attributes a type declares, taking each one from the document when it carries it and from the schema otherwise. It mirrors ProseMirror's computeAttrs, including the parts that matter most here: an attribute the document does not carry is not absent, it is the schema's default, and attributes the document carries but the type does not declare are dropped.
//
// A nil result means the type declares no attributes and the node carries no attrs object at all. An empty non-nil result means it declares attributes but every one of them came out undefined, which still serialises as an empty object.
//
// nilIsAbsent says whether a value that decodes to nothing counts as absent. It does for a node, whose attributes are Yjs element attributes and are never written when null — so nothing there means JavaScript's undefined, and ProseMirror reads undefined as "not supplied". It does not for a mark, whose attributes are stored as one object handed over whole, nulls and all.
func computeAttrs(declared map[string]Attribute, given map[string]any, owner string, nilIsAbsent bool) (map[string]any, error) {
	if len(declared) == 0 {
		return nil, nil
	}
	built := make(map[string]any, len(declared))
	for name, attr := range declared {
		if value, ok := given[name]; ok && !(nilIsAbsent && value == nil) {
			built[name] = value
			continue
		}
		switch {
		case !attr.HasDefault:
			return nil, fmt.Errorf("no value supplied for attribute %s of %s", name, owner)
		case attr.DefaultUndefined:
			// Left out entirely: the node is valid without it and it serialises to nothing.
		default:
			built[name] = attr.Default
		}
	}
	return built, nil
}
