// Package ydoc rebuilds a page's ProseMirror document from the Yjs update the collaborative editor stores.
//
// A Plane page lives as a Yjs document: an XML fragment named "default" holding the body, and a second one named "title". The live service converts that fragment back into a ProseMirror document every time it persists a page, and the API stores the result as description_json. This package is the Go side of that conversion.
package ydoc

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"strings"
)

// schemaJSON is the document editor's schema, generated by tools/generate_ydoc_schema.mjs from the same extension list the editor builds its schema from. Regenerate it whenever an extension is added, removed or reordered.
//
//go:embed schema.json
var schemaJSON []byte

// schemaRichJSON is the rich text editor's schema — the same extensions without the work item embed, which is the only thing a page can hold that nothing else can.
//
//go:embed schema_rich.json
var schemaRichJSON []byte

// Attribute is one declared attribute of a node or mark type.
//
// Three states, not two. An attribute without a default has to be carried by the document, and ProseMirror rejects a node that omits one. An attribute defaulting to undefined is satisfied without the document carrying it, but then holds no value at all and vanishes from the node's JSON — which is not the same as defaulting to null, where a null is stored and serialised.
type Attribute struct {
	HasDefault       bool `json:"has_default"`
	DefaultUndefined bool `json:"default_is_undefined"`
	Default          any  `json:"default"`
}

// NodeType is one node type in the schema. A leaf node may not have a content hole in its rendered spec, and an inline one is told so when a mark wraps it.
//
// Content is the grammar for what the type may hold, compiled into ContentMatch when the schema is loaded. Groups are the names the expression of another type may refer to it by, so that "block+" reaches every type in the block group.
type NodeType struct {
	Name     string   `json:"name"`
	IsText   bool     `json:"is_text"`
	IsLeaf   bool     `json:"is_leaf"`
	IsInline bool     `json:"is_inline"`
	Groups   []string `json:"groups"`
	Content  string   `json:"content"`
	// Whitespace is "pre" for a type whose content keeps its spacing exactly as written, which is what tells the parser not to collapse it.
	Whitespace string  `json:"whitespace"`
	Marks      *string `json:"marks"`
	// AttrNames is the attributes in the order the type declares them, which is the order they are written into a Yjs document — and two documents whose attributes went in in different orders are different bytes.
	AttrNames []string             `json:"attr_names"`
	Attrs     map[string]Attribute `json:"attrs"`

	// ContentMatch is the compiled Content, and MarkSet the compiled Marks: nil when every mark is allowed, empty when none is.
	ContentMatch *ContentMatch `json:"-"`
	MarkSet      []*MarkType   `json:"-"`
}

func (t *NodeType) inGroup(name string) bool {
	for _, group := range t.Groups {
		if group == name {
			return true
		}
	}
	return false
}

// hasRequiredAttrs reports whether the type declares an attribute the document must supply, which makes it a type nothing can invent to fill a gap.
func (t *NodeType) hasRequiredAttrs() bool {
	for _, attr := range t.Attrs {
		if !attr.HasDefault {
			return true
		}
	}
	return false
}

// MarkType is one mark type in the schema. Its position in Schema.Marks is its rank, which is the order ProseMirror sorts a text node's marks into. A mark that is not spanning opens a fresh element for each text node rather than wrapping a run of them.
//
// Excludes names the marks this one cannot sit beside: absent means it excludes only itself, "_" means it excludes every other mark, and a list names them.
type MarkType struct {
	Name      string               `json:"name"`
	Spanning  bool                 `json:"spanning"`
	Groups    []string             `json:"groups"`
	Excludes  *string              `json:"excludes"`
	AttrNames []string             `json:"attr_names"`
	Attrs     map[string]Attribute `json:"attrs"`
}

func (t *MarkType) inGroup(name string) bool {
	for _, group := range t.Groups {
		if group == name {
			return true
		}
	}
	return false
}

// Schema is the document editor's ProseMirror schema, reduced to what rebuilding a document needs: the attributes of every type, and the order the marks were registered in.
type Schema struct {
	TopNode string     `json:"top_node"`
	Nodes   []NodeType `json:"nodes"`
	Marks   []MarkType `json:"marks"`

	nodesByName map[string]*NodeType
	marksByName map[string]*MarkType
	markRank    map[string]int
}

// DocumentSchema is the schema of the document editor — the one behind every page. RichTextSchema is the other one, which everything that is not a page is written with.
var (
	DocumentSchema = mustLoadSchema(schemaJSON, "schema.json")
	RichTextSchema = mustLoadSchema(schemaRichJSON, "schema_rich.json")
)

func mustLoadSchema(raw []byte, name string) *Schema {
	var schema Schema
	if err := json.Unmarshal(raw, &schema); err != nil {
		panic(fmt.Sprintf("ydoc: %s is not readable: %v", name, err))
	}
	schema.nodesByName = make(map[string]*NodeType, len(schema.Nodes))
	for i := range schema.Nodes {
		schema.nodesByName[schema.Nodes[i].Name] = &schema.Nodes[i]
	}
	schema.marksByName = make(map[string]*MarkType, len(schema.Marks))
	schema.markRank = make(map[string]int, len(schema.Marks))
	for i := range schema.Marks {
		schema.marksByName[schema.Marks[i].Name] = &schema.Marks[i]
		schema.markRank[schema.Marks[i].Name] = i
	}
	if _, ok := schema.nodesByName[schema.TopNode]; !ok {
		panic(fmt.Sprintf("ydoc: %s has no top node", name))
	}
	if err := schema.compile(); err != nil {
		panic(fmt.Sprintf("ydoc: %s will not compile: %v", name, err))
	}
	return &schema
}

// NodeType returns the named node type, or nil when the schema does not declare it.
func (s *Schema) NodeType(name string) *NodeType {
	return s.nodesByName[name]
}

// MarkType returns the named mark type, or nil when the schema does not declare it.
func (s *Schema) MarkType(name string) *MarkType {
	return s.marksByName[name]
}

// computeAttrs fills in the attributes a type declares, taking each one from the document when it carries it and from the schema otherwise. It mirrors ProseMirror's computeAttrs, including the parts that matter most here: an attribute the document does not carry is not absent, it is the schema's default, and attributes the document carries but the type does not declare are dropped.
//
// A nil result means the type declares no attributes and the node carries no attrs object at all. An empty non-nil result means it declares attributes but every one of them came out undefined, which still serialises as an empty object.
//
// nilIsAbsent says whether a value that decodes to nothing counts as absent. It does for a node, whose attributes are Yjs element attributes and are never written when null — so nothing there means JavaScript's undefined, and ProseMirror reads undefined as "not supplied". It does not for a mark, whose attributes are stored as one object handed over whole, nulls and all.
func computeAttrs(declared map[string]Attribute, given map[string]any, owner string, nilIsAbsent bool) (map[string]any, error) {
	if len(declared) == 0 {
		return nil, nil
	}
	built := make(map[string]any, len(declared))
	for name, attr := range declared {
		if value, ok := given[name]; ok && !(nilIsAbsent && value == nil) {
			built[name] = value
			continue
		}
		switch {
		case !attr.HasDefault:
			return nil, fmt.Errorf("no value supplied for attribute %s of %s", name, owner)
		case attr.DefaultUndefined:
			// Left out entirely: the node is valid without it and it serialises to nothing.
		default:
			built[name] = attr.Default
		}
	}
	return built, nil
}

// compile turns every content and marks expression into the machinery that matches against it. It runs once, when the schema is loaded, because an expression that will not compile is a broken schema rather than a broken document.
func (s *Schema) compile() error {
	for i := range s.Nodes {
		nodeType := &s.Nodes[i]
		match, err := parseContentExpression(nodeType.Content, s)
		if err != nil {
			return fmt.Errorf("content of %s: %w", nodeType.Name, err)
		}
		nodeType.ContentMatch = match
		nodeType.MarkSet = s.gatherMarks(nodeType)
	}
	return nil
}

// gatherMarks reads a type's marks expression.
//
// Nil means every mark is allowed and an empty set means none, and which of the two a type with no expression gets depends on what it holds: a type holding inline content allows every mark, and a type holding blocks allows none, because the marks belong to the text inside those blocks rather than to the block itself.
func (s *Schema) gatherMarks(nodeType *NodeType) []*MarkType {
	if nodeType.Marks == nil {
		if nodeType.ContentMatch.InlineContent() {
			return nil
		}
		return []*MarkType{}
	}
	expression := *nodeType.Marks
	if expression == "_" {
		return nil
	}
	if strings.TrimSpace(expression) == "" {
		return []*MarkType{}
	}
	var found []*MarkType
	for _, name := range strings.Fields(expression) {
		if markType := s.MarkType(name); markType != nil {
			found = append(found, markType)
			continue
		}
		for i := range s.Marks {
			markType := &s.Marks[i]
			if markType.inGroup(name) {
				found = append(found, markType)
			}
		}
	}
	return found
}
