-- django_celery_beat.0011_auto_20190508_0153, recorded by apps/api-go/tools/generate_migration_sql.py. Do not edit by hand.
CREATE TABLE "django_celery_beat_clockedschedule" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "clocked_time" timestamp with time zone NOT NULL, "enabled" boolean NOT NULL);
ALTER TABLE "django_celery_beat_periodictask" ADD COLUMN "clocked_id" integer NULL CONSTRAINT "django_celery_beat_p_clocked_id_47a69f82_fk_django_ce" REFERENCES "django_celery_beat_clockedschedule"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "django_celery_beat_p_clocked_id_47a69f82_fk_django_ce" IMMEDIATE;
CREATE INDEX "django_celery_beat_periodictask_clocked_id_47a69f82" ON "django_celery_beat_periodictask" ("clocked_id");
