package auth

import "testing"

func TestVerifyDjangoPBKDF2Password(t *testing.T) {
	// Generated by Django 5.2.15's PBKDF2PasswordHasher.
	encoded := "pbkdf2_sha256$1000$abcdefghijklmnopqrstuv$gyIKGYrTlRTAwlDBIge8uQnhX+Bk/ZRF8dGfP4K2Zjc="
	if !VerifyPassword("Correct-Horse-Battery-7", encoded) {
		t.Fatal("Go should verify a Django PBKDF2 password")
	}
	if VerifyPassword("wrong", encoded) {
		t.Fatal("wrong password should not verify")
	}
	if got := sessionAuthHash(encoded, "pace-test-secret"); got != "eb522fc5da69c78fdc1c3ff2a37988ddfe78f786175f965fd6f0fea97e1b2112" {
		t.Fatalf("session auth hash = %q", got)
	}
}

func TestEncodedPasswordRoundTrip(t *testing.T) {
	encoded := encodePassword("Pace-passphrase-9", "abcdefghijklmnopqrstuv", 1000)
	if !VerifyPassword("Pace-passphrase-9", encoded) {
		t.Fatal("encoded password should verify")
	}
}

func TestVerifyDjangoLegacyPasswordHashes(t *testing.T) {
	const password = "Legacy-Pace-Pass-7"
	for _, encoded := range []string{
		"pbkdf2_sha1$1000$abcdefghijklmnopqrstuv$IVuawE8hKHBD08clajkvRhbEYcQ=",
		"scrypt$1024$abcdefghijklmnopqrstuv$8$1$jcGf/XqNLutYu1qULQLWseOBbBLY/eOFepe6CTzLdxbyEEmcTAu8GeNfHTRAlnfFUCS0O8I3ovqp5UcXrBllHA==",
	} {
		if !VerifyPassword(password, encoded) {
			t.Fatalf("failed to verify %q", encoded)
		}
	}
}
