package auth

import "testing"

func TestVerifyDjangoPBKDF2Password(t *testing.T) {
	// Generated by Django 5.2.15's PBKDF2PasswordHasher.
	encoded := "pbkdf2_sha256$1000$abcdefghijklmnopqrstuv$gyIKGYrTlRTAwlDBIge8uQnhX+Bk/ZRF8dGfP4K2Zjc="
	if !VerifyPassword("Correct-Horse-Battery-7", encoded) {
		t.Fatal("Go should verify a Django PBKDF2 password")
	}
	if VerifyPassword("wrong", encoded) {
		t.Fatal("wrong password should not verify")
	}
	if got := sessionAuthHash(encoded, "pace-test-secret"); got != "eb522fc5da69c78fdc1c3ff2a37988ddfe78f786175f965fd6f0fea97e1b2112" {
		t.Fatalf("session auth hash = %q", got)
	}
}

func TestEncodedPasswordRoundTrip(t *testing.T) {
	encoded := encodePassword("Pace-passphrase-9", "abcdefghijklmnopqrstuv", 1000)
	if !VerifyPassword("Pace-passphrase-9", encoded) {
		t.Fatal("encoded password should verify")
	}
}

func TestVerifyDjangoLegacyPasswordHashes(t *testing.T) {
	const password = "Legacy-Pace-Pass-7"
	for _, encoded := range []string{
		"pbkdf2_sha1$1000$abcdefghijklmnopqrstuv$IVuawE8hKHBD08clajkvRhbEYcQ=",
		"scrypt$1024$abcdefghijklmnopqrstuv$8$1$jcGf/XqNLutYu1qULQLWseOBbBLY/eOFepe6CTzLdxbyEEmcTAu8GeNfHTRAlnfFUCS0O8I3ovqp5UcXrBllHA==",
	} {
		if !VerifyPassword(password, encoded) {
			t.Fatalf("failed to verify %q", encoded)
		}
	}
}

// TestNeedsRehashSpotsEverythingOlderThanTheCurrentScheme covers the predicate that decides whether a sign-in should re-derive the stored hash. Every algorithm VerifyPassword still accepts is one a password could have been stored under before, and none of them should survive a successful sign-in.
func TestNeedsRehashSpotsEverythingOlderThanTheCurrentScheme(t *testing.T) {
	current, err := HashPassword("Correct-Horse-Battery-7")
	if err != nil {
		t.Fatal(err)
	}
	if NeedsRehash(current) {
		t.Errorf("a hash this version just produced should not need rehashing: %s", current)
	}

	for _, stale := range []string{
		"pbkdf2_sha256$1000$abcdefghijklmnopqrstuv$gyIKGYrTlRTAwlDBIge8uQnhX+Bk/ZRF8dGfP4K2Zjc=",
		"pbkdf2_sha1$260000$salt$digest",
		"bcrypt_sha256$$2b$12$abcdefghijklmnopqrstuv",
		"scrypt$16384$salt$8$1$digest",
		"argon2$whatever",
		"not-a-hash",
		"",
		"pbkdf2_sha256$notanumber$salt$digest",
	} {
		if !NeedsRehash(stale) {
			t.Errorf("NeedsRehash(%q) = false, want true", stale)
		}
	}
}
