package auth

import (
	"testing"
	"time"
)

func TestDecodeDjangoSessionGoldenVector(t *testing.T) {
	codec, err := NewSessionCodec("pace-test-secret", nil)
	if err != nil {
		t.Fatal(err)
	}
	// Generated by django.core.signing.dumps() in Django 5.2.15 with the
	// custom SessionStore salt and compression enabled.
	encoded := ".eJxVjcEOgjAQRH_F9CyliAr06N3Eg_dmaRdaxdbQ6sXw7y6Eg2ZPs_Nm5sMUvJJVr4ijcoZJJoq6K3WJWbEr91kFrc4ag90iD8eqbgS0bPsba0Hf0c9ZcwPfB66DT6Nr-Yzw1Y38HAwOp5X9K7AQLaVpikbIMvh2GpXzXWDywxYGevSJoAto3FwxJuLcU4ExI8ZIRrGruKAr5oLwAOfpaVN6yjwfgobBhphkKYRg0_QFKYRQog:1x6GQU:Rz4iJyDHL8b0mMVb1Zmj4DrmhQZYuBGloF0O8DZZAHs"
	data, err := codec.Decode(encoded)
	if err != nil {
		t.Fatal(err)
	}
	if got := data["_auth_user_id"]; got != "018f3c3e-1234-7abc-9def-1234567890ab" {
		t.Fatalf("user id = %#v", got)
	}
	device := data["device_info"].(map[string]any)
	if device["domain"] != "http://localhost:3000" {
		t.Fatalf("device info = %#v", device)
	}
}

func TestGoSessionCanRoundTripAndRejectTampering(t *testing.T) {
	codec, err := NewSessionCodec("pace-test-secret", []string{"old-secret"})
	if err != nil {
		t.Fatal(err)
	}
	codec.clock = func() time.Time { return time.Unix(1_700_000_000, 0) }
	encoded, err := codec.Encode(map[string]any{"_auth_user_id": "user-id", "state": "oauth-state"})
	if err != nil {
		t.Fatal(err)
	}
	const djangoReadable = "eyJfYXV0aF91c2VyX2lkIjoidXNlci1pZCIsInN0YXRlIjoib2F1dGgtc3RhdGUifQ:1r31eq:HttMtlx23tezkq_7SOOseMYzPzT3k36hOY2WQBM0jUc"
	if encoded != djangoReadable {
		t.Fatalf("encoded session = %q", encoded)
	}
	data, err := codec.Decode(encoded)
	if err != nil {
		t.Fatal(err)
	}
	if data["state"] != "oauth-state" {
		t.Fatalf("decoded data = %#v", data)
	}
	encoded = encoded[:len(encoded)-1] + "x"
	if _, err := codec.Decode(encoded); err == nil {
		t.Fatal("tampered session should fail signature verification")
	}
}
