-- db.0011_auto_20221222_2357, recorded from the Django app this replaced.
CREATE TABLE "module" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "name" varchar(255) NOT NULL, "description" text NOT NULL, "description_text" jsonb NULL, "description_html" jsonb NULL, "start_date" date NULL, "target_date" date NULL, "status" varchar(20) NOT NULL);
ALTER TABLE "project" ADD COLUMN "icon" varchar(255) NULL;
ALTER TABLE "project_member" ADD COLUMN "default_props" jsonb DEFAULT '{"filters": {"priority": null, "state": null, "state_group": null, "assignees": null, "created_by": null, "labels": null, "start_date": null, "target_date": null, "subscriber": null}, "display_filters": {"group_by": null, "order_by": "-created_at", "type": null, "sub_issue": true, "show_empty_groups": true, "layout": "list", "calendar_date_range": ""}}'::jsonb NOT NULL;
ALTER TABLE "project_member" ALTER COLUMN "default_props" DROP DEFAULT;
ALTER TABLE "user" ADD COLUMN "my_issues_prop" jsonb NULL;
CREATE TABLE "module_member" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "created_by_id" uuid NULL, "member_id" uuid NOT NULL, "module_id" uuid NOT NULL, "project_id" uuid NOT NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
ALTER TABLE "module" ADD COLUMN "created_by_id" uuid NULL CONSTRAINT "module_created_by_id_ff7a5866_fk_user_id" REFERENCES "user"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "module_created_by_id_ff7a5866_fk_user_id" IMMEDIATE;
ALTER TABLE "module" ADD COLUMN "lead_id" uuid NULL CONSTRAINT "module_lead_id_04966630_fk_user_id" REFERENCES "user"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "module_lead_id_04966630_fk_user_id" IMMEDIATE;
ALTER TABLE "module" ADD COLUMN "project_id" uuid NOT NULL CONSTRAINT "module_project_id_da84b04f_fk_project_id" REFERENCES "project"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "module_project_id_da84b04f_fk_project_id" IMMEDIATE;
ALTER TABLE "module" ADD COLUMN "updated_by_id" uuid NULL CONSTRAINT "module_updated_by_id_72ab6d5c_fk_user_id" REFERENCES "user"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "module_updated_by_id_72ab6d5c_fk_user_id" IMMEDIATE;
ALTER TABLE "module" ADD COLUMN "workspace_id" uuid NOT NULL CONSTRAINT "module_workspace_id_0a826fef_fk_workspace_id" REFERENCES "workspace"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "module_workspace_id_0a826fef_fk_workspace_id" IMMEDIATE;
CREATE TABLE "module_issues" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "created_by_id" uuid NULL, "issue_id" uuid NOT NULL, "module_id" uuid NOT NULL, "project_id" uuid NOT NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
ALTER TABLE "module" ADD CONSTRAINT "module_name_project_id_c730d437_uniq" UNIQUE ("name", "project_id");
ALTER TABLE "module_member" ADD CONSTRAINT "module_member_module_id_member_id_1421c56c_uniq" UNIQUE ("module_id", "member_id");
ALTER TABLE "module_member" ADD CONSTRAINT "module_member_created_by_id_2ed84a65_fk_user_id" FOREIGN KEY ("created_by_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_member" ADD CONSTRAINT "module_member_member_id_928f473e_fk_user_id" FOREIGN KEY ("member_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_member" ADD CONSTRAINT "module_member_module_id_f00be7ef_fk_module_id" FOREIGN KEY ("module_id") REFERENCES "module" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_member" ADD CONSTRAINT "module_member_project_id_ec8d2376_fk_project_id" FOREIGN KEY ("project_id") REFERENCES "project" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_member" ADD CONSTRAINT "module_member_updated_by_id_a9046438_fk_user_id" FOREIGN KEY ("updated_by_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_member" ADD CONSTRAINT "module_member_workspace_id_f2f23c73_fk_workspace_id" FOREIGN KEY ("workspace_id") REFERENCES "workspace" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "module_member_created_by_id_2ed84a65" ON "module_member" ("created_by_id");
CREATE INDEX "module_member_member_id_928f473e" ON "module_member" ("member_id");
CREATE INDEX "module_member_module_id_f00be7ef" ON "module_member" ("module_id");
CREATE INDEX "module_member_project_id_ec8d2376" ON "module_member" ("project_id");
CREATE INDEX "module_member_updated_by_id_a9046438" ON "module_member" ("updated_by_id");
CREATE INDEX "module_member_workspace_id_f2f23c73" ON "module_member" ("workspace_id");
CREATE INDEX "module_created_by_id_ff7a5866" ON "module" ("created_by_id");
CREATE INDEX "module_lead_id_04966630" ON "module" ("lead_id");
CREATE INDEX "module_project_id_da84b04f" ON "module" ("project_id");
CREATE INDEX "module_updated_by_id_72ab6d5c" ON "module" ("updated_by_id");
CREATE INDEX "module_workspace_id_0a826fef" ON "module" ("workspace_id");
ALTER TABLE "module_issues" ADD CONSTRAINT "module_issues_module_id_issue_id_3322d0ea_uniq" UNIQUE ("module_id", "issue_id");
ALTER TABLE "module_issues" ADD CONSTRAINT "module_issues_created_by_id_de0b995a_fk_user_id" FOREIGN KEY ("created_by_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_issues" ADD CONSTRAINT "module_issues_issue_id_7caa908b_fk_issue_id" FOREIGN KEY ("issue_id") REFERENCES "issue" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_issues" ADD CONSTRAINT "module_issues_module_id_74e0ed5a_fk_module_id" FOREIGN KEY ("module_id") REFERENCES "module" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_issues" ADD CONSTRAINT "module_issues_project_id_59836d1e_fk_project_id" FOREIGN KEY ("project_id") REFERENCES "project" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_issues" ADD CONSTRAINT "module_issues_updated_by_id_46dbf724_fk_user_id" FOREIGN KEY ("updated_by_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "module_issues" ADD CONSTRAINT "module_issues_workspace_id_6bf85201_fk_workspace_id" FOREIGN KEY ("workspace_id") REFERENCES "workspace" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "module_issues_created_by_id_de0b995a" ON "module_issues" ("created_by_id");
CREATE INDEX "module_issues_issue_id_7caa908b" ON "module_issues" ("issue_id");
CREATE INDEX "module_issues_module_id_74e0ed5a" ON "module_issues" ("module_id");
CREATE INDEX "module_issues_project_id_59836d1e" ON "module_issues" ("project_id");
CREATE INDEX "module_issues_updated_by_id_46dbf724" ON "module_issues" ("updated_by_id");
CREATE INDEX "module_issues_workspace_id_6bf85201" ON "module_issues" ("workspace_id");
