-- db.0021_auto_20230223_0104, recorded from the Django app this replaced.
CREATE TABLE "github_repositories" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "name" varchar(500) NOT NULL, "url" varchar(200) NULL, "config" jsonb NOT NULL, "repository_id" bigint NOT NULL, "owner" varchar(500) NOT NULL, "created_by_id" uuid NULL, "project_id" uuid NOT NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
CREATE TABLE "integrations" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "title" varchar(400) NOT NULL, "provider" varchar(400) NOT NULL UNIQUE, "network" integer NOT NULL CHECK ("network" >= 0), "description" jsonb NOT NULL, "author" varchar(400) NOT NULL, "webhook_url" text NOT NULL, "webhook_secret" text NOT NULL, "redirect_url" text NOT NULL, "metadata" jsonb NOT NULL, "verified" boolean NOT NULL, "avatar_url" varchar(200) NULL, "created_by_id" uuid NULL, "updated_by_id" uuid NULL);
SET CONSTRAINTS "issue_activity_issue_id_807fbde4_fk_issue_id" IMMEDIATE; ALTER TABLE "issue_activities" DROP CONSTRAINT "issue_activity_issue_id_807fbde4_fk_issue_id";
ALTER TABLE "issue_activities" ALTER COLUMN "issue_id" DROP NOT NULL;
ALTER TABLE "issue_activities" ADD CONSTRAINT "issue_activities_issue_id_180e5662_fk_issues_id" FOREIGN KEY ("issue_id") REFERENCES "issues" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE "workspace_integrations" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "metadata" jsonb NOT NULL, "config" jsonb NOT NULL, "actor_id" uuid NOT NULL, "api_token_id" uuid NOT NULL, "created_by_id" uuid NULL, "integration_id" uuid NOT NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
CREATE TABLE "issue_links" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "title" varchar(255) NULL, "url" varchar(200) NOT NULL, "created_by_id" uuid NULL, "issue_id" uuid NOT NULL, "project_id" uuid NOT NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
CREATE TABLE "github_repository_syncs" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "credentials" jsonb NOT NULL, "actor_id" uuid NOT NULL, "created_by_id" uuid NULL, "label_id" uuid NULL, "project_id" uuid NOT NULL, "repository_id" uuid NOT NULL UNIQUE, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL, "workspace_integration_id" uuid NOT NULL);
CREATE TABLE "github_issue_syncs" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "repo_issue_id" bigint NOT NULL, "github_issue_id" bigint NOT NULL, "issue_url" varchar(200) NOT NULL, "created_by_id" uuid NULL, "issue_id" uuid NOT NULL, "project_id" uuid NOT NULL, "repository_sync_id" uuid NOT NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
CREATE TABLE "github_comment_syncs" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "repo_comment_id" bigint NOT NULL, "comment_id" uuid NOT NULL, "created_by_id" uuid NULL, "issue_sync_id" uuid NOT NULL, "project_id" uuid NOT NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
ALTER TABLE "github_repositories" ADD CONSTRAINT "github_repositories_created_by_id_104fa685_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "github_repositories" ADD CONSTRAINT "github_repositories_project_id_65c546bb_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "github_repositories" ADD CONSTRAINT "github_repositories_updated_by_id_8aa4d772_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "github_repositories" ADD CONSTRAINT "github_repositories_workspace_id_c4de7326_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "github_repositories_created_by_id_104fa685" ON "github_repositories" ("created_by_id");
CREATE INDEX "github_repositories_project_id_65c546bb" ON "github_repositories" ("project_id");
CREATE INDEX "github_repositories_updated_by_id_8aa4d772" ON "github_repositories" ("updated_by_id");
CREATE INDEX "github_repositories_workspace_id_c4de7326" ON "github_repositories" ("workspace_id");
ALTER TABLE "integrations" ADD CONSTRAINT "integrations_created_by_id_0b6edd52_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "integrations" ADD CONSTRAINT "integrations_updated_by_id_d6d00d15_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "integrations_provider_6537a106_like" ON "integrations" ("provider" varchar_pattern_ops);
CREATE INDEX "integrations_created_by_id_0b6edd52" ON "integrations" ("created_by_id");
CREATE INDEX "integrations_updated_by_id_d6d00d15" ON "integrations" ("updated_by_id");
ALTER TABLE "workspace_integrations" ADD CONSTRAINT "workspace_integrations_workspace_id_integration_fa041c22_uniq" UNIQUE ("workspace_id", "integration_id");
ALTER TABLE "workspace_integrations" ADD CONSTRAINT "workspace_integrations_actor_id_21619aa1_fk_users_id" FOREIGN KEY ("actor_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "workspace_integrations" ADD CONSTRAINT "workspace_integrations_api_token_id_bdb1759b_fk_api_tokens_id" FOREIGN KEY ("api_token_id") REFERENCES "api_tokens" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "workspace_integrations" ADD CONSTRAINT "workspace_integrations_created_by_id_37639c73_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "workspace_integrations" ADD CONSTRAINT "workspace_integratio_integration_id_6cb0aace_fk_integrati" FOREIGN KEY ("integration_id") REFERENCES "integrations" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "workspace_integrations" ADD CONSTRAINT "workspace_integrations_updated_by_id_fce01dcb_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "workspace_integrations" ADD CONSTRAINT "workspace_integrations_workspace_id_27ebeb6b_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "workspace_integrations_actor_id_21619aa1" ON "workspace_integrations" ("actor_id");
CREATE INDEX "workspace_integrations_api_token_id_bdb1759b" ON "workspace_integrations" ("api_token_id");
CREATE INDEX "workspace_integrations_created_by_id_37639c73" ON "workspace_integrations" ("created_by_id");
CREATE INDEX "workspace_integrations_integration_id_6cb0aace" ON "workspace_integrations" ("integration_id");
CREATE INDEX "workspace_integrations_updated_by_id_fce01dcb" ON "workspace_integrations" ("updated_by_id");
CREATE INDEX "workspace_integrations_workspace_id_27ebeb6b" ON "workspace_integrations" ("workspace_id");
ALTER TABLE "issue_links" ADD CONSTRAINT "issue_links_created_by_id_5e4aa092_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_links" ADD CONSTRAINT "issue_links_issue_id_7032881f_fk_issues_id" FOREIGN KEY ("issue_id") REFERENCES "issues" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_links" ADD CONSTRAINT "issue_links_project_id_63d6e9ce_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_links" ADD CONSTRAINT "issue_links_updated_by_id_a771cce4_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_links" ADD CONSTRAINT "issue_links_workspace_id_ff9038e7_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "issue_links_created_by_id_5e4aa092" ON "issue_links" ("created_by_id");
CREATE INDEX "issue_links_issue_id_7032881f" ON "issue_links" ("issue_id");
CREATE INDEX "issue_links_project_id_63d6e9ce" ON "issue_links" ("project_id");
CREATE INDEX "issue_links_updated_by_id_a771cce4" ON "issue_links" ("updated_by_id");
CREATE INDEX "issue_links_workspace_id_ff9038e7" ON "issue_links" ("workspace_id");
ALTER TABLE "github_repository_syncs" ADD CONSTRAINT "github_repository_syncs_project_id_repository_id_0f3705e6_uniq" UNIQUE ("project_id", "repository_id");
ALTER TABLE "github_repository_syncs" ADD CONSTRAINT "github_repository_syncs_actor_id_1fa689fe_fk_users_id" FOREIGN KEY ("actor_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "github_repository_syncs" ADD CONSTRAINT "github_repository_syncs_created_by_id_0df94495_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "github_repository_syncs" ADD CONSTRAINT "github_repository_syncs_label_id_eb1e9bd7_fk_labels_id" FOREIGN KEY ("label_id") REFERENCES "labels" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "github_repository_syncs" ADD CONSTRAINT "github_repository_syncs_project_id_e7e8291e_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "github_repository_syncs" ADD CONSTRAINT "github_repository_sy_repository_id_ead52404_fk_github_re" FOREIGN KEY ("repository_id") REFERENCES "github_repositories" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "github_repository_syncs" ADD CONSTRAINT "github_repository_syncs_updated_by_id_07e9d065_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "github_repository_syncs" ADD CONSTRAINT "github_repository_syncs_workspace_id_4a22a8b8_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "github_repository_syncs" ADD CONSTRAINT "github_repository_sy_workspace_integratio_62858398_fk_workspace" FOREIGN KEY ("workspace_integration_id") REFERENCES "workspace_integrations" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "github_repository_syncs_actor_id_1fa689fe" ON "github_repository_syncs" ("actor_id");
CREATE INDEX "github_repository_syncs_created_by_id_0df94495" ON "github_repository_syncs" ("created_by_id");
CREATE INDEX "github_repository_syncs_label_id_eb1e9bd7" ON "github_repository_syncs" ("label_id");
CREATE INDEX "github_repository_syncs_project_id_e7e8291e" ON "github_repository_syncs" ("project_id");
CREATE INDEX "github_repository_syncs_updated_by_id_07e9d065" ON "github_repository_syncs" ("updated_by_id");
CREATE INDEX "github_repository_syncs_workspace_id_4a22a8b8" ON "github_repository_syncs" ("workspace_id");
CREATE INDEX "github_repository_syncs_workspace_integration_id_62858398" ON "github_repository_syncs" ("workspace_integration_id");
ALTER TABLE "github_issue_syncs" ADD CONSTRAINT "github_issue_syncs_repository_sync_id_issue_id_4b34427e_uniq" UNIQUE ("repository_sync_id", "issue_id");
ALTER TABLE "github_issue_syncs" ADD CONSTRAINT "github_issue_syncs_created_by_id_d02b7c56_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "github_issue_syncs" ADD CONSTRAINT "github_issue_syncs_issue_id_450cb083_fk_issues_id" FOREIGN KEY ("issue_id") REFERENCES "issues" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "github_issue_syncs" ADD CONSTRAINT "github_issue_syncs_project_id_4609ad0c_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "github_issue_syncs" ADD CONSTRAINT "github_issue_syncs_repository_sync_id_ba0d4de4_fk_github_re" FOREIGN KEY ("repository_sync_id") REFERENCES "github_repository_syncs" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "github_issue_syncs" ADD CONSTRAINT "github_issue_syncs_updated_by_id_e9cd6f86_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "github_issue_syncs" ADD CONSTRAINT "github_issue_syncs_workspace_id_eae020ad_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "github_issue_syncs_created_by_id_d02b7c56" ON "github_issue_syncs" ("created_by_id");
CREATE INDEX "github_issue_syncs_issue_id_450cb083" ON "github_issue_syncs" ("issue_id");
CREATE INDEX "github_issue_syncs_project_id_4609ad0c" ON "github_issue_syncs" ("project_id");
CREATE INDEX "github_issue_syncs_repository_sync_id_ba0d4de4" ON "github_issue_syncs" ("repository_sync_id");
CREATE INDEX "github_issue_syncs_updated_by_id_e9cd6f86" ON "github_issue_syncs" ("updated_by_id");
CREATE INDEX "github_issue_syncs_workspace_id_eae020ad" ON "github_issue_syncs" ("workspace_id");
ALTER TABLE "github_comment_syncs" ADD CONSTRAINT "github_comment_syncs_issue_sync_id_comment_id_38c82e7b_uniq" UNIQUE ("issue_sync_id", "comment_id");
ALTER TABLE "github_comment_syncs" ADD CONSTRAINT "github_comment_syncs_comment_id_6feec6d1_fk_issue_comments_id" FOREIGN KEY ("comment_id") REFERENCES "issue_comments" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "github_comment_syncs" ADD CONSTRAINT "github_comment_syncs_created_by_id_b1ef2517_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "github_comment_syncs" ADD CONSTRAINT "github_comment_syncs_issue_sync_id_5e738eb5_fk_github_is" FOREIGN KEY ("issue_sync_id") REFERENCES "github_issue_syncs" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "github_comment_syncs" ADD CONSTRAINT "github_comment_syncs_project_id_6d199ace_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "github_comment_syncs" ADD CONSTRAINT "github_comment_syncs_updated_by_id_bb05c066_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "github_comment_syncs" ADD CONSTRAINT "github_comment_syncs_workspace_id_b54528c8_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "github_comment_syncs_comment_id_6feec6d1" ON "github_comment_syncs" ("comment_id");
CREATE INDEX "github_comment_syncs_created_by_id_b1ef2517" ON "github_comment_syncs" ("created_by_id");
CREATE INDEX "github_comment_syncs_issue_sync_id_5e738eb5" ON "github_comment_syncs" ("issue_sync_id");
CREATE INDEX "github_comment_syncs_project_id_6d199ace" ON "github_comment_syncs" ("project_id");
CREATE INDEX "github_comment_syncs_updated_by_id_bb05c066" ON "github_comment_syncs" ("updated_by_id");
CREATE INDEX "github_comment_syncs_workspace_id_b54528c8" ON "github_comment_syncs" ("workspace_id");
