-- db.0027_auto_20230409_0312, recorded from the Django app this replaced.
CREATE TABLE "estimates" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "name" varchar(255) NOT NULL, "description" text NOT NULL, "created_by_id" uuid NULL, "project_id" uuid NOT NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
ALTER TABLE "issues" DROP COLUMN "attachments" CASCADE;
ALTER TABLE "issues" ADD COLUMN "estimate_point" integer DEFAULT 0 NOT NULL;
ALTER TABLE "issues" ALTER COLUMN "estimate_point" DROP DEFAULT;
CREATE TABLE "issue_attachments" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "attributes" jsonb NOT NULL, "asset" varchar(100) NOT NULL, "created_by_id" uuid NULL, "issue_id" uuid NOT NULL, "project_id" uuid NOT NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
ALTER TABLE "projects" ADD COLUMN "estimate_id" uuid NULL CONSTRAINT "projects_estimate_id_85c7b2ac_fk_estimates_id" REFERENCES "estimates"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "projects_estimate_id_85c7b2ac_fk_estimates_id" IMMEDIATE;
CREATE TABLE "estimate_points" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "key" integer NOT NULL, "description" text NOT NULL, "value" varchar(20) NOT NULL, "created_by_id" uuid NULL, "estimate_id" uuid NOT NULL, "project_id" uuid NOT NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
ALTER TABLE "estimates" ADD CONSTRAINT "estimates_name_project_id_2b42c12c_uniq" UNIQUE ("name", "project_id");
ALTER TABLE "estimates" ADD CONSTRAINT "estimates_created_by_id_7e401493_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "estimates" ADD CONSTRAINT "estimates_project_id_7f195a41_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "estimates" ADD CONSTRAINT "estimates_updated_by_id_b3fcfb1d_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "estimates" ADD CONSTRAINT "estimates_workspace_id_718811eb_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "estimates_created_by_id_7e401493" ON "estimates" ("created_by_id");
CREATE INDEX "estimates_project_id_7f195a41" ON "estimates" ("project_id");
CREATE INDEX "estimates_updated_by_id_b3fcfb1d" ON "estimates" ("updated_by_id");
CREATE INDEX "estimates_workspace_id_718811eb" ON "estimates" ("workspace_id");
ALTER TABLE "issue_attachments" ADD CONSTRAINT "issue_attachments_created_by_id_87be05bb_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_attachments" ADD CONSTRAINT "issue_attachments_issue_id_0faf88bf_fk_issues_id" FOREIGN KEY ("issue_id") REFERENCES "issues" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_attachments" ADD CONSTRAINT "issue_attachments_project_id_a95fe706_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_attachments" ADD CONSTRAINT "issue_attachments_updated_by_id_47dceec1_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_attachments" ADD CONSTRAINT "issue_attachments_workspace_id_c456a532_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "issue_attachments_created_by_id_87be05bb" ON "issue_attachments" ("created_by_id");
CREATE INDEX "issue_attachments_issue_id_0faf88bf" ON "issue_attachments" ("issue_id");
CREATE INDEX "issue_attachments_project_id_a95fe706" ON "issue_attachments" ("project_id");
CREATE INDEX "issue_attachments_updated_by_id_47dceec1" ON "issue_attachments" ("updated_by_id");
CREATE INDEX "issue_attachments_workspace_id_c456a532" ON "issue_attachments" ("workspace_id");
CREATE INDEX "projects_estimate_id_85c7b2ac" ON "projects" ("estimate_id");
ALTER TABLE "estimate_points" ADD CONSTRAINT "estimate_points_value_estimate_id_9d6daac4_uniq" UNIQUE ("value", "estimate_id");
ALTER TABLE "estimate_points" ADD CONSTRAINT "estimate_points_created_by_id_d1b04bd9_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "estimate_points" ADD CONSTRAINT "estimate_points_estimate_id_4b4cb706_fk_estimates_id" FOREIGN KEY ("estimate_id") REFERENCES "estimates" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "estimate_points" ADD CONSTRAINT "estimate_points_project_id_ba9bcb2c_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "estimate_points" ADD CONSTRAINT "estimate_points_updated_by_id_a1da94e1_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "estimate_points" ADD CONSTRAINT "estimate_points_workspace_id_96fc4f92_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "estimate_points_created_by_id_d1b04bd9" ON "estimate_points" ("created_by_id");
CREATE INDEX "estimate_points_estimate_id_4b4cb706" ON "estimate_points" ("estimate_id");
CREATE INDEX "estimate_points_project_id_ba9bcb2c" ON "estimate_points" ("project_id");
CREATE INDEX "estimate_points_updated_by_id_a1da94e1" ON "estimate_points" ("updated_by_id");
CREATE INDEX "estimate_points_workspace_id_96fc4f92" ON "estimate_points" ("workspace_id");
