-- db.0040_projectmember_preferences_user_cover_image_and_more, recorded from the Django app this replaced.
ALTER TABLE "project_members" ADD COLUMN "preferences" jsonb DEFAULT '{"pages": {"block_display": true}, "navigation": {"default_tab": "work_items", "hide_in_more_menu": []}}'::jsonb NOT NULL;
ALTER TABLE "project_members" ALTER COLUMN "preferences" DROP DEFAULT;
ALTER TABLE "users" ADD COLUMN "cover_image" varchar(800) NULL;
CREATE TABLE "issue_reactions" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "reaction" varchar(20) NOT NULL, "actor_id" uuid NOT NULL, "created_by_id" uuid NULL, "issue_id" uuid NOT NULL, "project_id" uuid NOT NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
CREATE TABLE "comment_reactions" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "reaction" varchar(20) NOT NULL, "actor_id" uuid NOT NULL, "comment_id" uuid NOT NULL, "created_by_id" uuid NULL, "project_id" uuid NOT NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
ALTER TABLE "projects" ALTER COLUMN "identifier" TYPE varchar(12);
ALTER TABLE "project_identifiers" ALTER COLUMN "name" TYPE varchar(12);
ALTER TABLE "issue_reactions" ADD CONSTRAINT "issue_reactions_issue_id_actor_id_reaction_4751a642_uniq" UNIQUE ("issue_id", "actor_id", "reaction");
ALTER TABLE "issue_reactions" ADD CONSTRAINT "issue_reactions_actor_id_5f5b8303_fk_users_id" FOREIGN KEY ("actor_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_reactions" ADD CONSTRAINT "issue_reactions_created_by_id_3953b7de_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_reactions" ADD CONSTRAINT "issue_reactions_issue_id_2c324bae_fk_issues_id" FOREIGN KEY ("issue_id") REFERENCES "issues" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_reactions" ADD CONSTRAINT "issue_reactions_project_id_8708ecaf_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_reactions" ADD CONSTRAINT "issue_reactions_updated_by_id_4069af90_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "issue_reactions" ADD CONSTRAINT "issue_reactions_workspace_id_bd8d7550_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "issue_reactions_actor_id_5f5b8303" ON "issue_reactions" ("actor_id");
CREATE INDEX "issue_reactions_created_by_id_3953b7de" ON "issue_reactions" ("created_by_id");
CREATE INDEX "issue_reactions_issue_id_2c324bae" ON "issue_reactions" ("issue_id");
CREATE INDEX "issue_reactions_project_id_8708ecaf" ON "issue_reactions" ("project_id");
CREATE INDEX "issue_reactions_updated_by_id_4069af90" ON "issue_reactions" ("updated_by_id");
CREATE INDEX "issue_reactions_workspace_id_bd8d7550" ON "issue_reactions" ("workspace_id");
ALTER TABLE "comment_reactions" ADD CONSTRAINT "comment_reactions_comment_id_actor_id_reaction_523d21ad_uniq" UNIQUE ("comment_id", "actor_id", "reaction");
ALTER TABLE "comment_reactions" ADD CONSTRAINT "comment_reactions_actor_id_21219e9c_fk_users_id" FOREIGN KEY ("actor_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "comment_reactions" ADD CONSTRAINT "comment_reactions_comment_id_87c59446_fk_issue_comments_id" FOREIGN KEY ("comment_id") REFERENCES "issue_comments" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "comment_reactions" ADD CONSTRAINT "comment_reactions_created_by_id_9aeb43c4_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "comment_reactions" ADD CONSTRAINT "comment_reactions_project_id_ab9114b4_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "comment_reactions" ADD CONSTRAINT "comment_reactions_updated_by_id_c74c9bbd_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "comment_reactions" ADD CONSTRAINT "comment_reactions_workspace_id_b614ca4f_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "comment_reactions_actor_id_21219e9c" ON "comment_reactions" ("actor_id");
CREATE INDEX "comment_reactions_comment_id_87c59446" ON "comment_reactions" ("comment_id");
CREATE INDEX "comment_reactions_created_by_id_9aeb43c4" ON "comment_reactions" ("created_by_id");
CREATE INDEX "comment_reactions_project_id_ab9114b4" ON "comment_reactions" ("project_id");
CREATE INDEX "comment_reactions_updated_by_id_c74c9bbd" ON "comment_reactions" ("updated_by_id");
CREATE INDEX "comment_reactions_workspace_id_b614ca4f" ON "comment_reactions" ("workspace_id");
