-- db.0047_webhook_apitoken_description_apitoken_expired_at_and_more, recorded from the Django app this replaced.
CREATE TABLE "webhooks" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "url" varchar(200) NOT NULL, "is_active" boolean NOT NULL, "secret_key" varchar(255) NOT NULL, "project" boolean NOT NULL, "issue" boolean NOT NULL, "module" boolean NOT NULL, "cycle" boolean NOT NULL, "issue_comment" boolean NOT NULL, "created_by_id" uuid NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
ALTER TABLE "api_tokens" ADD COLUMN "description" text DEFAULT '' NOT NULL;
ALTER TABLE "api_tokens" ALTER COLUMN "description" DROP DEFAULT;
ALTER TABLE "api_tokens" ADD COLUMN "expired_at" timestamp with time zone NULL;
ALTER TABLE "api_tokens" ADD COLUMN "is_active" boolean DEFAULT true NOT NULL;
ALTER TABLE "api_tokens" ALTER COLUMN "is_active" DROP DEFAULT;
ALTER TABLE "api_tokens" ADD COLUMN "last_used" timestamp with time zone NULL;
ALTER TABLE "project_members" ADD COLUMN "is_active" boolean DEFAULT true NOT NULL;
ALTER TABLE "project_members" ALTER COLUMN "is_active" DROP DEFAULT;
ALTER TABLE "workspace_members" ADD COLUMN "is_active" boolean DEFAULT true NOT NULL;
ALTER TABLE "workspace_members" ALTER COLUMN "is_active" DROP DEFAULT;
CREATE TABLE "webhook_logs" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "event_type" varchar(255) NULL, "request_method" varchar(10) NULL, "request_headers" text NULL, "request_body" text NULL, "response_status" text NULL, "response_headers" text NULL, "response_body" text NULL, "retry_count" smallint NOT NULL CHECK ("retry_count" >= 0), "created_by_id" uuid NULL, "updated_by_id" uuid NULL, "webhook_id" uuid NOT NULL, "workspace_id" uuid NOT NULL);
CREATE TABLE "api_activity_logs" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "token_identifier" varchar(255) NOT NULL, "path" varchar(255) NOT NULL, "method" varchar(10) NOT NULL, "query_params" text NULL, "headers" text NULL, "body" text NULL, "response_code" integer NOT NULL CHECK ("response_code" >= 0), "response_body" text NULL, "ip_address" inet NULL, "user_agent" varchar(512) NULL, "created_by_id" uuid NULL, "updated_by_id" uuid NULL);
ALTER TABLE "webhooks" ADD CONSTRAINT "webhooks_workspace_id_url_9e8012ba_uniq" UNIQUE ("workspace_id", "url");
ALTER TABLE "webhooks" ADD CONSTRAINT "webhooks_created_by_id_25aca1b0_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "webhooks" ADD CONSTRAINT "webhooks_updated_by_id_ea35154e_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "webhooks" ADD CONSTRAINT "webhooks_workspace_id_da5865d7_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "webhooks_created_by_id_25aca1b0" ON "webhooks" ("created_by_id");
CREATE INDEX "webhooks_updated_by_id_ea35154e" ON "webhooks" ("updated_by_id");
CREATE INDEX "webhooks_workspace_id_da5865d7" ON "webhooks" ("workspace_id");
ALTER TABLE "webhook_logs" ADD CONSTRAINT "webhook_logs_created_by_id_71e7bc38_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "webhook_logs" ADD CONSTRAINT "webhook_logs_updated_by_id_3d9bad04_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "webhook_logs" ADD CONSTRAINT "webhook_logs_webhook_id_53707b3d_fk_webhooks_id" FOREIGN KEY ("webhook_id") REFERENCES "webhooks" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "webhook_logs" ADD CONSTRAINT "webhook_logs_workspace_id_ffcd0e31_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "webhook_logs_created_by_id_71e7bc38" ON "webhook_logs" ("created_by_id");
CREATE INDEX "webhook_logs_updated_by_id_3d9bad04" ON "webhook_logs" ("updated_by_id");
CREATE INDEX "webhook_logs_webhook_id_53707b3d" ON "webhook_logs" ("webhook_id");
CREATE INDEX "webhook_logs_workspace_id_ffcd0e31" ON "webhook_logs" ("workspace_id");
ALTER TABLE "api_activity_logs" ADD CONSTRAINT "api_activity_logs_created_by_id_7f5c4ca8_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "api_activity_logs" ADD CONSTRAINT "api_activity_logs_updated_by_id_9ba0d417_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "api_activity_logs_created_by_id_7f5c4ca8" ON "api_activity_logs" ("created_by_id");
CREATE INDEX "api_activity_logs_updated_by_id_9ba0d417" ON "api_activity_logs" ("updated_by_id");
