-- db.0074_deploy_board_and_project_issues, recorded from the Django app this replaced.
ALTER TABLE "deploy_boards" ADD COLUMN "is_activity_enabled" boolean DEFAULT true NOT NULL;
ALTER TABLE "deploy_boards" ALTER COLUMN "is_activity_enabled" DROP DEFAULT;
ALTER TABLE "file_assets" ADD COLUMN "is_archived" boolean DEFAULT false NOT NULL;
ALTER TABLE "file_assets" ALTER COLUMN "is_archived" DROP DEFAULT;
ALTER TABLE "user_favorites" ALTER COLUMN "sequence" TYPE double precision USING "sequence"::double precision;
CREATE TABLE "project_issue_types" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "deleted_at" timestamp with time zone NULL, "id" uuid NOT NULL PRIMARY KEY, "level" integer NOT NULL CHECK ("level" >= 0), "is_default" boolean NOT NULL);
DROP INDEX IF EXISTS "issue_type_unique_name_project_when_deleted_at_null";
ALTER TABLE "issue_types" DROP CONSTRAINT "issue_types_project_id_name_deleted_at_caa8a8cc_uniq";
ALTER TABLE "issue_types" ADD CONSTRAINT "issue_types_workspace_id_name_deleted_at_525d680f_uniq" UNIQUE ("workspace_id", "name", "deleted_at");
CREATE UNIQUE INDEX "issue_type_unique_name_workspace_when_deleted_at_null" ON "issue_types" ("name", "workspace_id") WHERE "deleted_at" IS NULL;
ALTER TABLE "project_issue_types" ADD COLUMN "created_by_id" uuid NULL CONSTRAINT "project_issue_types_created_by_id_049cecfd_fk_users_id" REFERENCES "users"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "project_issue_types_created_by_id_049cecfd_fk_users_id" IMMEDIATE;
ALTER TABLE "project_issue_types" ADD COLUMN "issue_type_id" uuid NOT NULL CONSTRAINT "project_issue_types_issue_type_id_9494de9f_fk_issue_types_id" REFERENCES "issue_types"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "project_issue_types_issue_type_id_9494de9f_fk_issue_types_id" IMMEDIATE;
ALTER TABLE "project_issue_types" ADD COLUMN "project_id" uuid NOT NULL CONSTRAINT "project_issue_types_project_id_ef6e52e4_fk_projects_id" REFERENCES "projects"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "project_issue_types_project_id_ef6e52e4_fk_projects_id" IMMEDIATE;
ALTER TABLE "project_issue_types" ADD COLUMN "updated_by_id" uuid NULL CONSTRAINT "project_issue_types_updated_by_id_b5998397_fk_users_id" REFERENCES "users"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "project_issue_types_updated_by_id_b5998397_fk_users_id" IMMEDIATE;
ALTER TABLE "project_issue_types" ADD COLUMN "workspace_id" uuid NOT NULL CONSTRAINT "project_issue_types_workspace_id_ace3c5b5_fk_workspaces_id" REFERENCES "workspaces"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "project_issue_types_workspace_id_ace3c5b5_fk_workspaces_id" IMMEDIATE;
ALTER TABLE "issue_types" DROP COLUMN "is_default" CASCADE;
SET CONSTRAINTS "issue_types_project_id_a040d097_fk_projects_id" IMMEDIATE; ALTER TABLE "issue_types" DROP CONSTRAINT "issue_types_project_id_a040d097_fk_projects_id";
ALTER TABLE "issue_types" DROP COLUMN "project_id" CASCADE;
ALTER TABLE "issue_types" DROP COLUMN "sort_order" CASCADE;
ALTER TABLE "issue_types" DROP COLUMN "weight" CASCADE;
CREATE UNIQUE INDEX "project_issue_type_unique_project_issue_type_when_deleted_at_null" ON "project_issue_types" ("project_id", "issue_type_id") WHERE "deleted_at" IS NULL;
ALTER TABLE "project_issue_types" ADD CONSTRAINT "project_issue_types_project_id_issue_type_id_2287e5dc_uniq" UNIQUE ("project_id", "issue_type_id", "deleted_at");
ALTER TABLE "issue_types" ADD COLUMN "is_default" boolean DEFAULT false NOT NULL;
ALTER TABLE "issue_types" ALTER COLUMN "is_default" DROP DEFAULT;
ALTER TABLE "issue_types" ADD COLUMN "level" integer DEFAULT 0 NOT NULL CHECK ("level" >= 0);
ALTER TABLE "issue_types" ALTER COLUMN "level" DROP DEFAULT;
ALTER TABLE "issue_types" DROP CONSTRAINT "issue_types_workspace_id_name_deleted_at_525d680f_uniq";
DROP INDEX IF EXISTS "issue_type_unique_name_workspace_when_deleted_at_null";
CREATE INDEX "project_issue_types_created_by_id_049cecfd" ON "project_issue_types" ("created_by_id");
CREATE INDEX "project_issue_types_issue_type_id_9494de9f" ON "project_issue_types" ("issue_type_id");
CREATE INDEX "project_issue_types_project_id_ef6e52e4" ON "project_issue_types" ("project_id");
CREATE INDEX "project_issue_types_updated_by_id_b5998397" ON "project_issue_types" ("updated_by_id");
CREATE INDEX "project_issue_types_workspace_id_ace3c5b5" ON "project_issue_types" ("workspace_id");
