-- db.0077_draftissue_cycle_user_timezone_project_user_timezone_and_more, recorded from the Django app this replaced.
CREATE TABLE "draft_issues" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "deleted_at" timestamp with time zone NULL, "id" uuid NOT NULL PRIMARY KEY, "name" varchar(255) NULL, "description" jsonb NOT NULL, "description_html" text NOT NULL, "description_stripped" text NULL, "description_binary" bytea NULL, "priority" varchar(30) NOT NULL, "start_date" date NULL, "target_date" date NULL, "sort_order" double precision NOT NULL, "completed_at" timestamp with time zone NULL, "external_source" varchar(255) NULL, "external_id" varchar(255) NULL);
ALTER TABLE "cycles" ADD COLUMN "timezone" varchar(255) DEFAULT 'UTC' NOT NULL;
ALTER TABLE "cycles" ALTER COLUMN "timezone" DROP DEFAULT;
ALTER TABLE "projects" ADD COLUMN "timezone" varchar(255) DEFAULT 'UTC' NOT NULL;
ALTER TABLE "projects" ALTER COLUMN "timezone" DROP DEFAULT;
ALTER TABLE "cycles" ALTER COLUMN "end_date" TYPE timestamp with time zone USING "end_date"::timestamp with time zone;
ALTER TABLE "cycles" ALTER COLUMN "start_date" TYPE timestamp with time zone USING "start_date"::timestamp with time zone;
CREATE TABLE "draft_issue_modules" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "deleted_at" timestamp with time zone NULL, "id" uuid NOT NULL PRIMARY KEY, "created_by_id" uuid NULL, "draft_issue_id" uuid NOT NULL, "module_id" uuid NOT NULL, "project_id" uuid NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
CREATE TABLE "draft_issue_labels" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "deleted_at" timestamp with time zone NULL, "id" uuid NOT NULL PRIMARY KEY, "created_by_id" uuid NULL, "draft_issue_id" uuid NOT NULL, "label_id" uuid NOT NULL, "project_id" uuid NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
CREATE TABLE "draft_issue_cycles" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "deleted_at" timestamp with time zone NULL, "id" uuid NOT NULL PRIMARY KEY, "created_by_id" uuid NULL, "cycle_id" uuid NOT NULL, "draft_issue_id" uuid NOT NULL UNIQUE, "project_id" uuid NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
CREATE TABLE "draft_issue_assignees" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "deleted_at" timestamp with time zone NULL, "id" uuid NOT NULL PRIMARY KEY, "assignee_id" uuid NOT NULL, "created_by_id" uuid NULL, "draft_issue_id" uuid NOT NULL, "project_id" uuid NULL, "updated_by_id" uuid NULL, "workspace_id" uuid NOT NULL);
ALTER TABLE "draft_issues" ADD COLUMN "created_by_id" uuid NULL CONSTRAINT "draft_issues_created_by_id_aedba72a_fk_users_id" REFERENCES "users"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "draft_issues_created_by_id_aedba72a_fk_users_id" IMMEDIATE;
ALTER TABLE "draft_issues" ADD COLUMN "estimate_point_id" uuid NULL CONSTRAINT "draft_issues_estimate_point_id_9e333189_fk_estimate_points_id" REFERENCES "estimate_points"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "draft_issues_estimate_point_id_9e333189_fk_estimate_points_id" IMMEDIATE;
ALTER TABLE "draft_issues" ADD COLUMN "parent_id" uuid NULL CONSTRAINT "draft_issues_parent_id_eee6ec32_fk_issues_id" REFERENCES "issues"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "draft_issues_parent_id_eee6ec32_fk_issues_id" IMMEDIATE;
ALTER TABLE "draft_issues" ADD COLUMN "project_id" uuid NULL CONSTRAINT "draft_issues_project_id_784a560c_fk_projects_id" REFERENCES "projects"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "draft_issues_project_id_784a560c_fk_projects_id" IMMEDIATE;
ALTER TABLE "draft_issues" ADD COLUMN "state_id" uuid NULL CONSTRAINT "draft_issues_state_id_94f28f5a_fk_states_id" REFERENCES "states"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "draft_issues_state_id_94f28f5a_fk_states_id" IMMEDIATE;
ALTER TABLE "draft_issues" ADD COLUMN "type_id" uuid NULL CONSTRAINT "draft_issues_type_id_7a62fe34_fk_issue_types_id" REFERENCES "issue_types"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "draft_issues_type_id_7a62fe34_fk_issue_types_id" IMMEDIATE;
ALTER TABLE "draft_issues" ADD COLUMN "updated_by_id" uuid NULL CONSTRAINT "draft_issues_updated_by_id_1ca3cd4e_fk_users_id" REFERENCES "users"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "draft_issues_updated_by_id_1ca3cd4e_fk_users_id" IMMEDIATE;
ALTER TABLE "draft_issues" ADD COLUMN "workspace_id" uuid NOT NULL CONSTRAINT "draft_issues_workspace_id_9d8512c8_fk_workspaces_id" REFERENCES "workspaces"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "draft_issues_workspace_id_9d8512c8_fk_workspaces_id" IMMEDIATE;
CREATE UNIQUE INDEX "module_draft_issue_unique_issue_module_when_deleted_at_null" ON "draft_issue_modules" ("draft_issue_id", "module_id") WHERE "deleted_at" IS NULL;
ALTER TABLE "draft_issue_modules" ADD CONSTRAINT "draft_issue_modules_draft_issue_id_module_id_634e1f1a_uniq" UNIQUE ("draft_issue_id", "module_id", "deleted_at");
CREATE UNIQUE INDEX "draft_issue_assignee_unique_issue_assignee_when_deleted_at_null" ON "draft_issue_assignees" ("draft_issue_id", "assignee_id") WHERE "deleted_at" IS NULL;
ALTER TABLE "draft_issue_assignees" ADD CONSTRAINT "draft_issue_assignees_draft_issue_id_assignee__7cd49721_uniq" UNIQUE ("draft_issue_id", "assignee_id", "deleted_at");
ALTER TABLE "cycles" ADD COLUMN "version" integer DEFAULT 1 NOT NULL;
ALTER TABLE "cycles" ALTER COLUMN "version" DROP DEFAULT;
-- RUN db.0077_draftissue_cycle_user_timezone_project_user_timezone_and_more.migrate_draft_issues
ALTER TABLE "draft_issue_modules" ADD CONSTRAINT "draft_issue_modules_created_by_id_95ec4247_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "draft_issue_modules" ADD CONSTRAINT "draft_issue_modules_draft_issue_id_eb470383_fk_draft_issues_id" FOREIGN KEY ("draft_issue_id") REFERENCES "draft_issues" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "draft_issue_modules" ADD CONSTRAINT "draft_issue_modules_module_id_4d3f477a_fk_modules_id" FOREIGN KEY ("module_id") REFERENCES "modules" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "draft_issue_modules" ADD CONSTRAINT "draft_issue_modules_project_id_c32eadab_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "draft_issue_modules" ADD CONSTRAINT "draft_issue_modules_updated_by_id_18548965_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "draft_issue_modules" ADD CONSTRAINT "draft_issue_modules_workspace_id_536c335a_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "draft_issue_modules_created_by_id_95ec4247" ON "draft_issue_modules" ("created_by_id");
CREATE INDEX "draft_issue_modules_draft_issue_id_eb470383" ON "draft_issue_modules" ("draft_issue_id");
CREATE INDEX "draft_issue_modules_module_id_4d3f477a" ON "draft_issue_modules" ("module_id");
CREATE INDEX "draft_issue_modules_project_id_c32eadab" ON "draft_issue_modules" ("project_id");
CREATE INDEX "draft_issue_modules_updated_by_id_18548965" ON "draft_issue_modules" ("updated_by_id");
CREATE INDEX "draft_issue_modules_workspace_id_536c335a" ON "draft_issue_modules" ("workspace_id");
ALTER TABLE "draft_issue_labels" ADD CONSTRAINT "draft_issue_labels_created_by_id_88217eef_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "draft_issue_labels" ADD CONSTRAINT "draft_issue_labels_draft_issue_id_339d4c2b_fk_draft_issues_id" FOREIGN KEY ("draft_issue_id") REFERENCES "draft_issues" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "draft_issue_labels" ADD CONSTRAINT "draft_issue_labels_label_id_b9b001a5_fk_labels_id" FOREIGN KEY ("label_id") REFERENCES "labels" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "draft_issue_labels" ADD CONSTRAINT "draft_issue_labels_project_id_16f9ba0a_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "draft_issue_labels" ADD CONSTRAINT "draft_issue_labels_updated_by_id_edac537c_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "draft_issue_labels" ADD CONSTRAINT "draft_issue_labels_workspace_id_489a9873_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "draft_issue_labels_created_by_id_88217eef" ON "draft_issue_labels" ("created_by_id");
CREATE INDEX "draft_issue_labels_draft_issue_id_339d4c2b" ON "draft_issue_labels" ("draft_issue_id");
CREATE INDEX "draft_issue_labels_label_id_b9b001a5" ON "draft_issue_labels" ("label_id");
CREATE INDEX "draft_issue_labels_project_id_16f9ba0a" ON "draft_issue_labels" ("project_id");
CREATE INDEX "draft_issue_labels_updated_by_id_edac537c" ON "draft_issue_labels" ("updated_by_id");
CREATE INDEX "draft_issue_labels_workspace_id_489a9873" ON "draft_issue_labels" ("workspace_id");
ALTER TABLE "draft_issue_cycles" ADD CONSTRAINT "draft_issue_cycles_created_by_id_e56335c8_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "draft_issue_cycles" ADD CONSTRAINT "draft_issue_cycles_cycle_id_b214e11f_fk_cycles_id" FOREIGN KEY ("cycle_id") REFERENCES "cycles" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "draft_issue_cycles" ADD CONSTRAINT "draft_issue_cycles_draft_issue_id_ed45e8a2_fk_draft_issues_id" FOREIGN KEY ("draft_issue_id") REFERENCES "draft_issues" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "draft_issue_cycles" ADD CONSTRAINT "draft_issue_cycles_project_id_dc5d1ff6_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "draft_issue_cycles" ADD CONSTRAINT "draft_issue_cycles_updated_by_id_518a23ab_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "draft_issue_cycles" ADD CONSTRAINT "draft_issue_cycles_workspace_id_4fd0aa0c_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "draft_issue_cycles_created_by_id_e56335c8" ON "draft_issue_cycles" ("created_by_id");
CREATE INDEX "draft_issue_cycles_cycle_id_b214e11f" ON "draft_issue_cycles" ("cycle_id");
CREATE INDEX "draft_issue_cycles_project_id_dc5d1ff6" ON "draft_issue_cycles" ("project_id");
CREATE INDEX "draft_issue_cycles_updated_by_id_518a23ab" ON "draft_issue_cycles" ("updated_by_id");
CREATE INDEX "draft_issue_cycles_workspace_id_4fd0aa0c" ON "draft_issue_cycles" ("workspace_id");
ALTER TABLE "draft_issue_assignees" ADD CONSTRAINT "draft_issue_assignees_assignee_id_9cc52f9d_fk_users_id" FOREIGN KEY ("assignee_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "draft_issue_assignees" ADD CONSTRAINT "draft_issue_assignees_created_by_id_c25d4bde_fk_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "draft_issue_assignees" ADD CONSTRAINT "draft_issue_assignee_draft_issue_id_70827be2_fk_draft_iss" FOREIGN KEY ("draft_issue_id") REFERENCES "draft_issues" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "draft_issue_assignees" ADD CONSTRAINT "draft_issue_assignees_project_id_c87dd571_fk_projects_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "draft_issue_assignees" ADD CONSTRAINT "draft_issue_assignees_updated_by_id_16dbb5e0_fk_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "draft_issue_assignees" ADD CONSTRAINT "draft_issue_assignees_workspace_id_e28a98e9_fk_workspaces_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "draft_issue_assignees_assignee_id_9cc52f9d" ON "draft_issue_assignees" ("assignee_id");
CREATE INDEX "draft_issue_assignees_created_by_id_c25d4bde" ON "draft_issue_assignees" ("created_by_id");
CREATE INDEX "draft_issue_assignees_draft_issue_id_70827be2" ON "draft_issue_assignees" ("draft_issue_id");
CREATE INDEX "draft_issue_assignees_project_id_c87dd571" ON "draft_issue_assignees" ("project_id");
CREATE INDEX "draft_issue_assignees_updated_by_id_16dbb5e0" ON "draft_issue_assignees" ("updated_by_id");
CREATE INDEX "draft_issue_assignees_workspace_id_e28a98e9" ON "draft_issue_assignees" ("workspace_id");
CREATE INDEX "draft_issues_created_by_id_aedba72a" ON "draft_issues" ("created_by_id");
CREATE INDEX "draft_issues_estimate_point_id_9e333189" ON "draft_issues" ("estimate_point_id");
CREATE INDEX "draft_issues_parent_id_eee6ec32" ON "draft_issues" ("parent_id");
CREATE INDEX "draft_issues_project_id_784a560c" ON "draft_issues" ("project_id");
CREATE INDEX "draft_issues_state_id_94f28f5a" ON "draft_issues" ("state_id");
CREATE INDEX "draft_issues_type_id_7a62fe34" ON "draft_issues" ("type_id");
CREATE INDEX "draft_issues_updated_by_id_1ca3cd4e" ON "draft_issues" ("updated_by_id");
CREATE INDEX "draft_issues_workspace_id_9d8512c8" ON "draft_issues" ("workspace_id");
