-- db.0078_fileasset_comment_fileasset_entity_type_and_more, recorded from the Django app this replaced.
ALTER TABLE "file_assets" ADD COLUMN "comment_id" uuid NULL CONSTRAINT "file_assets_comment_id_35d4ecaf_fk_issue_comments_id" REFERENCES "issue_comments"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "file_assets_comment_id_35d4ecaf_fk_issue_comments_id" IMMEDIATE;
ALTER TABLE "file_assets" ADD COLUMN "entity_type" varchar(255) NULL;
ALTER TABLE "file_assets" ADD COLUMN "external_id" varchar(255) NULL;
ALTER TABLE "file_assets" ADD COLUMN "external_source" varchar(255) NULL;
ALTER TABLE "file_assets" ADD COLUMN "is_uploaded" boolean DEFAULT false NOT NULL;
ALTER TABLE "file_assets" ALTER COLUMN "is_uploaded" DROP DEFAULT;
ALTER TABLE "file_assets" ADD COLUMN "issue_id" uuid NULL CONSTRAINT "file_assets_issue_id_cfe87d6c_fk_issues_id" REFERENCES "issues"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "file_assets_issue_id_cfe87d6c_fk_issues_id" IMMEDIATE;
ALTER TABLE "file_assets" ADD COLUMN "page_id" uuid NULL CONSTRAINT "file_assets_page_id_64c753d1_fk_pages_id" REFERENCES "pages"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "file_assets_page_id_64c753d1_fk_pages_id" IMMEDIATE;
ALTER TABLE "file_assets" ADD COLUMN "project_id" uuid NULL CONSTRAINT "file_assets_project_id_ebd5c0d8_fk_projects_id" REFERENCES "projects"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "file_assets_project_id_ebd5c0d8_fk_projects_id" IMMEDIATE;
ALTER TABLE "file_assets" ADD COLUMN "size" double precision DEFAULT 0.0 NOT NULL;
ALTER TABLE "file_assets" ALTER COLUMN "size" DROP DEFAULT;
ALTER TABLE "file_assets" ADD COLUMN "storage_metadata" jsonb DEFAULT '{}'::jsonb NULL;
ALTER TABLE "file_assets" ALTER COLUMN "storage_metadata" DROP DEFAULT;
ALTER TABLE "file_assets" ADD COLUMN "user_id" uuid NULL CONSTRAINT "file_assets_user_id_ce1818dc_fk_users_id" REFERENCES "users"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "file_assets_user_id_ce1818dc_fk_users_id" IMMEDIATE;
ALTER TABLE "projects" ADD COLUMN "cover_image_asset_id" uuid NULL CONSTRAINT "projects_cover_image_asset_id_e6636b92_fk_file_assets_id" REFERENCES "file_assets"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "projects_cover_image_asset_id_e6636b92_fk_file_assets_id" IMMEDIATE;
ALTER TABLE "users" ADD COLUMN "avatar_asset_id" uuid NULL CONSTRAINT "users_avatar_asset_id_50fa2043_fk_file_assets_id" REFERENCES "file_assets"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "users_avatar_asset_id_50fa2043_fk_file_assets_id" IMMEDIATE;
ALTER TABLE "users" ADD COLUMN "cover_image_asset_id" uuid NULL CONSTRAINT "users_cover_image_asset_id_b9679cbc_fk_file_assets_id" REFERENCES "file_assets"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "users_cover_image_asset_id_b9679cbc_fk_file_assets_id" IMMEDIATE;
ALTER TABLE "workspaces" ADD COLUMN "logo_asset_id" uuid NULL CONSTRAINT "workspaces_logo_asset_id_a784bb00_fk_file_assets_id" REFERENCES "file_assets"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "workspaces_logo_asset_id_a784bb00_fk_file_assets_id" IMMEDIATE;
ALTER TABLE "file_assets" ALTER COLUMN "asset" TYPE varchar(800);
ALTER TABLE "integrations" ALTER COLUMN "avatar_url" TYPE text USING "avatar_url"::text;
ALTER TABLE "projects" ALTER COLUMN "cover_image" TYPE text USING "cover_image"::text;
ALTER TABLE "workspaces" ALTER COLUMN "logo" TYPE text USING "logo"::text;
CREATE INDEX "file_assets_comment_id_35d4ecaf" ON "file_assets" ("comment_id");
CREATE INDEX "file_assets_issue_id_cfe87d6c" ON "file_assets" ("issue_id");
CREATE INDEX "file_assets_page_id_64c753d1" ON "file_assets" ("page_id");
CREATE INDEX "file_assets_project_id_ebd5c0d8" ON "file_assets" ("project_id");
CREATE INDEX "file_assets_user_id_ce1818dc" ON "file_assets" ("user_id");
CREATE INDEX "projects_cover_image_asset_id_e6636b92" ON "projects" ("cover_image_asset_id");
CREATE INDEX "users_avatar_asset_id_50fa2043" ON "users" ("avatar_asset_id");
CREATE INDEX "users_cover_image_asset_id_b9679cbc" ON "users" ("cover_image_asset_id");
CREATE INDEX "workspaces_logo_asset_id_a784bb00" ON "workspaces" ("logo_asset_id");
