-- db.0081_remove_globalview_created_by_and_more, recorded from the Django app this replaced.
SET CONSTRAINTS "global_views_created_by_id_14b7d95c_fk_users_id" IMMEDIATE; ALTER TABLE "global_views" DROP CONSTRAINT "global_views_created_by_id_14b7d95c_fk_users_id";
ALTER TABLE "global_views" DROP COLUMN "created_by_id" CASCADE;
SET CONSTRAINTS "global_views_updated_by_id_112e0281_fk_users_id" IMMEDIATE; ALTER TABLE "global_views" DROP CONSTRAINT "global_views_updated_by_id_112e0281_fk_users_id";
ALTER TABLE "global_views" DROP COLUMN "updated_by_id" CASCADE;
SET CONSTRAINTS "global_views_workspace_id_3c68eca7_fk_workspaces_id" IMMEDIATE; ALTER TABLE "global_views" DROP CONSTRAINT "global_views_workspace_id_3c68eca7_fk_workspaces_id";
ALTER TABLE "global_views" DROP COLUMN "workspace_id" CASCADE;
ALTER TABLE "view_favorites" DROP CONSTRAINT "view_favorites_view_id_user_id_3f287788_uniq";
SET CONSTRAINTS "view_favorites_created_by_id_dc6047f5_fk_users_id" IMMEDIATE; ALTER TABLE "view_favorites" DROP CONSTRAINT "view_favorites_created_by_id_dc6047f5_fk_users_id";
ALTER TABLE "view_favorites" DROP COLUMN "created_by_id" CASCADE;
SET CONSTRAINTS "view_favorites_project_id_241c521d_fk_projects_id" IMMEDIATE; ALTER TABLE "view_favorites" DROP CONSTRAINT "view_favorites_project_id_241c521d_fk_projects_id";
ALTER TABLE "view_favorites" DROP COLUMN "project_id" CASCADE;
SET CONSTRAINTS "view_favorites_updated_by_id_2418b683_fk_users_id" IMMEDIATE; ALTER TABLE "view_favorites" DROP CONSTRAINT "view_favorites_updated_by_id_2418b683_fk_users_id";
ALTER TABLE "view_favorites" DROP COLUMN "updated_by_id" CASCADE;
SET CONSTRAINTS "view_favorites_user_id_b1e94c2e_fk_users_id" IMMEDIATE; ALTER TABLE "view_favorites" DROP CONSTRAINT "view_favorites_user_id_b1e94c2e_fk_users_id";
ALTER TABLE "view_favorites" DROP COLUMN "user_id" CASCADE;
SET CONSTRAINTS "view_favorites_view_id_3111e893_fk_issue_views_id" IMMEDIATE; ALTER TABLE "view_favorites" DROP CONSTRAINT "view_favorites_view_id_3111e893_fk_issue_views_id";
ALTER TABLE "view_favorites" DROP COLUMN "view_id" CASCADE;
SET CONSTRAINTS "view_favorites_workspace_id_3dbdd2a2_fk_workspaces_id" IMMEDIATE; ALTER TABLE "view_favorites" DROP CONSTRAINT "view_favorites_workspace_id_3dbdd2a2_fk_workspaces_id";
ALTER TABLE "view_favorites" DROP COLUMN "workspace_id" CASCADE;
ALTER TABLE "module_favorites" DROP CONSTRAINT "module_favorites_module_id_user_id_5b36ecc1_uniq";
SET CONSTRAINTS "module_favorites_created_by_id_7f84820d_fk_users_id" IMMEDIATE; ALTER TABLE "module_favorites" DROP CONSTRAINT "module_favorites_created_by_id_7f84820d_fk_users_id";
ALTER TABLE "module_favorites" DROP COLUMN "created_by_id" CASCADE;
SET CONSTRAINTS "module_favorites_module_id_c4f0736b_fk_modules_id" IMMEDIATE; ALTER TABLE "module_favorites" DROP CONSTRAINT "module_favorites_module_id_c4f0736b_fk_modules_id";
ALTER TABLE "module_favorites" DROP COLUMN "module_id" CASCADE;
SET CONSTRAINTS "module_favorites_project_id_83d9d9e8_fk_projects_id" IMMEDIATE; ALTER TABLE "module_favorites" DROP CONSTRAINT "module_favorites_project_id_83d9d9e8_fk_projects_id";
ALTER TABLE "module_favorites" DROP COLUMN "project_id" CASCADE;
SET CONSTRAINTS "module_favorites_updated_by_id_2437fed0_fk_users_id" IMMEDIATE; ALTER TABLE "module_favorites" DROP CONSTRAINT "module_favorites_updated_by_id_2437fed0_fk_users_id";
ALTER TABLE "module_favorites" DROP COLUMN "updated_by_id" CASCADE;
SET CONSTRAINTS "module_favorites_user_id_c5b76375_fk_users_id" IMMEDIATE; ALTER TABLE "module_favorites" DROP CONSTRAINT "module_favorites_user_id_c5b76375_fk_users_id";
ALTER TABLE "module_favorites" DROP COLUMN "user_id" CASCADE;
SET CONSTRAINTS "module_favorites_workspace_id_65a4ac6f_fk_workspaces_id" IMMEDIATE; ALTER TABLE "module_favorites" DROP CONSTRAINT "module_favorites_workspace_id_65a4ac6f_fk_workspaces_id";
ALTER TABLE "module_favorites" DROP COLUMN "workspace_id" CASCADE;
SET CONSTRAINTS "page_blocks_created_by_id_696391e1_fk_users_id" IMMEDIATE; ALTER TABLE "page_blocks" DROP CONSTRAINT "page_blocks_created_by_id_696391e1_fk_users_id";
ALTER TABLE "page_blocks" DROP COLUMN "created_by_id" CASCADE;
SET CONSTRAINTS "page_blocks_issue_id_33cad86b_fk_issues_id" IMMEDIATE; ALTER TABLE "page_blocks" DROP CONSTRAINT "page_blocks_issue_id_33cad86b_fk_issues_id";
ALTER TABLE "page_blocks" DROP COLUMN "issue_id" CASCADE;
SET CONSTRAINTS "page_blocks_page_id_5f55e114_fk_pages_id" IMMEDIATE; ALTER TABLE "page_blocks" DROP CONSTRAINT "page_blocks_page_id_5f55e114_fk_pages_id";
ALTER TABLE "page_blocks" DROP COLUMN "page_id" CASCADE;
SET CONSTRAINTS "page_blocks_project_id_068d80f7_fk_projects_id" IMMEDIATE; ALTER TABLE "page_blocks" DROP CONSTRAINT "page_blocks_project_id_068d80f7_fk_projects_id";
ALTER TABLE "page_blocks" DROP COLUMN "project_id" CASCADE;
SET CONSTRAINTS "page_blocks_updated_by_id_1a29acb7_fk_users_id" IMMEDIATE; ALTER TABLE "page_blocks" DROP CONSTRAINT "page_blocks_updated_by_id_1a29acb7_fk_users_id";
ALTER TABLE "page_blocks" DROP COLUMN "updated_by_id" CASCADE;
SET CONSTRAINTS "page_blocks_workspace_id_b051825d_fk_workspaces_id" IMMEDIATE; ALTER TABLE "page_blocks" DROP CONSTRAINT "page_blocks_workspace_id_b051825d_fk_workspaces_id";
ALTER TABLE "page_blocks" DROP COLUMN "workspace_id" CASCADE;
ALTER TABLE "page_favorites" DROP CONSTRAINT "page_favorites_page_id_user_id_6e2c24ba_uniq";
SET CONSTRAINTS "page_favorites_created_by_id_3b672270_fk_users_id" IMMEDIATE; ALTER TABLE "page_favorites" DROP CONSTRAINT "page_favorites_created_by_id_3b672270_fk_users_id";
ALTER TABLE "page_favorites" DROP COLUMN "created_by_id" CASCADE;
SET CONSTRAINTS "page_favorites_page_id_0896034b_fk_pages_id" IMMEDIATE; ALTER TABLE "page_favorites" DROP CONSTRAINT "page_favorites_page_id_0896034b_fk_pages_id";
ALTER TABLE "page_favorites" DROP COLUMN "page_id" CASCADE;
SET CONSTRAINTS "page_favorites_project_id_e0e3c871_fk_projects_id" IMMEDIATE; ALTER TABLE "page_favorites" DROP CONSTRAINT "page_favorites_project_id_e0e3c871_fk_projects_id";
ALTER TABLE "page_favorites" DROP COLUMN "project_id" CASCADE;
SET CONSTRAINTS "page_favorites_updated_by_id_623c7ac5_fk_users_id" IMMEDIATE; ALTER TABLE "page_favorites" DROP CONSTRAINT "page_favorites_updated_by_id_623c7ac5_fk_users_id";
ALTER TABLE "page_favorites" DROP COLUMN "updated_by_id" CASCADE;
SET CONSTRAINTS "page_favorites_user_id_162640a9_fk_users_id" IMMEDIATE; ALTER TABLE "page_favorites" DROP CONSTRAINT "page_favorites_user_id_162640a9_fk_users_id";
ALTER TABLE "page_favorites" DROP COLUMN "user_id" CASCADE;
SET CONSTRAINTS "page_favorites_workspace_id_4b7858d9_fk_workspaces_id" IMMEDIATE; ALTER TABLE "page_favorites" DROP CONSTRAINT "page_favorites_workspace_id_4b7858d9_fk_workspaces_id";
ALTER TABLE "page_favorites" DROP COLUMN "workspace_id" CASCADE;
ALTER TABLE "project_favorites" DROP CONSTRAINT "project_favorites_project_id_user_id_e7e43312_uniq";
SET CONSTRAINTS "project_favorites_created_by_id_613c0717_fk_users_id" IMMEDIATE; ALTER TABLE "project_favorites" DROP CONSTRAINT "project_favorites_created_by_id_613c0717_fk_users_id";
ALTER TABLE "project_favorites" DROP COLUMN "created_by_id" CASCADE;
SET CONSTRAINTS "project_favorites_project_id_df76634d_fk_projects_id" IMMEDIATE; ALTER TABLE "project_favorites" DROP CONSTRAINT "project_favorites_project_id_df76634d_fk_projects_id";
ALTER TABLE "project_favorites" DROP COLUMN "project_id" CASCADE;
SET CONSTRAINTS "project_favorites_updated_by_id_2a663e4d_fk_users_id" IMMEDIATE; ALTER TABLE "project_favorites" DROP CONSTRAINT "project_favorites_updated_by_id_2a663e4d_fk_users_id";
ALTER TABLE "project_favorites" DROP COLUMN "updated_by_id" CASCADE;
SET CONSTRAINTS "project_favorites_user_id_500f4f5b_fk_users_id" IMMEDIATE; ALTER TABLE "project_favorites" DROP CONSTRAINT "project_favorites_user_id_500f4f5b_fk_users_id";
ALTER TABLE "project_favorites" DROP COLUMN "user_id" CASCADE;
SET CONSTRAINTS "project_favorites_workspace_id_fa980513_fk_workspaces_id" IMMEDIATE; ALTER TABLE "project_favorites" DROP CONSTRAINT "project_favorites_workspace_id_fa980513_fk_workspaces_id";
ALTER TABLE "project_favorites" DROP COLUMN "workspace_id" CASCADE;
ALTER TABLE "issue_types" ADD COLUMN "external_id" varchar(255) NULL;
ALTER TABLE "issue_types" ADD COLUMN "external_source" varchar(255) NULL;
DROP TABLE "cycle_favorites" CASCADE;
DROP TABLE "global_views" CASCADE;
DROP TABLE "view_favorites" CASCADE;
DROP TABLE "module_favorites" CASCADE;
DROP TABLE "page_blocks" CASCADE;
DROP TABLE "page_favorites" CASCADE;
DROP TABLE "project_favorites" CASCADE;
